### ISSUE TITLE
no cover-art for unknown albums in exaile v3.4.0

### ISSUE THREAD

**Issue by FiSHYsolutions** [exaile/exaile#10]
a lot of my mp3-files are dj-sets which are not part of a dedicated album. my dir-tree usually looks like `<interpret>/<album>/<filename>.mp3` but in cases of files without an "album"-title the hierarchy switches to `<interpret>/<filename>.mp3`. all of my files are tagged by id3v2.4 and the tags always include a cover.jpg wich is placed in the same folder of the mp3, but of course it's embedded in the id3-tag, too. so far so good.

what is the problem? if i play a mp3-file without a album-tag (e.g. "unknown album"), exaile v3.4.0 doesn't show the cover.jpg (neither tag nor local). so i can fetch the cover by rightclicking the area, where the cover should be and then i choose (options-dialog) one of both covers (tag or local file). but if i press "pause", "next", "prev" or double click the track to play it from the very beginning, exaile losts the coverart of the specific file. there is no way to save the state, so every file without album-tag has spuriously no cover-art.

OS: xubuntu 14.04.1 lts

**Comment by sjohannes** [comment]
This should be much better after #501 (which will be in Exaile 4.0). In the worst case, it's possible to specify the `musicbrainz_albumid` tag to override all of Exaile's heuristics for album covers.
