### ISSUE TITLE
Can't update and clean database. 

### ISSUE THREAD

**Issue by XzuRukneg** [exaile/exaile#107]
Tested with exail 3.3, 3.4 and 3.5.

Look
http://www.zimagez.com/zimage/capturedcran-16062015-230404.php
This folder is empty!
The data base must be clean. It is not, the old is still present.

EDIt: oups, bad screen shot better here: http://www.zimagez.com/zimage/capturedcran-16062015-232040.php

**Comment by genodeftest** [comment]
Can you please give more detailled steps how you ran into this? Or do you have console output? Maybe exaile threw an error.

I cannot reproduce this issue by simply adding and deleting folders to my collection.

**Comment by XzuRukneg** [comment]
Sorry, I don't have recipe to reproduce.
I'm simply checking (for tags) my data base folder's one by one.
And suddenly, all my old collection (re)appears! 

Try: select no folder for database: exaile says database is empty.
Then add an empty folder and update. 

I'll like to reset (delete?) the database file. 

Term outup:
:~$ exaile 
INFO    : Loading Exaile 3.4.5 on Python 2.7.3...
INFO    : Loading settings...
INFO    : Using fr_FR UTF-8 locale
INFO    : Loading plugins...
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Using GTK+ 2.24.10
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
INFO    : Scanning library: file:///home/kxzu/Bureau/empty
INFO    : Scan completed: file:///home/kxzu/Bureau/empty
INFO    : Exaile is shutting down...
INFO    : Disabling plugins...
INFO    : Saving state...
INFO    : Bye!

**Comment by XzuRukneg** [comment]
Please, how can I reset my broken database?

**Comment by genodeftest** [comment]
(On Linux/Unix): Just delete the file `~/.local/share/exaile/music.db`, in your case that should be `/home/kxzu/.local/share/exaile/music.db`

**Comment by XzuRukneg** [comment]
Ok, thanks.
I think the problem comes from the multi-vesion I've got: 3.4.5 from git, and another packaged for ubuntu12.04 from ppa.

Delete the file don't resolve the problem (23 Mo!).
But after uninstall the packaged version and re-delete the file, then it's ok, my data base is ok. 
Now that works properly.
I think issue is resolved. (I stay with git version)

**Comment by genodeftest** [comment]
Ok, Ubuntu 12.04 is quite outdated still using exaile 0.3.2, which is more than 3 years old. This can be the cause of your problem.

If the problem is gone, can you please close this issue?

**Comment by XzuRukneg** [comment]
Sure!
Bye

**Comment by XzuRukneg** [comment]
Problem is back!
I'm just checking all my folders one by one.
So I select one for data base, and then remove and setup another one, etc.. 
then: broken data base. 
I can give the broken "music.db" file if necessary.

**Comment by genodeftest** [comment]
Is there any error message printed to console or log files below `~/.cache/exaile/logs` related to this problem?

**Comment by XzuRukneg** [comment]
Sorry, don't see anything. 
~/.cache/exaile/logs contain no log.

Don't found also what reproduce the problem.

**Comment by virtuald** [comment]
Without more information, this is difficult to diagnose. Closing.
