### ISSUE TITLE
Windows show Python Icon

### ISSUE THREAD

**Issue by mtangoo** [exaile/exaile#108]
Just moved from Linux due to some private circumstances. Now I miss Rhythmbox. But since my second choice was Exaile, so here Iam. 

Now instead of Exaile Icon, I get the Python icon. 
Please Fix it!

**Comment by sjohannes** [comment]
This works fine for me when running from a non-installed Exaile source tree. I wonder if it only affects installations.

**Comment by mtangoo** [comment]
@sjohannes I used installer. I think its doing funny things somehwere!

**Comment by mtangoo** [comment]
I no longer use Exaile!
