### ISSUE TITLE
feature request: Tag from file name and/or path

### ISSUE THREAD

**Issue by XzuRukneg** [exaile/exaile#109]
Like amarok1 did, for old and untagged files, that will be nice to deduce tag (artist, album, song number and name) from file name, and/or path name.
This feature maybe be customizable,like: 
~/artiste - album/song number - song name
or
/artiste - album -song number - song name
or 
artist/album/
etc..

That will be very very helpful for old audio collection (like mine!!).

**Comment by virtuald** [comment]
Maybe. Sounds like MusicBrainz picard is really what you're looking for, or some software that's designed to deal with that (there are a LOT of mp3 taggers out there). Exaile doesn't have to do everything, and I suspect this is one of those things it really shouldn't try to do unless someone wants to take the time to do it.

**Comment by XzuRukneg** [comment]
I understand your point of view.
I don't agree because exaile manage tag.
I prefer use only one soft for audio play/sort/tag etc...
But maybe you're wright.

**Comment by genodeftest** [comment]
Or [Mp3tag](http://www.mp3tag.de/en/) for Windows or [puddletag](http://puddletag.sourceforge.net/). I've tested both of them and they are quite usable. [Alternativeto.net](https://alternativeto.net/software/mp3tag/) lists some more.

**Comment by XzuRukneg** [comment]
Or "asy tag" or ... Amarok 1! :dancer: 
Ok, I close!
