### ISSUE TITLE
[gi] Add more types of requirements to plugin requirements

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#121]
Originally mentioned in https://github.com/exaile/exaile/pull/116. We can't put gi dependencies in plugin requirements because `imp.find_module` does not do subpackages.

@sjohannes found that a way to detect gi dependencies without explicitly loading them is the following:

```
import gi
has_webkit2 = bool(gi.importer.repository.enumerate_versions('WebKit2'))
```

He also mentioned that adding a special syntax like "gi:Webkit2" to activate such detection. I like that, as opposed to a separate key for `RequiredGiModules`.

@genodeftest mentioned the idea of adding extra 'required' fields to the plugin info, such as for dbus services. I'm not sure how I feel about this, partially because I don't know enough about how some of the plugins use dbus.

**Comment by genodeftest** [comment]
To make sure I understood you correctly I repeat what you are proposing here:
Expand the `RequiredModules` property in `PLUGININFO` to enable depending on gi modules. This could be done by adding a `gi:` prefix to e.g. depend on `WebKit2` by writing
`RequiredModules=['gi:WebKit2']`

Is that correct? If yes, I think it is a good idea, there is no need for a separate key `RequiredGiModules`. The `gi:` syntax has no backwards compatibility, but I doubt anyone will provide the same plugin (file) for both exaile 3.4 and 3.5. A separate key would just be ignored.

**Comment by sjohannes** [comment]
To expand on why we can't use the current module-checking method for this: Currently we use `imp.find_module('foo')` to check that the module *foo* exists. `find_module` is very simplistic, and seems to only check for `foo.py` in `sys.path`; it doesn't even support checking for submodules (e.g. `foo.bar`) and it definitely doesn't support GI's use of a very-rarely used Python feature: [import hooks](https://www.python.org/dev/peps/pep-0302/) (which lets us load a *WebKit2* module without an actual `WebKit2.py` anywhere).

> To make sure I understood you correctly I repeat what you are proposing here:

Yep, the suggestion is to add that `gi:` prefix. In the future if there are other sets of modules that need this special treatment, we can add other prefixes.

**Comment by lazka** [comment]
Please use the public API instead of pygobject internals:

```python
from gi.repository import GIRepository
GIRepository.Repository.get_default().enumerate_versions("WebKit2")
```
