### ISSUE TITLE
Year column

### ISSUE THREAD

**Issue by SaiyanRiku** [exaile/exaile#126]
Exaile provides a date column, but MusicBrainz tag the field with a complete date like '2012-12-12'. But i would like to display only the year. It should be useful to get a year column that parse the date and just display the year.

Thank you for this great software.

**Comment by virtuald** [comment]
See https://github.com/exaile/exaile/pull/127

**Comment by virtuald** [comment]
@SaiyanRiku were you able to try out the fix?

**Comment by SaiyanRiku** [comment]
I tested, this is perfect. Thank you.

**Comment by SaiyanRiku** [comment]
In fact, is it possible to display nothing instead of "Unknown"?

**Comment by virtuald** [comment]
It is "possible", but there is a difference between not present and empty. I suppose it would be easy enough to add an option to change it, but I'm not quite sure how I feel about that.

**Comment by SaiyanRiku** [comment]
You're right, i understand. I think an option will be too much just for this. In fact, what i want is to view better when the tag is empty or not present. So maybe just displaying a single characters like "/" or "...." when the tag is not present will be enough for me, but i don't know if it will look nice. Or maybe since a computed column is not important to differentiate both case. This is just a suggestion but having the column is already very nice.
