### ISSUE TITLE
Generate & install Bash completion file

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#132]
A simple one that just calls [`_parse_help` from bash-completion](https://anonscm.debian.org/cgit/bash-completion/bash-completion.git/tree/bash_completion?id=00abd48e5b1d5d79fff46b7f791b2b90d1d6953b#n771) is good enough, but I also have experimental code that generates a completion file from our optparse object in [sjohannes:bashcomp](https://github.com/exaile/exaile/compare/gi...sjohannes:bashcomp) which is marginally smarter.

**Comment by virtuald** [comment]
Fixed in 609db72bfa54a61131424d3aad27b7550559d0c6
