### ISSUE TITLE
Auto-complete "artiste" tag

### ISSUE THREAD

**Issue by XzuRukneg** [exaile/exaile#136]
Hi.
If i remember, in the past their was an auto-completion for the "artiste" tag. 
Can we get back this great function please? ( and anyway that can also prevent typing error).
(if I'm wrong it's a feature request!)
Thanks.

**Comment by virtuald** [comment]
What do you mean by autocomplete? Where? There's a lot of places in Exaile that one can type.

**Comment by XzuRukneg** [comment]
Example: right clic on a track in play list and "properties".
I think that would be very helpful for Ablum and Artiste tag.

**Comment by virtuald** [comment]
I'm not aware of any such feature, but it's possible it was previously implemented. It would probably require:

* Compiling an index of the field to be autocompleted -- could be done on either a per-collection or per-playlist basis. Autocomplete based on the contents of the current playlist probably would be very simple and fast.
* Feeding that index into some Gtk widget that supported autocomplete ([GtkEntryCompletion](https://developer.gnome.org/gtk3/stable/GtkEntryCompletion.html))

I welcome pull requests.

**Comment by XzuRukneg** [comment]
And what about auto-set tag from file name? :D 
(I know, exaile is not a tag editor, but what I use to edit my tag?->exaile! of course, because it's my collection manager!)

**Comment by virtuald** [comment]
There are a lot of tag editors that do that type of thing far better than Exaile ever will. While I'm not opposed to someone building the functionality in, since it would be useful, but I will not personally create such a thing.
