### ISSUE TITLE
UI freeze starting daap playlist (and sometimes local files)

### ISSUE THREAD

**Issue by sarnold** [exaile/exaile#137]
Enabling a daap server shows a blank tab but a saved playlist will start playing daap URIs, albeit with a UI freeze that leaves it completely unresponsive and takes a kill -s 9 to get its attention.

**Comment by virtuald** [comment]
What version of Exaile? Also, I've never used DAAP, so this might be difficult to diagnose/fix...

**Comment by sarnold** [comment]
3.4.5, latest in Gentoo.  Looks like the maintainer dep'd on gst-0.10 so I'm updating the ebuild now.  This is just the daap client part, using mt-daapd on local network.  Works fine in the old version of exaile (I have a slightly hacked 0.3.2.1 ebuild I kept around for a while).

**Comment by sarnold** [comment]
Okay, rebuilt with new deps, made sure IPv6 is working on both ends, and tried daap support again with ipv6 support enabled, same result: blank daap server tab, right-click properties and "refresh server list" do nothing (tab remains blank).  Starting a daap playlist plays the first song but freezes the UI.
![exaile-blank_daap-server_tab_screenshot_2015-09-16_12-04-19](https://cloud.githubusercontent.com/assets/300461/9915310/3d06a61c-5c6b-11e5-97b5-5c84de270013.png)

**Comment by virtuald** [comment]
After the GTK3 migration is complete, I'll take a look at this. I'm sure it's some simple mistake the plugin is making...

**Comment by sarnold** [comment]
Right-click "refresh server..." gives this traceback:

INFO    : DAAP share found: 'wimpy-tunes' at (fe80::240:63ff:fee3:4003,3689).
INFO    : DAAP share found: 'wimpy-tunes' at (192.168.NNN.NNN,3689).
adding menu wimpy-tunes (wimpy.local) 20wimpy-tunes_daap._tcplocal
...
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/exaile/plugins/daapclient/__init__.py", line 660, in refresh
    self.net_collection.rescan_libraries()
  File "/usr/lib64/exaile/xl/collection.py", line 270, in rescan_libraries
    library.rescan(notify_interval=scan_interval, force_update=force_update)
TypeError: rescan() got an unexpected keyword argument 'force_update'

Traceback (most recent call last):
  File "/usr/share/exaile/plugins/daapclient/__init__.py", line 648, in <lambda>
    callback = lambda *x: mgr.refresh_share(self.name)))
  File "/usr/share/exaile/plugins/daapclient/__init__.py", line 391, in refresh_share
    % (name, panel.daap_share.session.revision, rev))
TypeError: not all arguments converted during string formatting

**Comment by sarnold** [comment]
Okay, apparently it's not just with a daap playlist; here's a local CD-rip to flac that has the same symptom.  Not that I can tell you how to reproduce it, since mostly it works with local files.  I went ahead made sure the tags were clean in the suspect files and did the slow rebuild and still no joy:

![screenshot_exaile-ui](https://cloud.githubusercontent.com/assets/300461/10834532/57d08fc2-7e57-11e5-81f3-f38d1b1da0dc.png)

![screenshot_exaile-ui-2](https://cloud.githubusercontent.com/assets/300461/10834547/709bfb68-7e57-11e5-87a5-5fad9f1ebbf6.png)

**Comment by sarnold** [comment]
Here's what i get with latest gi commit build:

INFO    : Loading Exaile 3.4.5 on Python 2.7.10...
INFO    : Loading settings...
INFO    : Using en_US UTF-8 locale
INFO    : Loading plugins...
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
INFO    : Attempting to connect to AudioScrobbler (http://post.audioscrobbler.com/)
INFO    : Loading collection...
INFO    : Logged in successfully to AudioScrobbler (http://post.audioscrobbler.com/)
INFO    : Connected to AudioScrobbler
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Using GTK+ 2.24.28
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
INFO    : WARNING: could not open podcast file
No bp log location saved, using default.
[000:000] Cpu: 16.5.3, x4, 3000Mhz, 3951MB
[000:000] Computer model: Not available
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is Gtk2.
[000:001] Using Gtk2 toolkit
[000:001] No bp log location saved, using default.
[000:002] Cpu: 16.5.3, x4, 3000Mhz, 3951MB
[000:002] Computer model: Not available
[000:002] Browser XEmbed support present: 1
[000:002] Browser toolkit is Gtk2.
[000:002] Using Gtk2 toolkit
Vector smash protection is enabled.
Vector smash protection is enabled.
No bp log location saved, using default.
[000:000] Cpu: 16.5.3, x4, 3000Mhz, 3951MB
[000:000] Computer model: Not available
[000:002] No bp log location saved, using default.
[000:002] Cpu: 16.5.3, x4, 3000Mhz, 3951MB
[000:002] Computer model: Not available
INFO    : populate: ('DesktopEntry',)
INFO    : populate: ('PlaybackStatus', 'Metadata', 'CanGoNext', 'CanGoPrevious', 'CanPause', CanPlay')
INFO    : populate: ('CanGoNext', 'CanGoPrevious')
INFO    : Playing file:///home/sarnold/flac/rolling_stones/sticky_fingers_bonus_cd/01_brown_sugar_with_eric_clapton.flac
INFO    : populate: (('PlaybackStatus', 'Playing'), 'Metadata', 'CanGoNext', 'CanGoPrevious', 'CanPause', 'CanPlay')
INFO    : populate: ('Metadata',)
INFO    : populate: ('Metadata',)
/usr/share/exaile/plugins/lyricsviewer/__init__.py:247: Warning: Source ID 14701 was not found when attempting to remove it
  glib.source_remove(self._lyrics_id)
INFO    : populate: (('PlaybackStatus', 'Playing'), 'Metadata', 'CanGoNext', 'CanGoPrevious', 'CanPause', 'CanPlay')

(exaile.py:5475): GStreamer-CRITICAL **: gst_caps_copy: assertion 'GST_IS_CAPS (caps)' failed
/usr/lib64/exaile/xlgui/__init__.py:77: Warning: cannot register existing type 'GstObject'
  gtk.main()
/usr/lib64/exaile/xlgui/__init__.py:77: Warning: g_once_init_leave: assertion 'result != 0' failed
  gtk.main()
/usr/lib64/exaile/xlgui/__init__.py:77: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  gtk.main()
(exaile.py:5475): GStreamer-CRITICAL **: gst_element_class_set_metadata: assertion 'GST_IS_ELEMENT_CLASS (klass)' failed
/usr/lib64/exaile/xlgui/__init__.py:77: Warning: invalid cast from 'GstPlayBin' to 'GstStreamVolume'
  gtk.main()
/usr/lib64/exaile/xlgui/__init__.py:77: Warning: g_object_set_valist: object class 'GstPlayBin' has no property named 'mute'
  gtk.main()
/usr/lib64/exaile/xlgui/__init__.py:77: Warning: /var/tmp/portage/dev-libs/glib-2.44.1/work/glib-2.44.1/gobject/gsignal.c:2451: signal 'video-changed' is invalid for instance '0x151a550' of type 'GstPlayBin'
  gtk.main()
/usr/lib64/exaile/xlgui/__init__.py:77: Warning: /var/tmp/portage/dev-libs/glib-2.44.1/work/glib-2.44.1/gobject/gsignal.c:2451: signal 'audio-changed' is invalid for instance '0x151a550' of type 'GstPlayBin'  gtk.main()
(exaile.py:5475): GStreamer-CRITICAL **: gst_caps_copy: assertion 'GST_IS_CAPS (caps)' failed
INFO    : Attempting to submit "Now Playing" information to AudioScrobbler...
INFO    : Submitted "Now Playing" successfully to AudioScrobbler

**Comment by virtuald** [comment]
Definitely not the gi branch, gi branch won't work with Gtk+ 2, and is version 4.0.0-dev

**Comment by sarnold** [comment]
So this was(is?) an issue on master, whereas gi is only missing the daap display in the server tab.  Otherwise, daap playlists play fine from the playlist tab, no UI freeze.

Should we close this one and open a new one for the daap server display on gi?

**Comment by virtuald** [comment]
Yes, as the bug on master is unlikely to get fixed.
