### ISSUE TITLE
hacked updates to 0.3.2.1

### ISSUE THREAD

**Issue by sarnold** [exaile/exaile#138]
Before I knew there was a version 3.x I hacked up the old version to work with some of the newer Python dependencies, plus a couple of patches and kept it in my overlay:

https://github.com/sarnold/portage-overlay/tree/master/media-sound/exaile

Since there's still an old versions link, maybe some of this is useful(?)

**Comment by virtuald** [comment]
I suppose I should add a note to the site that old versions are completely unsupported. The patches seem very minimal, so if someone finds this issue then it might be useful for them. However, I don't want to confuse new users by linking to this.
