### ISSUE TITLE
Maybe bug (Exaile  3.4.5)

### ISSUE THREAD

**Issue by XzuRukneg** [exaile/exaile#139]
I've made a playlist using simple custom intelligent play list (30random tracks).
Exaile stop playing after 3th track.
Terminal output here: http://pastebin.com/njfGWNgS

I can play manually the 3th or 4th track, but something get wrong when approaching the last 10 second of the 3th track (Concerto pour violon et orchestre en Mi mineur, Op.64 - III. Allegretto non troppo-Allegro molto vivace).

Error message: Bad header.

**Comment by virtuald** [comment]
I'm sure this is a bug. However, the audio engine has been completely rewritten for the next version of Exaile, so I'm not interested in fixing this for 3.4.x. Exaile 4 isn't quite ready for primetime yet, but hopefully will be later this fall.
