### ISSUE TITLE
[gi] [main.py:1067] AttributeError: 'Window' object has no attribute 'window'

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#142]
I am using the current exaile version from git master (5b28f6c).

With "Show tray icon", "Minimize to tray" and "Close to tray" enabled (default preferences otherwise), I get this error message on console *every* time the exaile window changes its focus:
~~~
Traceback (most recent call last):
  File "/path/to/exaile/xlgui/main.py", line 1067, in window_state_change_event
    elif window.window.property_get('_NET_WM_STATE') is None:
AttributeError: 'Window' object has no attribute 'window'
~~~
This doesn't work since you can't (easily) get the GdkWindow from a GtkWindow and this property doesn't seem to be available under wayland. I couldn't find out how to fix this.

**Comment by virtuald** [comment]
I think I fixed this. Let me know if you still encounter problems.

**Comment by genodeftest** [comment]
Confirmed. Thank you!
