### ISSUE TITLE
Installation on Windows XP : can't find Python

### ISSUE THREAD

**Issue by Petrouchka** [exaile/exaile#146]
I'm installing exaile 3.4.5 on Windows XP. It tries to download Python but I've got this error :
![capture](https://cloud.githubusercontent.com/assets/3955499/10315851/ea1b42ee-6c5c-11e5-91f3-166083ed722a.png)
It's strange because
http://python.org/ftp/python/2.7.8/python-2.7.8.msi
http://www.python.org/ftp/python/2.7.8/python-2.7.8.msi
and
https://www.python.org/ftp/python/2.7.8/python-2.7.8.msi
are working.

**Comment by genodeftest** [comment]
Maybe the installer is unable to handle HTTP redirections. I am getting a redirection from http://python.org/ftp/python/2.7.8/python-2.7.8.msi to https://www.python.org/ftp/python/2.7.8/python-2.7.8.msi when trying to download the installer.

Btw: The download URL should be encrypted (HTTPS) anyway for basic security.

PS: Windows XP is really outdated. You should update to a newer operating system with (update) support.

**Comment by Petrouchka** [comment]
It works now, I had a problem with Windows.
