### ISSUE TITLE
exaile-3.4.5: scrolling bug in collections with "monitored" enabled on large collection

### ISSUE THREAD

**Issue by sarnold** [exaile/exaile#149]
Enable "monitored" on a flac collection large enough to require lots of scrolling to get to the end of the alphabet.  At some point it gets "stuck" and always returns to the top within a second or two after scrolling down to anywhere below the top.  Clicking on any of the arrows to expand an entry closes again before you can click anything.

**Comment by sarnold** [comment]
Sorry, forgot to mention the environment stuff:

Portage 2.2.22 (python 2.7.10-final-0, default/linux/amd64/13.0/desktop, gcc-4.9.3, glibc-2.21-r1, 4.2.0-gentoo-r1 x86_64)
=================================================================
System uname: Linux-4.2.0-gentoo-r1-x86_64-AMD_Athlon-tm-_II_X4_640_Processor-with-gentoo-2.2
KiB Mem:     4046600 total,    755664 free
KiB Swap:    8388604 total,   8371176 free
Timestamp of repository gentoo: Fri, 09 Oct 2015 10:30:01 +0000
sh bash 4.3_p42
ld GNU gold (Gentoo 2.25.1 p1.1 2.25.1) 1.11
distcc 3.2rc1 x86_64-pc-linux-gnu [enabled]
ccache version 3.2.3 [enabled]
app-shells/bash:          4.3_p42::gentoo
dev-java/java-config:     2.2.0::gentoo
dev-lang/perl:            5.22.0::gentoo
dev-lang/python:          2.7.10::gentoo, 3.3.5-r2::gentoo, 3.4.3::gentoo
dev-util/ccache:          3.2.3::gentoo
dev-util/cmake:           3.3.2::gentoo
dev-util/pkgconfig:       0.29::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.17::gentoo
sys-apps/sandbox:         2.9::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69-r1::gentoo
sys-devel/automake:       1.10.3-r1::gentoo, 1.11.6-r1::gentoo, 1.12.6::gentoo, 1.13.4::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.6.3::gentoo, 4.7.3-r1::gentoo, 4.8.4::gentoo, 4.9.3::gentoo
sys-devel/gcc-config:     1.8::gentoo
sys-devel/libtool:        2.4.6-r1::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.2::gentoo (virtual/os-headers)
sys-libs/glibc:           2.21-r1::nerdboy-local

**Comment by virtuald** [comment]
Is this specific to flac, or any collection? And, how large is large? Having a way to reproduce this would make it easier to fix it.

**Comment by sarnold** [comment]
I don't think it's specific to flac at all (I also have mp3 on mtdaap and local files) and the the local flac collection is less than 500 folders (say 10-15 tracks per folder ave.).

**Comment by genodeftest** [comment]
Exaile now uses Gtk+ 3.x. Please test our beta release https://github.com/exaile/exaile/releases/tag/4.0.0-beta1. Is this issue still present?

**Comment by genodeftest** [comment]
@sarnold : I cannot reproduce this bug with [4.0.0 beta 2](https://github.com/exaile/exaile/releases/latest) any more, neither on Windows 10 nor Fedora (Gtk+ 3.22.15). Please add a comment and feel free to reopen this issue if you can reproduce it with that version.
