### ISSUE TITLE
[gi] [lyrics viewer] warning about source IDs not found

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#157]
Every time I start a new playback while a file is already playing, I get this message on stdout:
```
exaile/plugins/lyricsviewer/__init__.py:252: Warning: Source ID 274 was not found when attempting to remove it
  GLib.source_remove(self._lyrics_id)
```
This does not happen with the first file I play, but with all files afterwards while another file is still playing.

**Comment by eri-trabiccolo** [comment]
Yes this was the reason of:
https://github.com/exaile/exaile/pull/129
"avoid warning when trying to remove a glib source already dismissed"

But that way to avoid it's "strange" though I haven't experienced any issue with it.
Anyway it's a warning which doesn't seem to be harbinger of whatever error, so maybe it can be ignored.

**Comment by virtuald** [comment]
I fixed some threading issues, and the underlying problem with the source_id. Let me know if you find more issues.

**Comment by genodeftest** [comment]
Please reopen this issue. It is not fixed with #129. Still present in current gi versions as of today (4.0.0dev 65dc822). The message now changed to
```
exaile/xlgui/widgets/playback.py:361: Warning: Source ID 2960 was not found when attempting to remove it
  GLib.source_remove(self.__timeout_id)
```

**Comment by eri-trabiccolo** [comment]
Not able to reproduce it here.
Works fine here.
Also are you sure is related to the lyricsviewer ?
The warning talks about the playback widget so..

**Comment by virtuald** [comment]
The playback.py message is most certainly a separate bug. I'll look at it tonight.

**Comment by genodeftest** [comment]
Ok, you are right, the issue I referred to in comment https://github.com/exaile/exaile/issues/157#issuecomment-149595979 is unrelated to the lyrics viewer. I'll open a separate bug report.
