### ISSUE TITLE
[gi] [ProgressMonitor] Gtk Warnings at startup

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#158]
When starting exaile (git master at 4.0.0dev+ecddf20) for the second time from a configuration directory with a collection configured, I get these Gtk Warnings at startup:
```
(exaile.py:25499): Gtk-WARNING **: GtkBox 0x2d60e40 is mapped but visible=1 child_visible=1 parent ProgressMonitor 0x216e660 mapped=0

(exaile.py:25499): Gtk-WARNING **: GtkButton 0x2d58360 is mapped but visible=1 child_visible=1 parent ProgressMonitor 0x216e660 mapped=0

(exaile.py:25499): Gtk-WARNING **: GtkProgressBar 0x2c7b450 is mapped but visible=1 child_visible=1 parent ProgressMonitor 0x216e660 mapped=0
```
This only happens with folder(s) added to the collection. It seems to be triggered by rescanning the collection at startup.

**Comment by virtuald** [comment]
I've seen them too, I've got some rework coming up for the event system, so maybe this will get fixed along the way.

**Comment by virtuald** [comment]
I'm not getting these errors anymore.
