### ISSUE TITLE
More plugins for streamed music

### ISSUE THREAD

**Issue by strebski** [exaile/exaile#16]
Would be great to see in Exaile some plugins (similar to already existed SomaFM and Icecast radio) to play streamed music from:
- http://jazzradio.com/
- http://www.rockradio.com/
- http://www.frescaradio.com/
- http://www.di.fm/
- http://www.radiotunes.com/

They are already "present" in Clementine music player :) that's why I'm still forced to use this player...

Thanks!

**Comment by virtuald** [comment]
As said previously, we're willing to include them if someone implements them -- PRs are encouraged! However, leaving this open isn't very useful, so I'm going to close it.
