### ISSUE TITLE
 [gi] [playback] warning about source IDs not found

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#160]
Source: https://github.com/exaile/exaile/issues/157#issuecomment-149595979

Steps to reproduce:
1. Try to play a file you can't play because you don't have the required codecs installed
2. play another file
3. watch stdout

With 4.0.0dev 65dc822 I get an error message
```
exaile/xlgui/widgets/playback.py:361: Warning: Source ID 2960 was not found when attempting to remove it
  GLib.source_remove(self.__timeout_id)
```

Additional info:
This issue is present with all plugins disabled.
This issue can not always be reproduced, looks like threading issues to me. I have a ~20% chance of hitting this issue.

**Comment by virtuald** [comment]
Should be fixed. Thanks for the testing support!

**Comment by genodeftest** [comment]
Thanks for fixing so fast!
