### ISSUE TITLE
[Windows] [NSIS Installer] Don't load python from an unencrypted website

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#165]
As I noted in https://github.com/exaile/exaile/issues/146#issuecomment-145945138 the download URL for python should be encrypted (HTTPS) for basic security (protection against simple man-in-the-middle attacks). For loading python from a HTTPS URL the NSIS preferences should be changed. I started that in https://github.com/genodeftest/exaile/commit/36fddc4da3c9ed7c4e3dd9f21d242580dcbb637c. Since I neither have nor use Windows nor have NSIS to test, I won't fix this issue.

**Comment by virtuald** [comment]
Given that we check the hash of the downloaded python, I'm not super worried about this. But, you're certainly right.

For Exaile 4.x, I'm strongly thinking to use the build system that @quodlibet uses, that way everything is in a single bundle and users don't have to worry about mixed versions of python or gtk or whatever. It'll make the download size a bit larger, but that seems fine to me. If we went that direction, this would be a moot point.

**Comment by virtuald** [comment]
No longer relevant due to new bundled installer.
