### ISSUE TITLE
Need to identify mechanism to import translations from launchpad

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#17]
Apparently, roundtripping bzr is really difficult. I've got a mirror of github setup at launchpad, but cannot seem to export the commits back into github the other direction. Need to identify a *safe* mechanism to do this, and document it.

**Comment by genodeftest** [comment]
Isn't this outdated since translations are managed on Weblate?

**Comment by virtuald** [comment]
Ha, good point.
