### ISSUE TITLE
[gi] [threading] exaile freezes while loading CD index

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#173]
Steps to reproduce:
1. start exaile
2. put a CD into your CD drive (if you still own one) and close it
3. try to use exaile

What happens:
Exaile freezes for some time (e.g. 10 seconds) until CD index is loaded.

Using current Git+gi master on Fedora 22 with udisks2

**Comment by virtuald** [comment]
I don't remember having this problem when I tried it this morning, but I'll look at it later.

**Comment by genodeftest** [comment]
This freeze also happens when you start importing from a CD using the folder icon in audio cd panel and then stop it.

**Comment by virtuald** [comment]
Cool, the second freeze happens for me. I can fix that.

**Comment by genodeftest** [comment]
I can't reproduce any of the bugs I listed above. Can anybody else? If no, feel free to close this bug.

The first thing (freeze when loading CD) doesn't happen any more to me.
The second (importing from CD) is resolved, instead a progress indicator is shown below the panels, including a "Stop" button.

**Comment by virtuald** [comment]
Alright, will close.
