### ISSUE TITLE
Ignore diacritics for search

### ISSUE THREAD

**Issue by SaiyanRiku** [exaile/exaile#176]
Exaile should ignore diacritics and accent when searching music on the library.

For example:
- searching "helene" should return result containing "Hélène".
- searching "coeur" should return result containing "cœur"

To help, I already did a function for one of my program in C with gtk to handle this. I hope this can work be adapted with python.

    gchar*
    g_utf8_removediacritics(const gchar *str, gssize len)
    {
        gchar *szNormalizedString;
        GString* szStringBuilder;
        gchar *szRes = NULL;
        gunichar c;
        gchar *szPtr = NULL;

        if(str != NULL){
            szNormalizedString = g_utf8_normalize (str, len, G_NORMALIZE_NFD);

            szStringBuilder = g_string_new ("");

            szPtr = szNormalizedString;
            while(szPtr){
                c = g_utf8_get_char(szPtr);
                if(c != '\0'){
                    if (!g_unichar_ismark(c)){
                        g_string_append_unichar (szStringBuilder, c);
                    }
                    szPtr = g_utf8_next_char (szPtr);
                }else{
                    szPtr = NULL;
                }
            }

            szRes = g_string_free (szStringBuilder, FALSE);
            g_free(szNormalizedString);
        }

        return szRes;
    }

Thank you in advance

**Comment by genodeftest** [comment]
Python provides a function for that: `unicodedata.normalize()`

**Comment by genodeftest** [comment]
https://stackoverflow.com/questions/517923/what-is-the-best-way-to-remove-accents-in-a-python-unicode-string and https://stackoverflow.com/questions/9042515/normalizing-unicode-text-to-filenames-etc-in-python show some possible solutions to this problem.
