### ISSUE TITLE
Migrate MPRIS plugin to MPRIS2

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#177]
Not actually sure what's needed here. Probably not that bad, right?

And if it does support MPRIS2, the plugin should probably mention that somewhere.

**Comment by virtuald** [comment]
Looks like there was a bug on [launchpad](https://bugs.launchpad.net/exaile/+bug/618483) about this.

@sjohannes you had suggested there that we remove the old dbus API and just implement MPRIS2. @sarnold says that there already exists a [plugin](https://github.com/sarnold/Exaile-Soundmenu-Indicator.git) that gets most of the way there. Seems like it would make sense to bring this under our wing -- though, probably still as a plugin?

**Comment by sarnold** [comment]
I don't do gnome3 any more, but this works with the xfce4-soundmenu-plugin:

https://github.com/sarnold/Exaile-Soundmenu-Indicator

**Comment by virtuald** [comment]
Addressed by b080ae5cdd11314a9d9469bc36b3a8bff646b977
