### ISSUE TITLE
GUI disappears on desktop change

### ISSUE THREAD

**Issue by pacocc** [exaile/exaile#18]
3.4.2 installed from source starts and runs fine but the gui disappears when switching to another (GNOME) desktop and returning to the exaile desktop.  'ps' shows it is still running (python2 -O exaile.py --startgui) but nothing is displayed.  Running 3.11.0-26-generic #45~precise1-Ubuntu.

**Comment by virtuald** [comment]
Any more information about this? Otherwise, will need to close as I can't reproduce it locally.

**Comment by virtuald** [comment]
Most likely, you had 'minimize to tray' enabled, and GNOME3 doesn't really show the tray icon particularly well -- perhaps a minimize accidentally happened. Without more information, closing this bug.
