### ISSUE TITLE
Please update or unbundle pylast

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#183]
Currently exaile is shipping an outdated copy of pylast in xl/externals/pylast.py. I don't know whether or not it works and am unable to test. Anyhow there are some minor changes and fixes in newer releases of pylast.
Some pitfalls (diff `xl/externals/pylast.py` vs. `__init__.py` from 1.4.2):
* pylast now depends on `six`
* `Artist.get_images()` is gone (wasn't used by exaile anyway)

other API changes:
* new functions:
  * `Artist.get_band_members()`
  * `Artist.get_correction()`
  * `Track.get_correction()`
  * `User.get_tagged_albums()`
  * `User.get_tagged_artists()`
  * `User.get_tagged_tracks()`
  * `cleanup_nodes()`
  * `_extract_artists()`
  * `_extract_albums()`
  * `_extract_tracks()`
* Functions with new optional parameters:
  * `User.get_recent_tracks()`
  * `_extract_element_tree()`

I guess this change should happen before publishing exaile 4.0 since shipping a 2 years old pylast.py is probably a bad idea.

I'd prefer removing pylast.py from xl.externals since it is available on most linux distributions as package anyway, it will be up-to-date without any work of exaile developers needed. And distro packagers usually don't like applications shipping 3rd party code due to their packaging strategy. I don't know the situation for Windows and Mac OS X though.

**Comment by virtuald** [comment]
I don't use last.fm stuff, so I don't really care either way. I would be fine with removing it.

**Comment by genodeftest** [comment]
Closing as of #185
