### ISSUE TITLE
user data migration to exaile 4.0 needed

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#188]
Due to the encoding changes I think exaile 4.0 needs to do a full rescan of the users collection.
I was using exaile with an old database some days ago and it still threw the well-known [encoding tracebacks](https://github.com/exaile/exaile/wiki/PyGI-migration-tasklist-%28GTK3-GStreamer-1.x%29#encoding-issues) when accessing data in its database.
Then I rescanned the whole collection and issues went gone.

**Comment by genodeftest** [comment]
This might not be necessary. Maybe I just ran into #192

**Comment by virtuald** [comment]
I think it's going to be hard to say until we see more people using it.

**Comment by genodeftest** [comment]
This should be in the 4.0 Milestone IMHO.

**Comment by virtuald** [comment]
You got it.

**Comment by genodeftest** [comment]
As @XzuRukneg confirmed in #413, user data migration is needed, at least for rescanning the database.

**Comment by virtuald** [comment]
I'm trying to create a bad database that needs migration, but I'm having trouble. I tried to match the setup of #413.

* Created an mp3 file with an `è` character in it; examined the file with hexdump, ensured that it was hex 'e8'. 
* Installed mutagen 1.31
* Created a database with Exaile 3.4, then opened with master
  * No error
* Created a database with Exaile 4.0-beta2, opened with master
  * No error
* Created a database with Exaile c0613121066705c193a9cf774c5e849f832c4f58 (circa October 2015), opened with master
  * No error

I also tried using the fr_FR locale via `LC_ALL=fr_FR`, but that didn't help to cause the error. Does anyone have a foolproof way of creating this error?

**Comment by sjohannes** [comment]
We never figured out how the bad data ended up there. Something caused the è to be written as a space (`%20`), which doesn't make sense to me (why space?).

It could be a bug in the metadata editor or writer, so try doing something that would cause the DB entry to be rewritten (edit a tag? rescan? I'm not too familiar with how they work) using one of the older versions.

The only other possible explanation I can think of is that the user renamed the file but forgot to rescan.

**Comment by virtuald** [comment]
It isn't possible to solve this issue without knowing what needs to be changed.

An alternative approach would be adding a setting that detects if a scan has been completed, and if it hasn't then we pop up a dialog telling the user that they should do a scan (and click yes to do it).

**Comment by genodeftest** [comment]
Since I don't see recent issues (bug reports) from the `-beta` and `-rc` releases, we may also just release 4.0 and hope that the issue happens very rarely or we fixed it in between. What do you think?

**Comment by virtuald** [comment]
I think without a reliable way to reproduce the issues this would be impossible to address. Probably the best we can do is add something to the user guide saying something to the effect of 'if you run into weird issues, rescan the collection'?

**Comment by genodeftest** [comment]
I've added this issue to the Exaile 4.0 release notes draft.

**Comment by sjohannes** [comment]
I think we all agree this can be closed now.
