### ISSUE TITLE
Smart playlists with criteria involving timestamps do not work

### ISSUE THREAD

**Issue by slosd** [exaile/exaile#19]
The search string for criteria like "Last time played" isn't constructed correctly. Also, playlists like "all tracks not played in the last X weeks/days/..." don't contain any songs for which the `__last_played` field isn't set yet, although that is probably the expected behaviour. 

[Here is a patch](https://gist.githubusercontent.com/slosd/22b7888d47b4d533d78a/raw/45c5d69d5cf773976e9d77f5eae7fa71a2ad73dd/0001-Fix-smart-playlists-involving-timestamps.patch) with changes I made to fix it for me personally. Possibly that's not how it should be properly fixed. In particular, I'm not sure if the localization I removed is actually desired.

**Comment by johannspies** [comment]
3.4.0 and 3.4.5 on Debian.  The smart play list using the following type of configuration, does not work.  The gui resets the setting to seconds:

(dp1
S'custom_params'
p2
(lp3
sS'name'
p4
Vouer as 4 dae
p5
sS'track_count'
p6
I-1
sS'random_sort'
p7
I00
sS'search_params'
p8
(lp9
(lp10
S'__last_played'
p11
aS'<'
a(lp12
F4
aVdays
p13
aaasS'or_match'
p14
I00
s.%                              

With this setting, when , in the gui, I open the edit option on the setting, I get:

Last played in the past 4 seconds.

**Comment by 4ndyD** [comment]
In 4.0, this has totally broken for me - a playlist meant to produce songs that have not been played in the last month now lists nothing, while a playlist meant to show the songs played in the last 24 hours now lists the entire library, even though the "last played" field in all those songs has various dates stretching out over a couple of years.
I don't know when this regression occurred though, as I made this jump from 3.3.2 that was available in my repository for Mint 18.3, 32bit XFCE.
