### ISSUE TITLE
[gi branch] Moodbar: depends on moodbar and gstreamer 0.10 package to be installed

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#190]
(I wanted to stop hijacking #99 so I put this in a new issue)

Exaile as from current gi branch does seem to require the `moodbar` package to be installed, but it does not complain if it is not.
Steps to reproduce:
1. don't have `moodbar` package installed
2. start exaile from gi branch
3. enable `moodbar` plugin
4. try to use moodbar

What happens:
No error message, no hint to the user that he is missing some software

PS: On Fedora 23 there is just a moodbar for gstreamer 0.10, not for 1.x. Is this any different on other platforms? The source code is not available any more and I can't find any related documentation except from [Amarok (outdated)](https://userbase.kde.org/Amarok/Manual/Various/Moodbar/en)

After installing moodbar (for gstreamer 0.10) I still cannot get this plugin working. Instead I see this error message:
```
Could not create element of type decodebin, please install it.
A list of plugins can be found at http://amarok.kde.org/wiki/Moodbar
Also please check that the moodbar package was installed
in the -->same prefix<-- as GStreamer: the moodbar binary
should be in the same directory as gst-inspect.
```
Exaile just displays an empty (background color) rectangle with borders, a marker and time. No colors.

Running `gst-inspect` (a.k.a. `gst-inspect-0.10`) shows moodbar is installed, `gst-inspect-1.0`doesn't. It seems like this plugin cannot work on gstreamer 1.0 on Fedora 23. On [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785883#5) they don't seem to have a replacement.
Where did you get your moodbar binary/source from? Is it for gstreamer 1.x?

**Comment by sjohannes** [comment]
There is no Moodbar executable for GStreamer 1 yet. Clementine has the closest thing, a Moodbar scanner for Gst 1, but it's integrated into the player and can't be used externally.

I'm currently using the old, Gst 0.10-based Moodbar to test the plugin. It should work as long as you have the plugins required to play the file. In your case, `decodebin` should be in gst-plugins-base. You will also need the usual decoders from -good, -ugly, etc.

**Comment by genodeftest** [comment]
Ok, now moodbar works for some codecs. For some I am getting these tracebacks when not having the same decoders installed.
```
Analyzing file /home/christian/Musik/24837b07fe0c.mp3
GStreamer does not how to decode the audio file.
You probably do not have the appropriate plugin installed.
Please see the wiki page at http://amarok.kde.org/wiki/Moodbar
for a plugin list, and troubleshooting tips.
Exception in thread SpectrumMoodbarGenerator:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 766, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/path/to/exaile/plugins/moodbar/generator.py", line 67, in generate
    os.remove(tmppath)
OSError: [Errno 2] File not found: '/tmp/tmpOHqk95moodbar.'
```
Could the moodbar plugin check (e.g. on activation) that the `moodbar` and `decodebin` executables are installed? If not it should notify the user that he needs to install moodbar and gstreamer-0.10.

**Comment by sjohannes** [comment]
I can add the note about Gst 0.10 plugins to the plugin description (in addition to moodbar). However, I can't check for the Gst plugins in code because it's not possible to mix Gst 0.10 and 1 libraries in one process.

**Comment by genodeftest** [comment]
How about running `moodbar --help`?

**Comment by sjohannes** [comment]
This commit makes the plugin fail during `enable()` if `moodbar --help` fails. It can't detect whether the appropriate Gst plugins are installed.

**Comment by genodeftest** [comment]
Thank you!
