### ISSUE TITLE
playlist search freezes

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#199]
I believe this only happens with large playlists, but I was able to trigger it at some point.

**Comment by strahlc** [comment]
I can confirm this on my 'Entire Library' playlist with 4783 entries.

Searches in this list brings up the gnome dialog 'No response from application. Force Quit / Wait'.
If I choose 'Wait' it takes over 1 minute and the search is done.

**Comment by genodeftest** [comment]
See #83

**Comment by virtuald** [comment]
Turns out, this isn't a thread related issue. For whatever reason, when refilter is called, the cursor changed event is called a LOT, which causes all sorts of things to happen in Exaile internally.

One thing in particular that happens is the group tagger plugin asks for the selected tracks to see if the length is 1... and on a large playlist, that takes a *long* time, and it probably happens for each item in the row.

Working on some fixes, but this points to needing greater introspection to what is happening in Exaile itself (thus why I filed #326).
