### ISSUE TITLE
Right-clicking an Autosized tracklist column header messes up column sizes

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#201]
1. Right-click column header, select Autosize.
2. Right-click column header again.

Expected:
- Column widths stay as they are.
- Columns stay in Autosize mode.

Actual:
- Columns widths shift wildly.
- If you hover on column header separators you'll notice that the columns are now resizable. Right-clicking again shows that it's now in Resizable mode.

**Comment by genodeftest** [comment]
I cannot reproduce this bug with [4.0.0 beta 2](https://github.com/exaile/exaile/releases/latest) any more, neither on Windows 10 nor Fedora (Gtk+ 3.22.15). Please add a comment and feel free to reopen this issue if you can reproduce it with that version.
