### ISSUE TITLE
[musicbrainzcovers plugin] Update or unbundle musicbrainzngs

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#203]
Exaile's version of [musicbrainzngs](https://github.com/alastair/python-musicbrainzngs) hasn't seen an update in 3 years. When fetching covers with musicbrainzngs enabled I'm getting many of these messages:
```
12:42:26,610:DEBUG   : in <ws2:release>, uncaught <text-representation> (python-musicbrainz-ngs)
12:42:26,610:DEBUG   : in <ws2:release>, uncaught <artist-credit> (python-musicbrainz-ngs)
12:42:26,610:DEBUG   : in <ws2:release>, uncaught <release-group> (python-musicbrainz-ngs)
12:42:26,610:DEBUG   : in <ws2:release>, uncaught <release-event-list> (python-musicbrainz-ngs)
12:42:26,610:DEBUG   : in <ws2:release>, uncaught <label-info-list> (python-musicbrainz-ngs)
12:42:26,611:DEBUG   : in <ws2:release>, uncaught <medium-list> (python-musicbrainz-ngs)
12:42:26,611:DEBUG   : in <ws2:release>, not delegating <title> (python-musicbrainz-ngs)
12:42:26,611:DEBUG   : in <ws2:release>, not delegating <status> (python-musicbrainz-ngs)
12:42:26,611:DEBUG   : in <ws2:name-credit>, uncaught <artist> (python-musicbrainz-ngs)
12:42:26,612:DEBUG   : in <ws2:artist>, not delegating <name> (python-musicbrainz-ngs)
12:42:26,612:DEBUG   : in <ws2:artist>, not delegating <sort-name> (python-musicbrainz-ngs)
12:42:26,612:DEBUG   : in <ws2:release-group>, not delegating <primary-type> (python-musicbrainz-ngs)
```
Which looks like API changed a lot.

This plugin is available on several distributions:
* [pypi/pip](https://pypi.python.org/pypi/musicbrainzngs/0.5)
* [Debian](https://packages.debian.org/stable/python/python-musicbrainzngs)
  * [Ubuntu](https://launchpad.net/ubuntu/+source/musicbrainzngs)
* [Arch Linux](https://www.archlinux.org/packages/community/any/python2-musicbrainzngs/)
* [Fedora](https://apps.fedoraproject.org/packages/python-musicbrainzngs)

I suggest either updating or unbundling this library. I guess this change should happen before publishing exaile 4.0 since shipping a 3 years old musicbrainzngs is probably a bad idea. I'd prefer unbundling if that's not a major issue for Windows users.

This is not critical since afaik we only fetch covers from musicbrainzngs. I tested fetching covers with the new API (version 0.5 from Fedora) and it works fine.

What's your opinion on that?

**Comment by virtuald** [comment]
Unbundle, and add the pypi package to `tools/installer/requirements.txt`.

**Comment by genodeftest** [comment]
Ok, I'll do that.
