### ISSUE TITLE
Please add support for the language ID3 tag (TLAN)

### ISSUE THREAD

**Issue by strahlc** [exaile/exaile#208]
It would be great to have support for the TLAN ID3 tag.
That way you could, for example, create smart playlists for French music.

**Comment by virtuald** [comment]
Seems easy enough. Any idea what the tags are for other file formats? (mp4, ogg/flac)

**Comment by strahlc** [comment]
Vorbis: LANGUAGE [1]
APE: Language [1]
mp4: ----:com.apple.iTunes:LANGUAGE [1]
FLAC: Language [2]


Sources:
  * [1] https://picard.musicbrainz.org/docs/mappings/
  * [2] http://forum.minimserver.com/archive/index.php?thread-2376.html

**Comment by virtuald** [comment]
Added support to master, tested on an mp3 file. Let me know if that works for you.

**Comment by strahlc** [comment]
@virtuald 
Thanks for implementing!
This works for me.

But I have a suggestion for an enhancement of this feature:

The id3 standard[1] says that the TLAN tag should be a three letter representation according ISO-639-2 [2].

> The language is represented with three characters according to ISO-639-2 [ISO-639-2]. If more than one language is used in the text their language codes should follow according to the amount of their usage, e.g. "eng" $00 "sve" $00

Maybe we can add a list of (translateable) language names[2]. This way the user see "Englisch", "French", "German", ... in the language column instead of "eng", "fra", "ger", ... .

Furthermore, in the track properties dialog, the user doesn't need to know the language code for the languages, he can just pick one from a drop down list.

Do we have support for drop-down lists in the track properties dialog?

[1] http://id3.org/id3v2.4.0-frames
[2] https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes

**Comment by virtuald** [comment]
Sounds like a separate bug report. ;)

It's not a bad idea. The properties might support lists (genre is something similar that comes to mind)... but that sounds a bit more involved.

**Comment by strahlc** [comment]
@virtuald 
> Sounds like a separate bug report. ;)

you're right. I've opened #255.
