### ISSUE TITLE
Import/export of playlists

### ISSUE THREAD

**Issue by tlnagy** [exaile/exaile#21]
It would be great to have the ability to import/export .m3u playlists with Exaile. Otherwise, it's difficult to see why users would invest the time to hand curate playlists if they are locked into Exaile only.

**Comment by virtuald** [comment]
.m3u playlists are supported. Right click on the playlist, and select 'export playlist'. There's also a corresponding import menu item somewhere as well.

**Comment by tlnagy** [comment]
I just found them. Sorry for the spam and thank you for the quick turn around. Perhaps the addition of an "Export playlist" option to the popup menu may be helpful for discoverability?

**Comment by virtuald** [comment]
Which popup menu?

**Comment by tlnagy** [comment]
The one that appears when right clicking inside the playlist tab. It already has a "New Playlist" option, as well as "Save" and "Save As" options. I didn't see the export playlist option on this menu or under the various menubar options (I guess I missed looking under File) so I assumed Exaile didn't have support for playlist import/export.

**Comment by virtuald** [comment]
Good point. Can you file that as a separate bug? I won't be able to get to it anytime in the near future, but it's definitely a good point. Thanks!
