### ISSUE TITLE
Apply tag with the GroupTagger or BPM with BPM plugin removes embedded album art from ID3

### ISSUE THREAD

**Issue by strahlc** [exaile/exaile#210]
This happens also when applying BPM from BPM Counter

**Comment by virtuald** [comment]
What version of mutagen do you have installed?

**Comment by strahlc** [comment]
1.27

**Comment by strahlc** [comment]
I've tried just version mutagen-1.31, but the error remains the same.

**Comment by virtuald** [comment]
Thanks. I'm on hiatus from Exaile until after FIRST Robotics season starts.. so, I won't personally have the time to look at these until maybe mid-January. However, perhaps someone else will...

**Comment by virtuald** [comment]
What type of file? mp3? Maybe that's where all of my album art disappeared...

**Comment by strahlc** [comment]
I can reproduce this bug only with my mp3 files (not with ogg or flac).

The embedded album art is removed from track after setting tags with the group tagger or after applying BPM with the BPM Counter plugin.

**Comment by virtuald** [comment]
Bug confirmed, working on diagnosing it.

**Comment by virtuald** [comment]
FYI, haven't gotten around to diagnosing this, figured I would add a unit test so this doesn't break on accident in the future... so I've spent a bunch of time fixing the unit tests and making them run on pushes/pull requests/etc, and adding new ones. Hopefully get to this later this week.
