### ISSUE TITLE
Editing a smart playlist unintentional changes some filter criteria

### ISSUE THREAD

**Issue by strahlc** [exaile/exaile#211]
When editing an existing smart playlist (for example to rename it), the smart playlist dialog reset some criteria to default values.

Examples:

Rename a playlist with the following criteria:
`'BPM' 'less than' 95`
changes the list criteria to: 
`'BPM' 'is' 95`

Rename a playlist with the following criteria:
`'Date added' 'not in the last' 4 'weeks'`
changes the list criteria to: 
`'Date added' 'in the last' 4 'weeks'`

(Maybe some combo boxes are not set to the right index on view creation.)

**Comment by genodeftest** [comment]
I'm seeing this issue too. It happens even on saving new smart playlists.
