### ISSUE TITLE
Transcoding command

### ISSUE THREAD

**Issue by dangmai** [exaile/exaile#214]
I'm running latest Exaile on Windows 8 (with the latest PyGI AIO), and when I use the Transcoder class and to encode to MP3, Exaile complains that the `lame` Gst plug in cannot be found. I fix it by changing the command at https://github.com/exaile/exaile/blob/master/xl/transcoder.py#L83 and https://github.com/exaile/exaile/blob/master/xl/transcoder.py#L94 to use `lamemp3enc` instead of `lame`. I haven't tested it with other OS/distribution tho, so I don't know if it's a problem everywhere else.

**Comment by genodeftest** [comment]
On Fedora/Linux there is no `lamemp3enc`, so I guess this fix would be platform specific.

**Comment by dangmai** [comment]
Based on [this bug report](http://thomas.apestaart.org/morituri/trac/ticket/45) for morituri, `lame` has been deprecated in favor or `lamemp3enc`. Do you have the ugly plugins installed? (I would not be surprised if Fedora doesn't include those by default since `lame` is definitely non-free)

**Comment by genodeftest** [comment]
Ok, seems like you are right.
