### ISSUE TITLE
Export of SmartPlaylist failed

### ISSUE THREAD

**Issue by strahlc** [exaile/exaile#216]
```
Traceback (most recent call last):
  File "/lib64/exaile/xlgui/widgets/dialogs.py", line 939, in on_response
    export_playlist(self.playlist, path, options)
  File "/lib64/exaile/xl/playlist.py", line 167, in export_playlist
    provider.export_to_file(playlist, path, options)
  File "/lib64/exaile/xl/playlist.py", line 349, in export_to_file
    for track in playlist:
TypeError: 'SmartPlaylist' object is not iterable
```

affects current master ( 8655a17 )

**Comment by strahlc** [comment]
affects current master ( 8655a17 )

**Comment by strahlc** [comment]
Steps to reproduce:
1. right click any Smart Playlist in the 'Smart Playlist' **TreeView** 
2. choose 'Export Playlist'
3. confirm dialog with 'Save'

What happens:
1. Traceback like above `TypeError: 'SmartPlaylist' object is not iterable`
2. Playlist file without any tracks is saved

Expected behavior:
The same behavior like in the workaround below.

Workaround:
1. open any Smart Playlist by double click
2. right click at the **Tab** above the playlist
2. choose 'Export Playlist'
3. confirm dialog with 'Save'
What happens:
1. Info dialog show up `Playlist saved as file:///home/strahlc/smart_playlist.m3u.`
2. Playlist file with all tracks is saved

**Comment by virtuald** [comment]
Fixed, thanks!
