### ISSUE TITLE
Traceback when trying to add cover art to mp3 files

### ISSUE THREAD

**Issue by strahlc** [exaile/exaile#217]
If I try to add a JPEG file as album art to a MP3 file (in the Properties dialog), I got the following error

Traceback (most recent call last):
  File "/lib64/exaile/xlgui/properties.py", line 1080, in on_button_clicked
    self.set_pixbuf(pixbuf, info['mime_types'][0])
TypeError: 'PixbufFormat' object has no attribute '__getitem__'

and the file chooser dialog stays open until I press ESC.

Affects current master (8655a17)

**Comment by genodeftest** [comment]
https://github.com/genodeftest/exaile/tree/fix-save-cover should fix this issue. Can you please confirm that or post a new traceback?

**Comment by strahlc** [comment]
your fix works perfect!

**Comment by genodeftest** [comment]
May I ask what system you are running? Linux distribution and Gtk+ release version would be what I'd need. Just to get an idea which systems are affected.

**Comment by strahlc** [comment]
I'm using Gentoo linux (rolling release - so, without version).

At the moment I'm using:
> INFO    : Using PyGObject 3.18.2
> INFO    : Loading Exaile 4.0.0dev+f07af87 on Python 2.7.10...
> INFO    : Loading settings...
> INFO    : Using en_US UTF-8 locale
> INFO    : Using GTK+ 3.18.7
> INFO    : Using GStreamer 1.6.3
