### ISSUE TITLE
Please add an option to store track ratings in ID3 tags.

### ISSUE THREAD

**Issue by strahlc** [exaile/exaile#218]
If I move some files to another folder, I loose all my ratings.

It would be nice to have an optional setting to store the rating in the ID3 tag (clementine has such an option).

Alternatively Exaile could store a checksum of each file and if it rescans the collection it can recognize the file on its checksum even if it has a new path. That way it can keep the rating, play count, date added, ...

**Comment by strahlc** [comment]
Most audio player use the POPULARIMETER flag (POPM) to store the rating.

Here are some descriptions of implementation examples:
https://en.wikipedia.org/wiki/ID3#ID3v2_rating_tag_issue
http://help.mp3tag.de/main_tags.html#POPM

**Comment by virtuald** [comment]
I agree that this would be nice to have.

**Comment by sbrubes** [comment]
As a plugin it's an easy task.

Do not affects users that do not expect it, and could accept a customized 'Email to user' (see 4.17.   Popularimeter at http://id3.org/id3v2.4.0-frames).

Maybe it could also handle to store 4.16.   Play counter, if doesn't have it yet, or even adding it as another plugin.

**Comment by phalgunlolur** [comment]
Hi. I would really like this as well

**Comment by gitut2007** [comment]
I'd prefer the FMPS_RATING standard as used eg by Amarok which i tough you were originally based in...

**Comment by luzip665** [comment]
Is there some new development?

I would prefer to use POPM for mp3 (or rather id3) and rate for mp4 and RATING for flac/vorbis.

My source is at least only https://docs.kde.org/trunk5/en/kid3/kid3/commands.html#frame-list
Does someone know if there is a better source available?

**Comment by Pkanjai** [comment]
> If I move some files to another folder, I loose all my ratings.
> 
> It would be nice to have an optional setting to store the rating in the ID3 tag (clementine has such an option).
> 
> Alternatively Exaile could store a checksum of each file and if it rescans the collection it can recognize the file on its checksum even if it has a new path. That way it can keep the rating, play count, date added, ...
