### ISSUE TITLE
Namespace Gst not available

### ISSUE THREAD

**Issue by XzuRukneg** [exaile/exaile#220]
Can't start on xubuntu 12.04 (maybe after update), version from PPA.
`~$ exaile
Traceback (most recent call last):
  File "/usr/local/lib/exaile/exaile.py", line 68, in <module>
    main()
  File "/usr/local/lib/exaile/exaile.py", line 65, in main
    exaile = main.Exaile()
  File "/usr/local/lib/exaile/xl/main.py", line 254, in __init__
    _do_heavy_imports()
  File "/usr/local/lib/exaile/xl/main.py", line 51, in _do_heavy_imports
    gi.require_version('Gst', '1.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 48, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available`

`~$ exaile --version
Exaile 4.0.0dev`

Git version also suddenly don't work, but don't got the output (sorry).

**Comment by virtuald** [comment]
You don't have the correct dependencies installed: http://exaile.readthedocs.org/en/latest/user/deps.html

Apparently whoever setup the PPA you're using hasn't adjusted the deps correctly. Exaile 4 requires Gtk 3.10+, PyGObject 3.12+, and GStreamer 1.4+.

**Comment by XzuRukneg** [comment]
Le 18/01/2016 19:11, Dustin Spicuzza a écrit :
>
> You don't have the correct dependencies installed:
> http://exaile.readthedocs.org/en/latest/user/deps.html
>
> Apparently whoever setup the PPA you're using hasn't adjusted the deps
> correctly. Exaile 4 requires Gtk 3.10+, PyGObject 3.12+, and GStreamer
> 1.4+.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exaile/exaile/issues/220#issuecomment-172609870>.
>
Can you please tell wath version should work? (and the git comand)

-- 
Damien.DX

**Comment by genodeftest** [comment]
Currently, exaile 3.4.x should work fine.

To make the git version work (and the broken version you got somewhere, too), install:
GStreamer version 1.4 or higher
Gtk+ version 3.10 or higher
PyGObject 3.12 or higher.

There is no git command to do so. Look up your package manager (Software-Center, Synaptic, aptitude or apt-get) and install these packages. You should be able to get the package source from there. Please report this issue to whoever made this package.

**Comment by XzuRukneg** [comment]
I think I have to do something to clear my git installation and do after
a correct package install (by PPA or standart repo).
But I don't know how to do this clean up...




-- 
Damien.DX

**Comment by genodeftest** [comment]
Ok, you probably want to run `make clean` from your git folder as root or with sudo. This should be enough to clean up.

**Comment by XzuRukneg** [comment]
Le 18/01/2016 22:36, Christian Stadelmann a écrit :
> |make clean|
Thanks.

But exaile still don't start, with same message.(See log files.)
This is the version from standard ubuntu12.04 repo.
Is this version broken??





-- 
Damien.DX


~$ exaile
Traceback (most recent call last):
  File "/usr/local/lib/exaile/exaile.py", line 68, in <module>
    main()
  File "/usr/local/lib/exaile/exaile.py", line 65, in main
    exaile = main.Exaile()
  File "/usr/local/lib/exaile/xl/main.py", line 254, in __init__
    _do_heavy_imports()
  File "/usr/local/lib/exaile/xl/main.py", line 51, in _do_heavy_imports
    gi.require_version('Gst', '1.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 48, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available


exaile$ sudo make clean
find . -name "*.~[0-9]~" -exec rm -f {} \;
find . -name "*.py[co]" -exec rm -f {} \;
find po/* -depth -type d -exec rm -r {} \;
rm -f exaile.1.gz
make -C plugins clean
make[1]: entrant dans le répertoire « /home/kxzu/Exaile/exaile/plugins »
find . -name "*.py[co]" -exec rm -f {} \;
make[1]: quittant le répertoire « /home/kxzu/Exaile/exaile/plugins »
kxzu@KXstudio:~/Exaile/exaile$ sudo make clean
find . -name "*.~[0-9]~" -exec rm -f {} \;
find . -name "*.py[co]" -exec rm -f {} \;
find po/* -depth -type d -exec rm -r {} \;
rm -f exaile.1.gz
make -C plugins clean
make[1]: entrant dans le répertoire « /home/kxzu/Exaile/exaile/plugins »
find . -name "*.py[co]" -exec rm -f {} \;
make[1]: quittant le répertoire « /home/kxzu/Exaile/exaile/plugins »

**Comment by virtuald** [comment]
What version of GStreamer do you have installed?

**Comment by XzuRukneg** [comment]
Le 19/01/2016 00:44, Dustin Spicuzza a écrit :
>
> What version of GStreamer do you have installed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exaile/exaile/issues/220#issuecomment-172683574>.
>
GStreamer 0.10.13-1

-- 
Damien.DX

**Comment by virtuald** [comment]
Exaile 4 (master) requires GStreamer 1.4.x.

**Comment by XzuRukneg** [comment]
In fact, I can't success in clean up my git version!

|I have make clean| from my git folder as root.

And try to install packaged version.
"Commit Log for Mon Jan 18 23:24:04 2016


Reinstalled the following packages:
exaile (0.3.2.2-2)"

But:
 :~$ exaile --version
Exaile 4.0.0dev

I don't understand!
What I'm missing?

-- 
Damien.DX

**Comment by XzuRukneg** [comment]
Le 19/01/2016 02:58, Dustin Spicuzza a écrit :
>
> Exaile 4 (master) requires GStreamer 1.4.x.
>
>
Ok. But how a working application can suddenly don't work?
I use exaile every days (really).
I've checked my synaptic history, there is nothing about gstreamer.
I was running "a" git version (for year), don't really knows witch one.

Any idea anybody about what should happen? :/


-- 
Damien.DX

**Comment by genodeftest** [comment]
@XzuRukneg:
You currently have two versions of exaile installed:
0.3.2.2 from ubuntu repositories which requires GStreamer 0.10.x
4.0.0dev from git repository which requires GStreamer 1.4.x or higher

Sorry, my comment was wrong. It shouldn't be `make clean` but `make uninstall`. `make clean` deletes all compiled files from source folder, `make uninstall` uninstalls your software. This is why you are getting 4.0.0dev when running `exaile --version`. I've corrected my comment above yesterday, but it looks like there is no email sent to you if I do that.

After running `make uninstall`, `exaile --version` should return 0.3.2.something. Can you confirm that?

**Comment by XzuRukneg** [comment]
Le 19/01/2016 12:51, Christian Stadelmann a écrit :
> |make uninstall| uninstalls your software.
That was the missing thing!
Thank you!

I've cleaned git version.
I've apt-get autoremove --purge exaile
And install it from PPA:
~$ exaile --version
Exaile 3.3.2

Then:
~$ exaile
INFO    : Loading Exaile 3.3.2 on Python 2.7.3...

:D
Ok, thank you one more time!


Now the last and how mysterious question is " how my running version
become 'not working' ".

 Best,

-- 
Damien.DX

**Comment by genodeftest** [comment]
Ok, that's good.

As far as I know, any software installed in /usr/local/ (e.g. by running `make install` for exaile) has a higher priority than software installed in /usr. Usually there is an enviroment variable controlling this preference. You can get its value by running `env | grep PATH`. You should see one line starting with `PATH=/usr/local/bin:/usr/…`. Whatever is listed first has highest priority.
In your case it probably looked like this:
/usr/bin/exaile provided by your distro package
/usr/local/bin/exaile provided by your manual installation
since /usr/local/bin is first in PATH, it has higher priority, so if you start exaile it will run /usr/local/bin/exaile, not /usr/bin/exaile. The same should be true with .desktop files used by desktop shells to start applications.

Did that answer your question?

**Comment by XzuRukneg** [comment]
Interesting, thank you again for your answer.

> Did that answer your question?
>
In fact no.
I used exaile every days, don't remember exactly witch version (but got
sources on my hard disk, for sure).
I'm a "linuxmusician" and use jack
Yesterday, I've started by error exaile without jack running, so without
audio server on my system.
That happen sometimes, and just close, start jackd and restart exaile do
the trick.
But this time, suddenly, it don't restart (it start few seconds before!!)
I always run it into terminal, and it says something about "mutagen".
Unfortunately, I don't get this log, and start to do "bad things" (git
pull) because I don't knew how to "make unistall".

The most reverent thing I've did before this issue for me, was to do
"apt-get clean up" (autoremove --purge).
It very incredible to see a current running application suddenly refuse
to work!
That probably make me quite "panic", and I think that's why I don't get
the log.
And finally, I open the bug report, desperately confused.

I'm interesting about understand what should happen.

-- 
Damien.DX

**Comment by genodeftest** [comment]
Hm, is your exaile working again now?

**Comment by XzuRukneg** [comment]
Le 19/01/2016 17:10, Christian Stadelmann a écrit :
>
> Hm, is your exaile working again now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exaile/exaile/issues/220#issuecomment-172901478>.
>
That is ok, yes it works with PPA for ubuntu12.04.
That what I mean here:
~$ exaile
INFO    : Loading Exaile 3.3.2 on Python 2.7.3...


But I like to understand "why" when something get wrong.

-- 
Damien.DX

**Comment by genodeftest** [comment]
Yes, see my comment [above](https://github.com/exaile/exaile/issues/220#issuecomment-172848841) for an explanation. Looks like you were running `make install` from exaile's source folder some days ago.
