### ISSUE TITLE
[security] Update strategy for bundled WebKitGTK+

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#223]
Exaile on Windows is bundling WebKitGTK+ (am I right?). It doesn't get security updates. This is putting users at risk. See [Michael Catanzaro: On WebKit Security Updates](https://blogs.gnome.org/mcatanzaro/2016/02/01/on-webkit-security-updates/) for details.

In short: There must be an update to exaile every time WebKitGtk+ gets an update. And Exaile 4.0 should be released soon since (the currently shipped) WebKitGtk+ for gtk 2.x is unsupported for >1 year with literally hundreds of known security issues.

**Comment by virtuald** [comment]
We are not bundling WebGTK+.

**Comment by genodeftest** [comment]
Hmm, sorry for the noise.

**Comment by virtuald** [comment]
Funny thing is, for Exaile 4.0 we would potentially bundle Webkit. But not in older versions.
