### ISSUE TITLE
"Use fade transitions on user actions" breaks volume

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#234]
Steps to reproduce:
1. in Preferences → Playback enable "Use fade transitions on user actions"
2. open a playlist with multiple tracks
3. start playing
4. press "next" or "previous" buttons often, faster than twice the time specified as "Fade duration"

What happens:
After some time volume is down to 0 (mute).

What should happen:
No change in volume

Additional note:
This issue can also be reproduced when playing music files which are shorter than twice the "Fade duration".

Affected version:
Exaile 4.0.0dev+25a2372 on Python 2.7.10

**Comment by virtuald** [comment]
I played with it a bit, but I'm not able to duplicate this with the latest in master. If you're still able to duplicate this, let me know.
