### ISSUE TITLE
Exportet playlist conatins wrong path when the playlist name contains withespaces

### ISSUE THREAD

**Issue by strahlc** [exaile/exaile#253]
When exporting a playlist with one or more whitespaces in the name, the playlist entries pointing to an invalid location.

Steps to reproduce:
1. create a playlist "my cool playlist"
2. add one or more titles
3. export the playlist to m3u
4. check the file contend -> result: The path of each entry in the exported playlist points to an invalid location
5. rename the playlist to "my_cool_plalist" and export it again
6. check the file contend -> result: The path of each entry in the exported playlist is correct

Example:
With white spaces in playlist name:
```
$ cat "my cool playlist.m3u" 
#EXTM3U
#PLAYLIST: my cool playlist
#EXTINF:2,Track 6 - Artist
../test_data/artist/album/06. Artist - Track 6.mp3
#EXTINF:2,Track 7 - Artist
../test_data/artist/album/07. Artist - Track 7.mp3
```
After rename and export:
```
$ cat "my_cool_playlist.m3u" 
#EXTM3U
#PLAYLIST: my_cool_playlist
#EXTINF:2,Track 6 - Artist
test_data/artist/album/06. Artist - Track 6.mp3
#EXTINF:2,Track 7 - Artist
test_data/artist/album/07. Artist - Track 7.mp3
```

**Comment by tfree87** [comment]
It seems that there was an error in getting the basename of the exported playlist file. The `playlist_file.get_basename()` was seems to only get part of the filename if there is a space in the file name. Using `os.path.basename(playlist_path)` seems to fix this issue.

**Comment by tfree87** [comment]
Not sure why `Gio.File.get_basename()` would be broken in this way. This will require more investigation...

**Comment by tfree87** [comment]
I figured it out, `Gio.File.get_basename()` no longer returns strings with spaces replaced by `%20`. This means that when removing the basename from the end of the uri using `len()` will leave 3 characters on the end. Adding `.replace(' ', '%20') to the end of `Gio.File.get_basename` fixes this issue. Not sure if there is a more elegant way to do this. 

I have squashed this change with my previous commit. Please excuse all the updates as I was having difficulties with `git rebase` again.
