### ISSUE TITLE
Cover window: Esc key doesn't work if the Close toolbar button is hidden

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#260]
1. Play a song, double-click on cover image so the Cover window appears.
2. Reduce the window width until the toolbar overflows and the Close button is hidden under an arrow button.
3. Press Escape.

Expected behaviour: Window is closed.

Actual behaviour: Nothing happens.

Note: If you increase the window width so the Close button appears, Esc works. Bizarre.

Targetting 4.0 because Adwaita makes this more likely to happen (due to just how stupidly big everything is)&mdash;in my case the Close button is already hidden without having to resize the window at all.

**Comment by tfree87** [comment]
If we directly connect the `CoverWindow.cover_window` key-press-event to a function `on_key_press` that executes the `hide()` function if the escape key is pressed, then the window will reproducibly close the window even when the close button is hidden.

**Comment by tfree87** [comment]
I noticed that all the handlers appear to be in the ui file so I have changed that in this last commit.

**Comment by sjohannes** [comment]
Thanks, I've committed your changes.
