### ISSUE TITLE
Non-Latin search always matches every track

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#270]
1. Edit a track, add `中` to the title.
1. Search for `中` in the Collections panel.

Expected: Only tracks containing the character match.

Actual: Every track matches.

This is a regression from e5ea6ba (#176 / #261).  The issue is that `unicodedata.normalize('NFKD', u'中').encode('ascii')` returns `?` instead of the original character. (For the record, `GLib.utf8_normalize(u'中', 1, GLib.NormalizeMode.NFKD)` also has the same issue.)

Note that unicode searching in the tracklist (right pane) is currently broken for a different reason, so this can only be tested in panels and maybe smart playlists.

**Comment by tfree87** [comment]
A good solution for this might be to go through each character in the `search_string` and normalize each one. If the character can't be normalized to an ascii character (i.e. `unicodedata.normalize('NFKD', search_string).encode('ASCII','ignore')` returns `None`), then the original character can be returned.

**Comment by virtuald** [comment]
This was fixed in #270, now it appears that zero tracks are matched when searching for that character. I'm adding a unit test to make sure that happens -- and if that's not what's supposed to happen, then we can fix it.

**Comment by virtuald** [comment]
I stand corrected, it does the search correctly.
