### ISSUE TITLE
smartplaylists don't have 'bitrate' as filter criteria

### ISSUE THREAD

**Issue by strahlc** [exaile/exaile#274]
It would be nice to have 'bitrate' as criteria for smartplaylists.

Over the years I've ripped all my Audio-CDs to MP3 and put them in the basement.
Unfortunately I've used only 160 kbps in the beginning.
Over the time I raised the quality up to 256 kbps.

Now I would like to create a smartplaylist containing all low quality tracks, to decide which one I have to encode again.

**Comment by virtuald** [comment]
Fixed.
