### ISSUE TITLE
Exaile 3.4.5 does not recognize / display Opus metadata

### ISSUE THREAD

**Issue by flberger** [exaile/exaile#278]
[Opus](https://www.opus-codec.org/) is a next generation audio codec aimed at superseding MP3, Vorbis etc. It is stable and widely supported. GStreamer added Opus support [in 2012](https://gstreamer.freedesktop.org/news/#2012-02-21T14:00:00Z).

However Exaile 3.4.5 apparently does not display the metadata tags of Opus files. See the screenshot for an identically tagged FLAC and Opus file.

![opus-metadata](https://cloud.githubusercontent.com/assets/8035998/17080103/17ca5426-5124-11e6-85a3-8028eae38507.png)

Expected behaviour: Exaile should recognize the Opus metadata tags (which are the same as in Vorbis).

I'll gladly help out with any further information required, or examples.

**Comment by sjohannes** [comment]
This will be fixed in 4.0; see #150. I believe the patch there should work with 3.x, if you want to fix it locally.

**Comment by flberger** [comment]
Thanks!
