### ISSUE TITLE
Makefile missing separator

### ISSUE THREAD

**Issue by alanbbr** [exaile/exaile#281]
Just pulled master onto a CentOS 7.2 Gnome 3.14 system. make fails:

20:12:40 alan@asus:~/Source/External/exaile [master|=] 
$ make
Makefile:1: *** missing separator.  Stop.

**Comment by sjohannes** [comment]
Works fine here. It could be an issue with older versions of GNU Make but I doubt it.

Check that you haven't accidentally broken the makefile. That error seems to be usually caused by text editors replacing tab characters with spaces.

**Comment by alanbbr** [comment]
git clone, cd, make: no editor involved. Rnning GNU Make 3.82 as
included by Redhat. If Exaile required gmake 4, would you note that in
the INSTALL.

**Comment by sjohannes** [comment]
I tested this on a CentOS container and could reproduce the issue. It looks like GNU Make 3.x doesn't have the `!=` operator, which ironically I used for BSD Make compatibility. The linked changeset replaces it with the GNU-only `$(shell ...)` function.

Thanks for the bug report!
