### ISSUE TITLE
Sorting by Playcount: 0 gets sorted as the largest value

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#287]
For example, sorting tracks (in the tracklist, by clicking the Playcount column header) with playcounts of [0, 1, 2, 3] results in [1, 2, 3, 0]. Clicking the column header again results in [0, 3, 2, 1].

Probably has to do with how we sort numeric vs nonexistent values.

Need to check if this affects other numeric columns.

**Comment by sbrubes** [comment]
Yes, it's related to the way values are checked:
> if not value:
https://github.com/exaile/exaile/blob/master/xl/trax/track.py#L593

**Comment by genodeftest** [comment]
@sbrubes : Thank you!
