### ISSUE TITLE
Files panel: Files inside directories are added to tracklist in arbitrary order

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#290]
1. On the Files panel, right click on a directory containing music files.
2. Select _Append to Current_ or _Replace Current_.

Expected: Files are added in some reasonable order.

Actual: Files are added in arbitrary filesystem order (not even alphabetical).

**Comment by virtuald** [comment]
:(

**Comment by virtuald** [comment]
Nope, when added to the playlist, it's actually resorted using its own sort order. The default sort order seems to be `['albumartist', 'date', 'album', 'discnumber', 'tracknumber', 'title']`.

See https://github.com/exaile/exaile/blob/master/xlgui/widgets/playlist.py#L1197

**Comment by sjohannes** [comment]
That's when you drag the files into the playlist. This bug only occurs when you right click &rarr; *Append to Current* or *Replace Current*.

It doesn't happen all the time; it likely depends on how the files are stored in the filesystem and listed by the OS. I can consistently reproduce this problem by doing this:

1. Let's say I have a directory containing 10 tracks.
2. Create a new `~/test` directory.
3. Copy tracks 2, 4, 6 to the new directory.
4. Copy the rest of the tracks.
5. In Exaile, browse to `~`, right click on `test`, and select Append to Current.

The files will be ordered like this: 2 4 6 1 3 5 7 8 9 10.
