### ISSUE TITLE
gnomemmkeys: Wrong D-Bus object used if running GNOME with MATE installed

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#293]
When MATE is installed (but not running), the following code causes the MATE Settings Daemon to start due to D-Bus service activation.

```
obj = bus.get_object('org.mate.SettingsDaemon', '/org/mate/SettingsDaemon/MediaKeys')
```

This is bad by itself (we don't want the mate-settings-daemon process to start at all), but it also causes the gnomemmkeys plugin to not work with GNOME because the above call returns successfully (usually, when MATE is not installed, it would raise an exception which we catch).

When we use `obj` later, we get

```
Traceback (most recent call last):
  File "/exaile/xl/plugins.py", line 148, in enable_plugin
    plugin.enable(self.exaile)
  File "/exaile/plugins/gnomemmkeys/__init__.py", line 52, in enable
    _enable(None, player.PLAYER, None)
  File "/exaile/plugins/gnomemmkeys/__init__.py", line 90, in _enable
    GNOME_MMKEYS.GrabMediaPlayerKeys("Exaile", 0)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "GrabMediaPlayerKeys" with signature "si" on interface "org.mate.SettingsDaemon.MediaKeys" doesn't exist
```

because the service is incomplete and doesn't have the `/org/mate/SettingsDaemon/MediaKeys` object.

**Comment by genodeftest** [comment]
gnome-shell has support for MPRIS2 since 3.20 (through [this commit](https://git.gnome.org/browse/gnome-shell/commit/?id=3ecdfaffd278dbd1115dea0eb86069b3cf0ae680)), so there is no need to use gnomemmkeys on GNOME any more.
It looks like the same is true for MATE: https://github.com/mate-desktop/mate-settings-daemon/search?utf8=%E2%9C%93&q=mpris
So if somebody can confirm the MPRIS2 plugin works fine on MATE, how about removing this plugin?

**Comment by sjohannes** [comment]
Ah you're right, thanks. Confirmed that it also works on MATE.
