### ISSUE TITLE
bpmdetect: Autodetection on a video file causes the video to be played

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#295]
1. Add a video file to a tracklist.
1. Right click, Autodetect BPM.

A video window then appears and the video starts playing (in 1&times; speed). Closing the window shows an "Output window was closed" message box and cancels the autodetection.

**Comment by virtuald** [comment]
lol.

**Comment by sjohannes** [comment]
(For the record, that was my own commit. Git attributed it to the wrong author for some reason.)

Autodetection on a video file still seems a bit slow (a few seconds), but I'm not sure if it's avoidable.
