### ISSUE TITLE
Cover images are associated only with Album tag and not Artist+Album

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#306]
1. Have 2 files tagged with the same Album name but different Artist names.
2. Attach a cover image to the first file (through e.g. right click on cover &rarr; Fetch Cover).
3. Play the second file.

Expected: Exaile shows a different cover image, or no cover.

Actual: Exaile shows the first file's cover image.

I'm pretty sure this used to work correctly; I wonder what broke it.

**Comment by sjohannes** [comment]
While we're at it, maybe also look at using albumartist if available.

**Comment by sbrubes** [comment]
I've found this patch from July, 05.

Could you see if it's what you are looking for?

[306.txt](https://github.com/exaile/exaile/files/1295871/306.txt)

**Comment by sbrubes** [comment]
Just **disregard what I've sent**.

I'll check it together with this one: https://github.com/exaile/exaile/issues/215

**Comment by sbrubes** [comment]
[A fixed version.](https://github.com/exaile/exaile/files/1297172/306-fixed.txt)

**Comment by sbrubes** [comment]
[Possible solution to #306.](https://github.com/sbrubes/exaile/commit/986370ccc25fce8b8ad043722b43c66bb41c94c9)

This time uses album as a switch off[*] and the keys 'albumartist', '__compilation' or 'date'.

 [*] This way an album with no album information will not have a key, and I'm assuming that.

**Comment by sbrubes** [comment]
Changing this index will request "migration". #188

**Comment by virtuald** [comment]
@sbrubes can you make a PR with whatever happens to be the right solution to this? Thanks!

Thinking about it, we should add a test for this too.

**Comment by sbrubes** [comment]
@virtuald yes, I can

@sjohannes fine to you? https://github.com/exaile/exaile/issues/306#issuecomment-329291172

**Comment by sjohannes** [comment]
Ok, I dug into our current code to see what it's doing, and it's quite surprising. Our covers.db key used to be the tuple `(artist, album)` in the simplest case. Then during the 0.3 rewrite back in 2009 it was changed to `('album', album)`, but that's bad because it removes the artist information — I completely missed this change throughout these years.

I like the patch but I want to change things around a bit. I'll post a PR later today and see what everyone thinks.
