### ISSUE TITLE
Stream to dlna renderer?

### ISSUE THREAD

**Issue by cars10** [exaile/exaile#307]
Is there any way to achieve this?

I DON'T want to browse a dlna server, i want to stream music to a dlna renderer.

**Comment by virtuald** [comment]
You could write a plugin to do it. I don't know anything about DLNA, so not sure how hard it is. Sounds like a fun project for you. :)

**Comment by virtuald** [comment]
If there's serious interest in doing this, we can reopen. However, it doesn't appear to be the case, so closing as wont fix.
