### ISSUE TITLE
Exaile doesnt read Opus Tags (?)

### ISSUE THREAD

**Issue by psyca** [exaile/exaile#312]
I dont know if its an problem of Exaile or gstreamer or something other related - close this report if its false.

If i encode my music to Opus and play it with Exaile (3.4.4), Exaile doesnt show/read the Tag informations in the file. Testing with VLC it works.

**Comment by sjohannes** [comment]
Yeah, it's fixed in the development version (the patch is in #150 if you want to fix it locally).

**Comment by psyca** [comment]
Ok. Thanks.
