### ISSUE TITLE
NotebookTab theming and orientation issues

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#319]
From [the wiki page](https://github.com/exaile/exaile/wiki/PyGI-migration-tasklist-(GTK3-GStreamer-1.x)):

> If _Prefs > Appearance > Tab placement_ is Left or Right, it looks terrible.
> We force 6px padding to deal with Adwaita's massive padding, but 6px is actually larger than normal on some other themes. Hmm....

There are two issues here:
# Theming
We should not apply Adwaita theme fixes to non-Adwaita themes. Also, the Adwaita theme fixes are only working for `Gtk.PositionType.LEFT` tabs, but not for `RIGHT`.

Solutions:
1. It is possible to apply our theming fixes only if the theme is Adwaita and let all the other themes handle it however they like. A fix for this is in my branch.
2. I also wrote a fix for `Gtk.PositionType.RIGHT`. Compatible with the other solution.

~# Widget orientation~
~When setting `Gtk.PositionType.LEFT` or `RIGHT`, the tab widgets (label, etc.) are still oriented horizontally.~

~Some options here:~
1. ~disable changing tab placement. Remove a feature to simplify code. Panel tabs still need to have custom theming, but my fix won't be necessary.~
2. ~In my branch, the tab widget is also rotated, including the label. This solution is not perfect now, because~
    * ~images are not rotated, which looks weird. But I'm not sure it will get better when being rotated. do we want them to rotate?~
    * ~renaming the tab gets __very__ ugly now, because you can't easily rotate a `Gtk.Entry` and you probably shouldn't anyway. How about replacing it by a `Gtk.Popover`? Note that this will increase the version requirement on Gtk+ to 3.12. I think we can do that, because [Debian stable (8.0 Jessie) is at 3.14](https://distrowatch.com/dwres.php?firstlist=ubuntu&secondlist=debian&firstversions=6&secondversions=2&resource=compare-packages&view=major&refresh=Refresh) and CentOS too, but we'll lose Ubuntu 14.04 LTS compatibility. You'll need to decide whether you want that.~

As one can see below, @sjohannes didn't really want to rotate the tabs other 

My branch: https://github.com/genodeftest/exaile/tree/notebooktab

**Comment by sjohannes** [comment]
Regarding the orientation, there should be a difference between the panel-style layout (what the current code calls "vertical") where the items are laid out vertically, and the tracklist-style layout where they are laid out horizontally (even when the tab bar is on the left).

In ASCII art form:

```
+-+-------+      +-------+-----------+      +---------------+---------------+
|X|       |      |Tab1  X|           |      |     Tab1     X|     Tab2     X|
| |       |      +-------+           |      +---------------+---------------+
| |       |      |Tab2  X|           |      |                               |
+-+       |      +-------+           |      |                               |
|X|       |      |       |           |      |                               |
| |       |      |       |           |      |                               |
| |       |      |       |           |      |                               |
+-+-------+      +-------+-----------+      +-------------------------------+
   Panel,              Tracklist,                      Tracklist,
   left                  left                             top
```

**Comment by genodeftest** [comment]
Oh, so you're opposed to rotating the tabs if they are left on tracklist, but prefer the status quo instead?
What do you want to have fixed instead? I doubt I can make the tabs appear on the top only, as your second "image" shows. Looks like you want the tabs to not expand vertically.

Should I submit only the patch to apply the changes to Adwaita theme only?

**Comment by sjohannes** [comment]
> Oh, so you're opposed to rotating the tabs if they are left on tracklist, but prefer the status quo instead?

Yeah. The motivation for allowing the tracklist tabs on the left/right is to sacrifice some horizontal space to show more tabs (or more characters per tab). If you're familiar with the [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) Firefox addon, the idea is similar.

> What do you want to have fixed instead?

The biggest problem right now is that the tab labels are getting cut off too early. When I switch the tabs to the left, I can only see "Pl..." on every tab.

> I doubt I can make the tabs appear on the top only, as your second "image" shows. Looks like you want the tabs to not expand vertically.

Yeah, having them not expand would look better in the vertical (left/right tab bar) case. It should be possible; in fact I think they don't expand by default. I made them expand to match other GTK+ 3 apps, but it doesn't really matter if they don't, even in the horizontal (top/bottom tab bar) case. That is, if they can be made to work like the tabs on Exaile 3.x, that's fine too.

> Should I submit only the patch to apply the changes to Adwaita theme only?

I like that part of the patch (although I don't know how well other themes deal with our vertical tabs). But if you want to work on the left/right tracklist tab bar problem that would be great as well.

**Comment by genodeftest** [comment]
> The biggest problem right now is that the tab labels are getting cut off too early. When I switch the tabs to the left, I can only see "Pl..." on every tab.

This can easily be changed by `gtk_label_set_width_chars()` to something bigger than 4 ;)

> I like that part of the patch (although I don't know how well other themes deal with our vertical tabs). But if you want to work on the left/right tracklist tab bar problem that would be great as well.

Ok, will do that in a few days, probably in 2017.

**Comment by genodeftest** [comment]
> This can easily be changed by `gtk_label_set_width_chars()` to something bigger than 4 ;)

Sadly, this does also increase the minimum width.

`Gtk.Notebook` has child properties `tab-fill` and `tab-expand`, but they are both ignored. Needs a reproducer with a minimal testcase and probably should be reported as bug to Gtk+.

**Comment by virtuald** [comment]
It would be nice to get this in. The left tab thing is particularly annoying for me -- I would be happy I think with a min-width/set_width_chars for now, just because the default setting is so unusable.

I noticed tab-fill and tab-expand don't show up in the list of properties in Gtk inspector? Though, definitely in the docs. Very strange.

One thing about the adwaita theme detection is that a user can technically change the theme at runtime... I think there's a theme-changed signal somewhere you can listen to for that? Maybe we need a `csstheme.py` where we can stick any css-related machinery?

**Comment by virtuald** [comment]
Also, I definitely agree with @sjohannes ASCII art, those layouts are the Exaile I'm used to. :)

**Comment by virtuald** [comment]
I have some ideas for a theme plugin, I'll put them together now and we can discuss it there.

**Comment by sjohannes** [comment]
> I noticed tab-fill and tab-expand don't show up in the list of properties in Gtk inspector? Though, definitely in the docs. Very strange.

You have to select a PlaylistPage instance and choose Child Properties on the top left combo box.

**Comment by virtuald** [comment]
.. and got distracted. Maybe tomorrow.

**Comment by genodeftest** [comment]
This looks fixed. Any reason to keep it open? anything missing? Feel free to reopen.

The current Exaile code behaves pretty much like the ASCII art by @sjohannes in https://github.com/exaile/exaile/issues/319#issuecomment-268472797
