### ISSUE TITLE
Playlist columns always added on the right end of treeview where users can't see them

### ISSUE THREAD

**Issue by grubersjoe** [exaile/exaile#322]
**Exaile 4.0.0dev**
Arch Linux (AUR package exaile-git)

When right-clicking on a column header in the playlist to choose shown track attributes the view does not update. If you switch afterwards from "Resizable" to "Autoresize" or vice-versa the view updates correctly and shows the newly chosen attribute as well. Sometimes it works instantly, but most of the time not.

**Steps to reproduce**
1. Right click on a column header in the playlist and choose an arbitrary unselected track attribute
2. The view does not update

**Expected result**
The view should update immediately and show all selected track attributes.

**Comment by genodeftest** [comment]
The issue is a bit different, actually: Playlist columns are added, and the view is updated. The issue here is that the column is added on the right, outside of the visible area, so you can't see it. Changing the column resize mode changes column widths, so it gets visible.
