### ISSUE TITLE
Volume can only be set in minimum increments of 5%

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#327]
I'm on GTK 3.22 on Fedora 25, and it appears that via the mouse I can set the volume in increments of 10%, or 5% if I use the scroll wheel. This appears to be because the Gtk.Adjustment settings in the UI file.

Can someone confirm this is/isn't the case on other platforms/configurations? Probably should change the minimum step to be 1%. I could be convinced to leave the max step at 10%... though I feel like 5% is more appropriate.

**Comment by genodeftest** [comment]
I'm against a 1% step. Turning your scroll wheel by 100 steps is too much. 5% steps are ok for me.

**Comment by sjohannes** [comment]
I'm using GTK+ 3.22.12 on Arch (`testing` repo).

* Dragging or clicking the volume bar always snaps it to multiples of 10%. I'm could've sworn this wasn't the case in the past.
* Scrolling with a normal mouse wheel always increases/decreases by 5% but doesn't snap (e.g. 3% &rarr; scroll up &rarr; 8%).
* Smooth scroll (using trackpad) can set it to any int 0..100.

**Comment by lazka** [comment]
Seeing the same in quodlibet, maybe a gtk bug? Seems like it has something to do with the "digits" and "round-digits" property, increasing "digits" helps.

**Comment by dangmai** [comment]
I can confirm that this is also the behavior in Windows 7 with Gtk 3.22.10 (MSYS2)

**Comment by lazka** [comment]
Filed upstream (in case we see the same problem here..): https://bugzilla.gnome.org/show_bug.cgi?id=781605

**Comment by virtuald** [comment]
Setting round_digits to 2 fixed this issue. However, I wonder what the behavior for that will be on previous versions of GTK. Time to go fire up my docker container...

**Comment by virtuald** [comment]
Works on 3.18, going to call that an appropriate fix.
