### ISSUE TITLE
With gapless playback enabled, exaile plays 2 songs at once

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#332]
When I enable "gapless playback", playing songs from a playlist results in two songs played at once.

In case you need more information: Is there any way to debug this?

Current version: https://github.com/exaile/exaile/commit/01b369fcb1ea8e99a8baf4682c4e48e157ed5d4c

**Comment by virtuald** [comment]
Can you post a log of the transition period with `--debug` enabled?

**Comment by genodeftest** [comment]
Logs as requested:
```
00:45:22,219:INFO    : Unihibited Suspend (inhibitsuspend)
00:45:22,441:DEBUG   : Saving settings... (xl.settings)
00:45:43,550:DEBUG   : player-audiostream-1-filters: Removing all elements (xl.player.gst.gst_utils)
00:45:43,550:DEBUG   : Not applying audio filters (xl.player.gst.engine [player-a1])
00:45:43,550:INFO    : Playing file:///home/username/Music/Inception%20OST/Inception_2010_Physics_Soundtrack_OST.m4a (xl.player.gst.engine [player-a1])
00:45:43,555:INFO    : Inhibited Suspend (inhibitsuspend)
00:45:51,228:DEBUG   : Saving settings... (xl.settings)
00:49:22,929:DEBUG   : Delaying start for 100ms (xl.player.player)
00:49:22,943:DEBUG   : player-audiostream-1-filters: Removing all elements (xl.player.gst.gst_utils)
00:49:22,944:DEBUG   : Not applying audio filters (xl.player.gst.engine [player-a1])
00:49:22,944:INFO    : Playing file:///home/username/Music/Ender's%20Game%20OST/16_Graduation_Day_Ender_s_Game_Soundtrack.m4a (xl.player.gst.engine [player-a1])
00:49:23, 38:DEBUG   : Resuming playback after delayed start (xl.player.player)
```

It is also possible that one song is played at two positions at the same time, I am not sure about that. The only thing I am sure about is that disabling "gapless playback" puts playback back to normal.

**Comment by virtuald** [comment]
Hm, that's very strange, I would have expected a message about gapless playback. However -- it looks like you have delayed start on AND gapless playback. I bet that combination is where the issue is occurring...

Probably the best way to debug this is to stick a bunch of print statements in `engine_autoadvance_get_next_track` and `on_about_to_finish` and figure out where things are going wrong.

**Comment by virtuald** [comment]
I tried for a bit, but I wasn't able to duplicate this issue. I tried a variety of different settings, using flac files. Maybe it's a setting affecting it? Does it happen for all file types?

**Comment by genodeftest** [comment]
I guess I was wrong on this, sorry for the noise. I probably just had a different audio file than I expected. In a different player, the files in question sound the same.
