### ISSUE TITLE
Change track_tags_changed to be per-track, instead of per-tag

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#334]
One complaint I've often heard is that scanning collections takes a really long time. There are a lot of reasons for this, but I think one change that could make a huge difference is changing `track_tags_changed` to be only emitted once per change to a track, instead of 8 different events per track. Lots of stuff happens as a result of events, so fewer of them occurring would be a positive thing.

There's only maybe a dozen or so places where the track tags event is used, and most of them don't actually care that the specific tag changed, only that the track itself changed.

I think if this change were to be made, then it should be done for Exaile 4. If there are no objections, I think I should be able to do it fairly quickly.

**Comment by sbrubes** [comment]
I believe that it could not be the main problem.

From my point of view, the error is calling _set_tag_raw_ emitting event. (https://github.com/exaile/exaile/blob/master/xl/trax/track.py#L382)

So just call it with **_notify_changed_ to False**.

After it remains event for the tags below and it must be checked: 
```
__loc
__modified
__basedir
__date_added
__modified

```

Probably should also not send _track_tags_changed_ event to _loc_ and _basedir_, emitting just 2 (_date_added_ and _modified_).

Of course it will cause alot of impact on each handler of _track_tags_changed_ event and **needs more test**.

It's only a suggestion.

**Comment by virtuald** [comment]
@sbrubes this is a bit of a naming problem. When you call `read_tags()`, it reads the tags directly from disk, and stores them in Exaile's database. This could potentially cause the tags to change (in Exaile's database). The notification handlers exist so that if a track in a currently displayed playlist changes, the UI changes the displayed track contents (imagine if a track was changed outside of Exaile, for example). If there weren't notifications, then when the user refreshes the track they wouldn't see the changes, which would be undesirable.

As stated above, I think it would be better to batch the events up so less of them are being emitted -- though this probably wouldn't solve the entire problem. It seems like there are no objections to batching the notifications, so we should do that.

**Comment by sbrubes** [comment]
I agree to you.

I believe that we need what you suggest, having a new event to be per-track, instead of per-tag.

I just don't want to have to change it all. It could be as a deprecated, and moving all the new things to it.

Do you believe that this change (not sending events to each tag), could affect application anyway?

Thank you,
sbrubes

**Comment by virtuald** [comment]
We've made so many breaking changes in Exaile 4, I'm fine with just fixing it to be per-track, without bothering with deprecations. As far as I know, there are very few plugins that aren't in Exaile's source tree, so as long as we fix everything in the repository to deal with this change, then we should be good to go.

**Comment by sbrubes** [comment]
It's quite not a thing that I'm worried.

All fine. ;)

**Comment by virtuald** [comment]
I'm working on this today, and I've found a whole host of issues with track tag events. Hopefully can get this done quickly.
