### ISSUE TITLE
Error on clicking plugin Reload button

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#351]
1. Edit &rarr; Preferences &rarr; Plug-ins.
2. Click one of the reload buttons.

```
17:50:55,384:ERROR   : Unhandled exception (gtk)
Traceback (most recent call last):
  File "/exaile/xlgui/widgets/common.py", line 547, in do_activate
    pixbuf_width = self.props.pixbuf.get_width()
AttributeError: 'NoneType' object has no attribute 'get_width'


Locals at innermost frame:

{ 'background_area': <Gdk.Rectangle object at 0x0000000007eff738 (GdkRectangle at 0x000000000ec41...
  'cell_area': <Gdk.Rectangle object at 0x0000000007eff808 (GdkRectangle at 0x000000000ec41910)>,
  'event': <Gdk.Event object at 0x0000000007eff7a0 (GdkEvent at 0x000000000ecd1140) type=<enum GD...
  'flags': <flags 0 of type Gtk.CellRendererState>,
  'path': '4:1',
  'self': <common.ClickableCellRendererPixbuf object at 0x000000000677a500 (xlgui+widgets+common+...
  'widget': <Gtk.TreeView object at 0x0000000006749be0 (GtkTreeView at 0x00000000081d3470)>}
```

**Comment by genodeftest** [comment]
I don't see the reload button. How do you get there?

**Comment by sjohannes** [comment]
Apparently only there when you run with `--debug` (I just spent a long time trying to figure out why they didn't show up anymore).

Not a crucial bug then. We can safely push this to a future version.

**Comment by genodeftest** [comment]
Since this code is not used without `--debug`, how about removing it all together?

**Comment by sjohannes** [comment]
Well, the Reload feature is probably useful for developing plugins (I think?). Seems convenient; would have saved me having to restart Exaile after making changes to a plugin, if only I knew the feature existed.
