### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [exaile/exaile#352]
```
Traceback (most recent call last):
  File "tools/generate-completion.py", line 104, in <module>
    p = main.create_argument_parser()
  File "/home/solaraquarion/build/exaile-git/src/exaile/xl/main.py", line 75, in create_argument_parser
    usage=_("Usage: exaile [OPTION...] [LOCATION...]"),
  File "/home/solaraquarion/build/exaile-git/src/exaile/xl/nls.py", line 87, in gettext
    return gettextfunc(text).decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'
make: *** [Makefile:180: completion] Error 1
```

**Comment by virtuald** [comment]
What version of python are you using?

**Comment by virtuald** [comment]
That error would only occur if you're using Python 3. Exaile does not currently work on Python 3.

**Comment by virtuald** [comment]
I just pushed a fix, try it out and let me know if it works.

**Comment by SolarAquarion** [comment]
make: command: Command not found
make: command: Command not found
m compileall -q xl xlgui
make: m: Command not found
make: [Makefile:38: compile] Error 127 (ignored)
O -m compileall -q xl xlgui
make: O: Command not found
make: [Makefile:39: compile] Error 127 (ignored)
make -C plugins compile
make[1]: Entering directory '/home/solaraquarion/build/exaile-git/src/exaile/plugins'
python2 -m compileall -q .
python2 -O -m compileall -q .
make[1]: Leaving directory '/home/solaraquarion/build/exaile-git/src/exaile/plugins'
make: command: Command not found
tools/generate-completion.py > exaile.bash-completion
Traceback (most recent call last):
  File "tools/generate-completion.py", line 104, in <module>
    p = main.create_argument_parser()
  File "/home/solaraquarion/build/exaile-git/src/exaile/xl/main.py", line 75, in create_argument_parser
    usage=_("Usage: exaile [OPTION...] [LOCATION...]"),
  File "/home/solaraquarion/build/exaile-git/src/exaile/xl/nls.py", line 87, in gettext
    return gettextfunc(text).decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'
make: *** [Makefile:180: completion] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by virtuald** [comment]
What OS are you using, and what shell?

**Comment by SolarAquarion** [comment]
Zsh archlinux

**Comment by virtuald** [comment]
Try running the makefile in bash for now, and we'll fix it in zsh later.

**Comment by virtuald** [comment]
Weird, it works in zsh for me. Do you have a /usr/bin/python2 ?

**Comment by sjohannes** [comment]
I think I've fixed this properly now. Apparently `$(shell command -v python2)` doesn't use the shell's `command` builtin, but rather searches for a `command` executable in $PATH. And some systems don't have a `command` executable, causing the call to fail.

I've replaced the whole thing with just `python2`... I think that should be ok.

**Comment by dangmai** [comment]
Could you default it to the PYTHON2_CMD environment variables if it exists? I use it in the MSYS2 installer to tell Make where Python is

**Comment by sjohannes** [comment]
Done.

**Comment by dangmai** [comment]
Thanks!

**Comment by SolarAquarion** [comment]
it works perfectly now
