### ISSUE TITLE
Does not display Artist properly

### ISSUE THREAD

**Issue by Lee-the-Geek** [exaile/exaile#353]
The program lists Artist as 'Unknown' although the artist is clearly embedded in the songs which is evidenced by the fact that the Artist Name appears in the track info when I attempt to insert the artist name manually.

**Comment by virtuald** [comment]
Which version of Exaile? Can you provide the output of the `mutagen-inspect` command on the file?

**Comment by Lee-the-Geek** [comment]
Sorry for the delayed response. I have been offline for a few days, and it
will be a few more days yet before I am back on my real computer.

>

-- 
~/Lee the Geek

**Comment by genodeftest** [comment]
@Lee-the-Geek : Can you please answer that question? Maybe Github broke parsing your EMail.
> Which version of Exaile? Can you provide the output of the `mutagen-inspect` command on the file?

**Comment by Lee-the-Geek** [comment]
Version # 3.3.2. Linux is XFCE 17.3
The issue is in the program's inability to read the data in some MP3 and WAV files although the data is clearly there. It even appears in the child window when I go to edit.
Your response has taken so long, I don't even remember which songs.

**Comment by genodeftest** [comment]
> Version # 3.3.2. Linux is XFCE 17.3

Exaile has seen like 10 stable releases after that. Please update exaile to a more recent version (3.4.5 or the 4.0.0 beta 2). Probably your version of mutagen is also outdated. If you don't have these updates available in your Linux distribution, please run a distribution upgrade. Exaile 3.4.0, the next stable release, has been released almost 3 years ago.

> This has taken so long, I don't even remember which songs. I'll have to find some more...

Yeah, sorry. If you can reproduce this issue with a more recent version of Exaile (3.4.5 or 4.0.0) please comment here. Until then I'll close this bug.
