### ISSUE TITLE
During adding files to playlist, `track-tags-changed` is sent very often

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#357]
Steps to reproduce:
1. watch the handler for the `track-tags-changed` signal in info.TracklistInfoPane
2. start exaile
3. add many files to a playlist

What happens:
The `track-tags-changed` event is emitted on every single track.

What should happen:
I don't know whether that is necessary, but I doubt it. This may be one reason why it takes so long to add just a few files to a playlist.

Version:
Exaile from git master

Additional info:
This issue probably also affects other stuff. I stumbled upon it while fixing the osd plugin for #346.

**Comment by virtuald** [comment]
I'm sure it's not necessary (and if it is, then we'll make it not necessary!). Maybe print out what tags have claimed to be changed, that might provide insight to what's going on.

**Comment by sbrubes** [comment]
Issue related to https://github.com/exaile/exaile/issues/334.

The solution purposed here could fix it: https://github.com/exaile/exaile/issues/334#issuecomment-328880909
