### ISSUE TITLE
Drag/drop crash on OSX

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#369]
### Steps to Reproduce (for bugs)

1. Drag anything from the playlist

### Current Behavior

Segfault. :(
### Environment

* Operating System and version: OSX 10.12

* Exaile Version: git master

**Comment by genodeftest** [comment]
Any backtrace?

**Comment by virtuald** [comment]
Not yet, planning on investigating it tonight.

**Comment by virtuald** [comment]
This is a GTK issue, as I can reproduce it on gtk3-demo-application by just dragging some text around. Will file a bug upstream.

**Comment by virtuald** [comment]
Upstream @ https://bugzilla.gnome.org/show_bug.cgi?id=782914

**Comment by sbrubes** [comment]
http://python-gtk-3-tutorial.readthedocs.io/en/latest/drag_and_drop.html

I have tested this and works.

**Comment by virtuald** [comment]
Fixed in #472
