### ISSUE TITLE
UnicodeDecodeError when config dir is in non-ASCII folder

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#380]
### Steps to Reproduce (for bugs)
1. With latest git master (e.g. 4.0.0-beta1 release),
2. run `exaile --all-data-dir=/tmp/ä
3. watch output

### Expected Behavior
Start fine

### Current Behavior
Exaile refuses to start. I get a traceback, then Exaile stops:
```
Traceback (most recent call last):
  File "/path/to/exaile/xl/main.py", line 336, in __init__
    self.__init()
  File "/path/to/exaile/xl/main.py", line 467, in __init
    self._add_default_playlists()
  File "/path/to/exaile/xl/main.py", line 564, in _add_default_playlists
    self.smart_playlists.save_playlist(entire_lib, overwrite=True)
  File "/path/to/exaile/xl/playlist.py", line 1998, in save_playlist
    encode_filename(name)))
  File "/usr/lib64/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
```

**Comment by sjohannes** [comment]
Side note:

I had a quick look at the code and found another potential problem on Windows: xdg.datadirs checks `os.environ['EXAILE_DIR']`, which in Python 2 doesn't support Unicode (the unsupported characters are replaced with question marks). As far as I know there is no way to fix this other than by calling the wide-character WinAPI functions through ctypes.

But that is really a separate issue that I didn't bother testing or exploring further. I only mention it here so anyone debugging this on Windows don't get confused.
