### ISSUE TITLE
Erro message on ARM: FATAL: cannot locate cpu MHz in /proc/cpuinfo

### ISSUE THREAD

**Issue by AdamKlob** [exaile/exaile#39]
I have a HummingBoard ARM board (http://www.solid-run.com/products/hummingboard/), running Debian.

Exalie refuses to play any media I tried with following error message:

FATAL: cannot locate cpu MHz in /proc/cpuinfo

Aditional info:

~$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 10 (v7l)
Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0xc09
CPU revision    : 10

processor       : 1
model name      : ARMv7 Processor rev 10 (v7l)
Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0xc09
CPU revision    : 10

Hardware        : Freescale i.MX6 Quad/DualLite (Device Tree)
Revision        : 0000
Serial          : 0000000000000000

**Comment by virtuald** [comment]
Hm, never tried an ARM device. Can you post exaile's logfile?

**Comment by AdamKlob** [comment]
stdout:

~$ exaile
INFO    : Loading Exaile 0.3.2.2...
INFO    : Loading settings...
WARNING : Failed to import gtk.glade, interface will not be fully translated.
INFO    : Loading plugins...
Traceback (most recent call last):
  File "/usr/lib/exaile/xl/plugins.py", line 122, in enable_plugin
    plugin = self.load_plugin(pluginname)
  File "/usr/lib/exaile/xl/plugins.py", line 84, in load_plugin
    plugin = imp.load_source(pluginname, os.path.join(path,'__init__.py'))
  File "/usr/share/exaile/plugins/notifyosd/__init__.py", line 19, in <module>
    import cgi, glib, gtk.gdk, logging, pynotify
ImportError: No module named pynotify
WARNING : Unable to enable plugin notifyosd
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Loading interface...
WARNING : Failed to connect to HAL, autodetection of devices will be disabled.
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
INFO    : Playing file:///mnt/nas/music/Julia%20Marcell/It%20Might%20Like%20You/01%20-%20Put%20Your%20Headphones%20On.mp3
FATAL: cannot locate cpu MHz in /proc/cpuinfo

I could attach log if I knew where to find it.

**Comment by virtuald** [comment]
I can't find that particular log message in exaile's current source code, and we no longer support 0.3.2.2. Please upgrade to 3.4.x and let me know if you still have the same problem.

**Comment by AdamKlob** [comment]
With 3.4.2 it is the same:

~/exaile-3.4.2$ ./exaile 
INFO    : Loading Exaile 3.4.2 on Python 2.7.3...
INFO    : Loading settings...
INFO    : Using en_US UTF-8 locale
INFO    : Loading plugins...
INFO    : Loading collection...
WARNING : Exception occurred while loading /home/adamk/.local/share/exaile/music.db
WARNING : Exception occurred while loading /home/adamk/.local/share/exaile/music.db
WARNING : Exception occurred while loading /home/adamk/.local/share/exaile/music.db
INFO    : Loading devices...
WARNING : Failed to connect to udisks2, autodetection of devices will be disabled.
INFO    : Connected to udisks
INFO    : Loading interface...
INFO    : Using GTK+ 2.24.10
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
INFO    : Playing file:///mnt/nas/music/Amnesia%20The%20Dark%20Descent%20OST%20(MP3)/Amnesia%20OST%20-%2001%20-%20Menu%20Theme.mp3
FATAL: cannot locate cpu MHz in /proc/cpuinfo

If it is not from Exaile codebase, it must be from some library Exaile uses. I'm running full filesystem search to find it.

**Comment by AdamKlob** [comment]
I found it in libjack.so and libjacknet.so. This is a dependency of gstreamer. I do not use jack. Exaile should handle this error if possible.

**Comment by virtuald** [comment]
This sounds like a GStreamer problem then. I would recommend trying to play something simple with gstreamer via gst-launch, and see if that works. I don't have it on my computer at the moment, but I can look later tonight.

Another thought is to look at your playback preferences, and see what output plugin is configured. If it's configured for the auto sink, perhaps try a different output?

**Comment by AdamKlob** [comment]
My audio sink was configured as auto. I tried PulseAudio and ALSA with the same result.

**Comment by virtuald** [comment]
Alright, try using gst-launch to manually play a file using gstreamer. If you can get it to play this way, then we can fix Exaile. Here's what I used on my desktop to play a file:

```
gst-launch-0.10 filesrc location=/path/to/file.mp3 ! mad ! autoaudiosink
```

**Comment by AdamKlob** [comment]
Ok, trying to fiddle with gst-launch made me investigate my gstreamer setup, and it turned out the problem was there. After setting gstreamer correctly and setting Exaile to use PulseAudio and not audoconfig, I hear sound :)

Thanks for help, sorry for the problem. At least now You know that Exaile works on ARM :)

**Comment by virtuald** [comment]
Thanks!
