### ISSUE TITLE
Opening/closing settings saves over existing settings

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#390]
This is causing @sjohannes transparency issues... it's clearly intentional behavior (as all settings are copied over when the dialog is closed), though it is unexpected. Pretty easy to see when you do `--eventdebug`. It would be nice if it only emitted settings that actually changed.

**Comment by genodeftest** [comment]
See 00f6f934381ad9d118f9275a75d8fe25e3ce3a51 for a discussion.
