### ISSUE TITLE
exaile inhibits (prevents) Gnome auto-lock screen

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#40]
I run exaile under gnome 3.14. In gnome-control-center → Privacy the auto-lock screen is enabled to start after 2 minutes. It works fine when exaile is not running.
Whenever exaile runs and plays music GNOME does not lock the screen after >2min of inactivity. In fact it does seem to never lock at all.
I think this is some kind of "feature" introduced by gstreamer since I found no reference to this functionality in exailes code.

**Comment by sjohannes** [comment]
Do you have the Inhibit Suspend plugin enabled (Edit &rarr; Preferences &rarr; Plugins &rarr; Utility &rarr; Inhibit Suspend)? Apparently that also inhibits screensaver.

(To ease testing, you can reduce the screensaver delay by running *dconf-editor* and changing the value of *org.gnome.desktop.session/idle-delay*.)

**Comment by genodeftest** [comment]
No, this happens without any plugin enabled. Manually locking the screen still works.

Since I changed the values of `org.gnome.desktop.session/idle-delay` and `org.gnome.desktop.screensaver/lock-delay` to some low value the screen gets locked as it should even while playing music in exaile. So this was some kind of configuration (user?) issue. Or my mouse may have moved because of the music before the delay expired (don't know whether that is realistic).
Thanks for helping and sorry for wasting your time.
