### ISSUE TITLE
[gapless playback] exaile mutes playback if FLAC is played after one or two MP3 files (details unclear)

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#41]
Sometimes when exaile plays music from large playlists (randomly play songs, repeat everything active), it does the following:
1. The song which was started plays until the end
2. exaile loads the next song (and file, according to logging). This includes title information (above playlists) and cover, title length (progress bar below playlists).
3. In some cases exaile does not start playing the song. In fact the progress bar is stuck at 0:00 seconds though it should play (and it is not paused).
4. after some time exaile suddently starts playing the file (often just the last 1…3 seconds of the file) and then switches to step 2. again.

When clicking somewhere after 3. happened into the progress bar makes exaile behave normal and play the file.

I keep on running into this problem for quite a while but I am unsure how to reproduce it. The only thing I found out is that it only affects huge playlists. So it seems like exaile reacts special on some rare files (file types?). This could also be an issue with some gstreamer plugin, I don't know for sure.

It looks like this primarily affects flac files. When they are played often the first few seconds go missing. In this case the progress bar misses some seconds (e.g. 0:01 and 0:03). It looks to me like exaile desperately tries to play a file the moment it should start without caring whether it is already loaded. I might be wrong but it looks to me like a caching (and: hard disk file access time) issue.

This does not happen with VLC media player nor with totem (gnome's default media player using gstreamer). So it seems to be an issue with exaile only.

**Comment by genodeftest** [comment]
Someone at Arch Linux seems to have had the same problem. See https://wiki.archlinux.org/index.php/Exaile#Progress_bar_stuck_at_0:00 . His fixes didn't help me.

**Comment by virtuald** [comment]
I'd be interested in figuring out how to reproduce this, as it may help diagnose #76.

**Comment by genodeftest** [comment]
I think I finally managed to reproduce this bug:

This bug seems to happen if 2 MP3 files are played after each other followed by a flac file. The MP3 files do not have to be played completely, you may skip everything except the last and first few samples. The MP3 files should just play fine (as expected). The flac file will be loaded, you will see the

Playing file:///…

output. Metadata is loaded correctly (title, length, icon, …). The play/pause button still shows "pause" as if exaile were playing music but it isn't. Time slider is stuck at 0:00/4:37 (if song length is 4:37). UI still reacts to user input.

If you wait exaile will after some time (some seconds to several minutes) play as if it were playing all the time. Thus it will often start in the middle of a song. The time exaile is muted seems to depend on the time it played MP3 files before: if it played just a few seconds of MP3 it just skips a few seconds of the next FLAC file. If it played 2 whole MP3 songs it skips more than one minute of the next FLAC file. This is the last lines from starting to "play" (mute play) the FLAC file:

```
22:51:25,368:DEBUG   : Attempting to call <bound method MainWindow.on_track_tags_changed of <MainWindow object at 0x7fffdae7ea50 (xlgui+main+MainWindow at 0x10a8080)>> in response to track_tags_changed. (xl.event)
22:51:25,368:DEBUG   : Attempting to call <bound method PlaylistModel.on_track_tags_changed of <PlaylistModel object at 0x7fffd90107d0 (GtkListStore at 0x11e6ab0)>> in response to track_tags_changed. (xl.event)
22:51:25,368:DEBUG   : Attempting to call <bound method PlaylistsPanel.refresh_playlists of <PlaylistsPanel object at 0x7fffd8f271e0 (xlgui+panel+playlists+PlaylistsPanel at 0x11e0ba0)>> in response to track_tags_changed. (xl.event)
22:51:25,368:DEBUG   : Attempting to call <bound method TrackToolTip.on_track_tags_changed of <TrackToolTip object at 0x7fffd8f3dcd0 (GtkAlignment at 0x12dc690)>> in response to track_tags_changed. (xl.event)
22:51:25,369:DEBUG   : Attempting to call <bound method PlaylistModel.on_track_tags_changed of <PlaylistModel object at 0x7fffd8fe3a50 (GtkListStore at 0x119ce10)>> in response to track_tags_changed. (xl.event)
22:51:25,369:DEBUG   : Attempting to call <bound method PlaylistModel.on_track_tags_changed of <PlaylistModel object at 0x7fffd90039b0 (GtkListStore at 0xcbf6b0)>> in response to track_tags_changed. (xl.event)
22:51:25,369:DEBUG   : Attempting to call <bound method CollectionPanel.refresh_tags_in_tree of <CollectionPanel object at 0x7fffd8f7a7d0 (xlgui+panel+collection+CollectionPanel at 0xccaf80)>> in response to track_tags_changed. (xl.event)
22:51:25,369:DEBUG   : Attempting to call <bound method MainWindowTrackInfoPane.on_track_tags_changed of <MainWindowTrackInfoPane object at 0x7fffdae90870 (GtkAlignment at 0xfdfdc0)>> in response to track_tags_changed. (xl.event)
22:51:25,369:DEBUG   : Sent 'track_tags_changed' event from ''City of Angels' from 'Love Lust Faith + Dreams' by 'Thirty Seconds to Mars'' with data ''__playcount''. (xl.event)
22:51:25,370:DEBUG   : Attempting to call <bound method MainWindow.on_track_tags_changed of <MainWindow object at 0x7fffdae7ea50 (xlgui+main+MainWindow at 0x10a8080)>> in response to track_tags_changed. (xl.event)
22:51:25,370:DEBUG   : Attempting to call <bound method PlaylistModel.on_track_tags_changed of <PlaylistModel object at 0x7fffd90107d0 (GtkListStore at 0x11e6ab0)>> in response to track_tags_changed. (xl.event)
22:51:25,370:DEBUG   : Attempting to call <bound method PlaylistsPanel.refresh_playlists of <PlaylistsPanel object at 0x7fffd8f271e0 (xlgui+panel+playlists+PlaylistsPanel at 0x11e0ba0)>> in response to track_tags_changed. (xl.event)
22:51:25,370:DEBUG   : Attempting to call <bound method TrackToolTip.on_track_tags_changed of <TrackToolTip object at 0x7fffd8f3dcd0 (GtkAlignment at 0x12dc690)>> in response to track_tags_changed. (xl.event)
22:51:25,370:DEBUG   : Attempting to call <bound method PlaylistModel.on_track_tags_changed of <PlaylistModel object at 0x7fffd8fe3a50 (GtkListStore at 0x119ce10)>> in response to track_tags_changed. (xl.event)
22:51:25,371:DEBUG   : Attempting to call <bound method PlaylistModel.on_track_tags_changed of <PlaylistModel object at 0x7fffd90039b0 (GtkListStore at 0xcbf6b0)>> in response to track_tags_changed. (xl.event)
22:51:25,371:DEBUG   : Attempting to call <bound method CollectionPanel.refresh_tags_in_tree of <CollectionPanel object at 0x7fffd8f7a7d0 (xlgui+panel+collection+CollectionPanel at 0xccaf80)>> in response to track_tags_changed. (xl.event)
22:51:25,371:DEBUG   : Attempting to call <bound method MainWindowTrackInfoPane.on_track_tags_changed of <MainWindowTrackInfoPane object at 0x7fffdae90870 (GtkAlignment at 0xfdfdc0)>> in response to track_tags_changed. (xl.event)
22:51:25,371:DEBUG   : Sent 'track_tags_changed' event from ''City of Angels' from 'Love Lust Faith + Dreams' by 'Thirty Seconds to Mars'' with data ''__last_played''. (xl.event)
22:51:25,371:DEBUG   : Attempting to call <bound method PlaylistModel.on_playback_state_change of <PlaylistModel object at 0x7fffd90107d0 (GtkListStore at 0x11e6ab0)>> in response to playback_track_end. (xl.event)
22:51:25,371:DEBUG   : Attempting to call <bound method PlaylistModel.on_playback_state_change of <PlaylistModel object at 0x7fffd8fe3a50 (GtkListStore at 0x119ce10)>> in response to playback_track_end. (xl.event)
22:51:25,371:DEBUG   : Sent 'playback_track_end' event from '<xl.player.engine_normal.NormalPlayer object at 0x7fffdef2c6d0>' with data ''City of Angels' from 'Love Lust Faith + Dreams' by 'Thirty Seconds to Mars''. (xl.event)
22:51:25,371:INFO    : Playing file:///path/to/song.flac (xl.player.engine_normal)
22:51:25,372:DEBUG   : Attempting to call <bound method PlaylistView.on_playback_start of <PlaylistView object at 0x7fffd9010320 (xlgui+widgets+playlist+PlaylistView at 0x124ea80)>> in response to playback_track_start. (xl.event)
22:51:25,372:DEBUG   : Attempting to call <bound method PlaylistModel.on_playback_state_change of <PlaylistModel object at 0x7fffd90107d0 (GtkListStore at 0x11e6ab0)>> in response to playback_track_start. (xl.event)
22:51:25,372:DEBUG   : Attempting to call <bound method PlaylistModel.on_playback_state_change of <PlaylistModel object at 0x7fffd90039b0 (GtkListStore at 0xcbf6b0)>> in response to playback_track_start. (xl.event)
22:51:25,372:DEBUG   : Attempting to call <bound method TrayIcon.on_playback_change_state of <TrayIcon object at 0x7fffd8f3dc80 (GtkStatusIcon at 0x108b6e0)>> in response to playback_track_start. (xl.event)
22:51:25,372:DEBUG   : Attempting to call <bound method MainWindowTrackInfoPane.on_playback_track_start of <MainWindowTrackInfoPane object at 0x7fffdae90870 (GtkAlignment at 0xfdfdc0)>> in response to playback_track_start. (xl.event)
22:51:25,372:DEBUG   : Attempting to call <bound method DbusManager.emit_state_changed of <xl.xldbus.DbusManager at /org/exaile/Exaile at 0x7fffe995e250>> in response to playback_track_start. (xl.event)
22:51:25,372:DEBUG   : Attempting to call <bound method SeekProgressBar.on_playback_track_start of <SeekProgressBar object at 0x7fffd8f9b690 (xlgui+widgets+playback+SeekProgressBar at 0x12613c0)>> in response to playback_track_start. (xl.event)
22:51:25,373:DEBUG   : Attempting to call <bound method PlayQueue.on_playback_track_start of <xl.player.queue.PlayQueue object at 0x7fffecbb9410>> in response to playback_track_start. (xl.event)
22:51:25,373:DEBUG   : Attempting to call <bound method PlaylistView.on_playback_start of <PlaylistView object at 0x7fffd8fe3410 (xlgui+widgets+playlist+PlaylistView at 0x124e420)>> in response to playback_track_start. (xl.event)
22:51:25,373:DEBUG   : Attempting to call <bound method Playlist.on_playback_track_start of <xl.playlist.Playlist object at 0x7fffd8ff0c50>> in response to playback_track_start. (xl.event)
22:51:25,373:DEBUG   : Attempting to call <bound method Playlist.on_playback_track_start of <xl.playlist.Playlist object at 0x7fffdaeaa990>> in response to playback_track_start. (xl.event)
22:51:25,373:DEBUG   : Attempting to call <bound method PlaylistModel.on_playback_state_change of <PlaylistModel object at 0x7fffd8fe3a50 (GtkListStore at 0x119ce10)>> in response to playback_track_start. (xl.event)
22:51:25,373:DEBUG   : Attempting to call <bound method TrackToolTip.on_playback_track_start of <TrackToolTip object at 0x7fffd8f3dcd0 (GtkAlignment at 0x12dc690)>> in response to playback_track_start. (xl.event)
22:51:25,373:DEBUG   : Attempting to call <bound method MarkerManager.on_playback_track_start of <xlgui.widgets.playback.MarkerManager object at 0x7fffdbe0dc90>> in response to playback_track_start. (xl.event)
22:51:25,373:DEBUG   : Attempting to call <bound method PlaybackProgressBar.on_playback_track_start of <PlaybackProgressBar object at 0x7fffd8f430a0 (GtkProgressBar at 0x12ce0c0)>> in response to playback_track_start. (xl.event)
22:51:25,374:DEBUG   : Attempting to call <bound method MainWindow.on_playback_start of <MainWindow object at 0x7fffdae7ea50 (xlgui+main+MainWindow at 0x10a8080)>> in response to playback_track_start. (xl.event)
22:51:25,374:DEBUG   : Attempting to call <bound method PlaylistView.on_playback_start of <PlaylistView object at 0x7fffd90032d0 (xlgui+widgets+playlist+PlaylistView at 0x124e750)>> in response to playback_track_start. (xl.event)
22:51:25,374:DEBUG   : Attempting to call <bound method PlaybackProgressBar.on_playback_track_start of <PlaybackProgressBar object at 0x7fffdae90d20 (GtkProgressBar at 0x1073a70)>> in response to playback_track_start. (xl.event)
22:51:25,374:DEBUG   : Attempting to call <bound method ExaileMprisPlayer.track_change_cb of <mpris_player.ExaileMprisPlayer at /Player at 0x7fffdbd83050>> in response to playback_track_start. (xl.event)
22:51:25,375:DEBUG   : Sent 'playback_track_start' event from '<xl.player.engine_normal.NormalPlayer object at 0x7fffdef2c6d0>' with data ''Vox Populi' from 'This Is War' by '30 Seconds to Mars''. (xl.event)
22:51:25,375:DEBUG   : Attempting to call <bound method MainWindow.on_tags_parsed of <MainWindow object at 0x7fffdae7ea50 (xlgui+main+MainWindow at 0x10a8080)>> in response to tags_parsed. (xl.event)
22:51:25,375:DEBUG   : Attempting to call <bound method DbusManager.emit_track_changed of <xl.xldbus.DbusManager at /org/exaile/Exaile at 0x7fffe995e250>> in response to tags_parsed. (xl.event)
22:51:25,375:DEBUG   : Sent 'tags_parsed' event from '<xl.player.engine_normal.NormalPlayer object at 0x7fffdef2c6d0>' with data '('Vox Populi' from 'This Is War' by '30 Seconds to Mars', <GstTagList at 0x7fffb4046d90>)'. (xl.event)
22:51:25,375:DEBUG   : Attempting to call <bound method MainWindow.on_tags_parsed of <MainWindow object at 0x7fffdae7ea50 (xlgui+main+MainWindow at 0x10a8080)>> in response to tags_parsed. (xl.event)
22:51:25,376:DEBUG   : Attempting to call <bound method DbusManager.emit_track_changed of <xl.xldbus.DbusManager at /org/exaile/Exaile at 0x7fffe995e250>> in response to tags_parsed. (xl.event)
22:51:25,376:DEBUG   : Sent 'tags_parsed' event from '<xl.player.engine_normal.NormalPlayer object at 0x7fffdef2c6d0>' with data '('Vox Populi' from 'This Is War' by '30 Seconds to Mars', <GstTagList at 0x7fffac081b90>)'. (xl.event)
22:51:25,384:DEBUG   : Sent 'playlist_cursor_changed' event from '<PlaylistView object at 0x7fffd90032d0 (xlgui+widgets+playlist+PlaylistView at 0x124e750)>' with data '<xl.common.LazyDict object at 0x7fffecc2bdc0>'. (xl.event)
22:51:47,910:DEBUG   : Attempting to call <bound method MainWindow.on_tags_parsed of <MainWindow object at 0x7fffdae7ea50 (xlgui+main+MainWindow at 0x10a8080)>> in response to tags_parsed. (xl.event)
22:51:47,910:DEBUG   : Attempting to call <bound method DbusManager.emit_track_changed of <xl.xldbus.DbusManager at /org/exaile/Exaile at 0x7fffe995e250>> in response to tags_parsed. (xl.event)
```

So while playback mutes exaile does not do any logging. You can see that here: exaile didn't play from 22:51:25 until 22:51:47 and skipped the first ~20 seconds of the flac file.

If you don't wait but click into the progress bar / slider stuck at 0:00 it will play as if it were playing all the time.

[1] output generated by running `$ gdb --args /usr/bin/python2 /usr/share/exaile/exaile.py --datadir=/usr/share/exaile/data --startgui --new --all-data-dir=/tmp/exaile5 --eventdebug` in a newly created directory with just one single settings.ini file. This is the content of settings.ini:

```
[plugins]
enabled = L: ['mpris', 'gnomemmkeys']

[osd]
enabled = B: False

[player]
volume = F: 1.0
resume_paused = B: True

[gui]
collection_active_view = I: 6
files_panel_dir = S: file:///path/to/some/folder/30%20Seconds%20to%20Mars
files_filename_col_width = I: 262
mainw_height = I: 1016
mainw_width = I: 960
mainw_x = I: 960
mainw_y = I: 27
last_selected_panel = S: files
mainw_maximized = B: False
show_info_area = B: True
show_info_area_covers = B: True
show_tabbar = B: True
use_tray = B: True
minimize_to_tray = B: True
panels = D: {'files': (True, 3), 'radio': (True, 1), 'playlists': (True, 2), 'collection': (True, 0)}
mainw_sash_pos = I: 361
col_width_tracknumber = I: 50
col_width_title = I: 354
col_width_album = I: 354
col_width_artist = I: 354
col_width___length = I: 50
columns = L: ['tracknumber', 'title', 'album', 'artist', '__length', '__basename']
col_width___basename = I: 357
close_to_tray = B: True

[plugin/equalizer]
band0 = F: 0.0
band1 = F: 0.0
band2 = F: 0.0
band3 = F: 0.0
band4 = F: 0.0
band5 = F: 0.0
band6 = F: 0.0
band7 = F: 0.0
band8 = F: 0.0
band9 = F: 0.0
pre = F: 0.0
enabled = B: True

[general]
first_run = B: False

[preview_device]
volume = F: 1.0

[plugin/previewdevice]
shown = B: False

[plugin/notifyosd]
tray_hover = B: False
notify_change = B: True
notify_pause = B: True
notify_play = B: True
```

**Comment by genodeftest** [comment]
I should add that:

1. I can reproduce this bug with many different FLAC and MP3 files.
2. I can only reproduce this bug with some specific settings. I'm trying to bisect them.

**Comment by genodeftest** [comment]
I think I found the configuration option to reproduce this bug: Choose the default configuration and disable (!) the replaygain plugin. Then you will run into this bug. As a workaround I suggest enabling the replaygain plugin, this "fixes" the problem for me.
If you need more info or cannot reproduce the bug just ask.

**Comment by virtuald** [comment]
This sounds very much like an issue with gapless playback, and could explain why it shows up when you combine mp3 + flac. I've also seen this happen when I was trying to get playback working on multiple devices... You're using the 'normal' engine, right?

**Comment by genodeftest** [comment]
Yes, I am using the 'normal' engine.
Can I disable gapless playback for testing?

**Comment by virtuald** [comment]
There isn't an option for disabling gapless playback at the moment. Try https://github.com/exaile/exaile/tree/disable-gapless, I commented out the gapless playback functionality.

**Comment by genodeftest** [comment]
Is running `git checkout disable-gapless` enough to change branches? `git status` reports that exaile is on the disable-gapless branch.
If this is true, gapless is not to blame (or you didn't completely disable it).

**Comment by genodeftest** [comment]
Ok, I had to run `git reset --hard 22650f74e4`. Now this bug is gone
1. regardless of whether replaygain is active or not
2. regardless of whether I use the default configuration or my own one
3. regardless of which songs I play (files) as long as they are one or 2 MP3s followed by a FLAC file.

**Comment by virtuald** [comment]
That fixed it? Interesting. This is almost certainly a gstreamer bug then -- we're using gst 0.10, I suspect Totem et al are using gst 1.x, which probably has a fix for this bug. We might be moving to 1.x in the near future, see #3. It'll be awhile. As a stopgap, we could add an option to enable/disable gapless playback.

**Comment by genodeftest** [comment]
I can still reproduce this with the latest changes ( #128 ) to the gi branch. Sadly this is not fixed with gstreamer 1.x.
And it is no more limited to FLAC files, also affects MP3. Haven't tested other formats.
Could this be a multithreading related issue?

**Comment by virtuald** [comment]
@genodeftest that's sad to hear. There is a setting now to disable gapless playback, though I forgot to expose it in preferences. Pull again and there should be an option to disable gapless.

Also, can you send a debug log of the issue happening? I'll see if I can duplicate this later...

**Comment by virtuald** [comment]
So, I tried creating some files to duplicate this issue, but was not able to do so. Does it still require long playlists? I've got a repo with some files (https://github.com/exaile/exaile-test-files), and created a playlist with:

* gapless_3.flac
* gapless_4.flac
* tone.mp3

And that didn't trigger a bug as far as I can tell..

**Comment by genodeftest** [comment]
It doesn't always happen to me and you need 2 MP3 files. Playlist doesn't have to be long, mine had ~8 songs yesterday.
I'll try again generating a debug log tomorrow.

**Comment by virtuald** [comment]
Nice! I was able to duplicate it by adding a second mp3. Very strange.

**Comment by virtuald** [comment]
I created a small standalone file that shows the bug, with some test files. Try it out.

https://gist.github.com/virtuald/0aa9f7e30ed82c0270de

**Comment by sjohannes** [comment]
Here's what I'm getting on Windows, Gst 1.4.5. Comments inline.

```
about to play file:///D:/track1.flac  --> Start
pos: 0.93
pos: 1.93
pos: 2.93
about to play file:///D:/track2.flac
pos: 3.93
pos: 0.00  --> No gap
pos: 0.93
pos: 1.93
pos: 2.93
about to play file:///D:/track3.mp3
pos: 3.93
pos: 0.00  --> Gap
pos: 0.93
pos: 1.93
seek!  # Stop, Start
pos: 3.00
about to play file:///D:/track4.mp3
pos: 3.97
pos: 0.00  --> Gap (there's about a second of audio after the gap)
pos: 0.00  --> Stop
pos: 0.00
pos: 0.00
pos: 0.00
pos: 0.00
pos: 0.00
pos: 0.00
pos: 0.00
pos: 0.97  --> Start
pos: 1.97
pos: 2.97
Done  --> Stop
```

**Comment by virtuald** [comment]
Definitely a gstreamer bug, nothing weird about the example code I posted. I'll file a bug with them later.

Also, the gaps in the mp3 files are normal, as mp3 doesn't support gapless playback under most circumstances.

**Comment by virtuald** [comment]
We must be doing something wrong... there's a tool called 'gst-play', and running the following doesn't cause any issues:

```
gst-play-1.0 --gapless track1.flac track2.flac track3.mp3 track4.mp3
```

**Comment by genodeftest** [comment]
Sorry, I didn't find enough time to do the debug log. Do you still need it?

**Comment by virtuald** [comment]
Nope.

**Comment by virtuald** [comment]
I filed a bug on gstreamer's bugzilla at https://bugzilla.gnome.org/show_bug.cgi?id=753575

**Comment by dangmai** [comment]
I ran your script (bugger.py) in the bugzilla issue with GStreamer 1.6.1 on Windows and it seems to run correctly now (no stalling or loss of audio for track 3 and 4) :+1:

**Comment by genodeftest** [comment]
Same here on gstreamer 1.6.1.

**Comment by virtuald** [comment]
I'm going to close this then, and call it fixed until someone runs into it again. Will have to make sure to update the Windows installer too.

**Comment by genodeftest** [comment]
Hm, I'm running into this issue again, seems like it's not gone completely. This time it happens with short MP3 files, no FLAC involved. And after a "muted" file should have finished playing, exaile doesn't advance to the next file.
