### ISSUE TITLE
Playlist: closing shuffle or repeat popup resets its setting to disabled

### ISSUE THREAD

**Issue by rokm** [exaile/exaile#410]
I have been using the gtk3-enabled git master for a while now, and have observed the following minor annoyance, which is also present in 4.0.0-beta2: whenever I open the playlist's shuffle or repeat popup to check its setting, and then close the popup without selecting anything (e.g., pressing ESC, clicking elsewhere), the corresponding setting gets reset back to 'disabled'.

It would seem that the GtkRadioMenuItem emits the 'activate' signal not only when it becomes checked (active), but on every state change. Furthermore, when the popup is created, the first GtkRadioMenuItem in its group (= 'disabled') is automatically checked (set as active). Therefore, if any other item is checked afterwards due to the current setting, the first item will become unchecked and will emit 'activate' signal, hence resetting the setting. The 'activate' signal from the other item is not connected to the callback yet, so the proper setting is never recovered.

Therefore, the on_shuffle_mode_set() and on_repeat_mode_set() callbacks should check the widget's state before applying the mode. (Alternatively, connecting the item's callback before setting its state during popup construction would probably do the trick as well).

**Comment by genodeftest** [comment]
Nice catch, thanks! I have been wondering about that a while ago, and I thought it was intended (but inconvenient).

By the way, the current code works fine with keyboard navigation, i.e. if popping up the menu has been triggered by pressing the space key on the button, ESC closes the menu without loosing the current mode.
