### ISSUE TITLE
Some shortcuts are not listed in the Shortcuts window

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#417]
[MainWindow._setup_hotkeys](https://github.com/exaile/exaile/blob/643975c2db6dedd86faab11f3af7a229e9b2a4ac/xlgui/main.py#L145) adds a few things that are not listed by our Shortcuts window.

**Comment by genodeftest** [comment]
Fixed in 637288a82989d905c485ae6c09758a15620c257c.
