### ISSUE TITLE
[RFE] Add support for native ratings on Windows

### ISSUE THREAD

**Issue by svnpenn** [exaile/exaile#422]
I had previously rated some songs with Windows

I then added this folder to my collection, and add the ratings column to be seen

The Windows ratings show in Windows Explorer, but not in Exaile

**Comment by virtuald** [comment]
This isn't a thing Exaile supports. Will you implement a plugin for it?

**Comment by svnpenn** [comment]
Will I? No thank you

**Comment by virtuald** [comment]
My thoughts exactly.

**Comment by genodeftest** [comment]
@svnpenn : An explanation: We don't have enough contributors nor time to implement this. If someone wants to step up and implement it, pull requests are welcome. Unless that happens, this feature won't be implemented.

**Comment by svnpenn** [comment]
@genodeftest no biggie, plenty of competing programs out there

@virtuald I see your passive aggressive there - you can shove it up your ass

**Comment by virtuald** [comment]
@svnpenn nothing passive aggressive here, I'm just being practical. If you (or someone) is willing to implement this, then I'm willing to accept the PR. However, if you're not going to do it, then I don't want this feature request cluttering up our task list, as it's unlikely it'll ever be done.

If you don't want to implement a feature that you care about, why should I implement a feature I don't care about? That seems rather inefficient.

**Comment by genodeftest** [comment]
Since @svnpenn is using inappropriate language here, I'm locking this conversation. This is not a place for verbal aggression.
