### ISSUE TITLE
How to update https://exaile.readthedocs.io/en/stable/ ?

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#425]
With the changes in e41b490179bbbe9d781d8a4a96adce13f5ec1c1b, 86cf1ce2236fa0b499e93ddb4d432112b6c94ade and ec4b27c05df1d2c5e177c29b8b0cc8b744c5edf1 it would be nice to get https://exaile.readthedocs.io/en/stable/ updated. How can this be done? Should we wait until the 4.0.0 Release?

**Comment by virtuald** [comment]
Yeah, a non-beta tag has to exist for RTD to set it as stable. One can force any arbitrary tag to be stable if desired.

**Comment by genodeftest** [comment]
> Yeah, a non-beta tag has to exist for RTD to set it as stable. One can force any arbitrary tag to be stable if desired.

Ok, so once Exaile 4.0 is going final, the docs will be updated. That's ok for me.
