### ISSUE TITLE
Force-disable the tray icon on GNOME shell 3.26+ ?

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#426]
GNOME shell developers [recently announced](https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/) that they will ship version 3.26 without support for a system tray, i.e. without support for `GtkStatusIcon`. They have also published [some more infos](https://wiki.gnome.org/Initiatives/StatusIconMigration/) and [guidelines for migration](https://wiki.gnome.org/Initiatives/StatusIconMigration/Guidelines).

Now what do we do? Disable enabling the tray icon on gnome-shell?

**Comment by virtuald** [comment]
Maybe put a warning in the plugin description? Doesn't seem like we can detect the lack of status icons.

**Comment by sjohannes** [comment]
The TopIcons extension [will still provide](https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/) this functionality for users that want it. I think it's fine to keep the option there; if the user messes around with the tray options and accidentally hides the window, they can still unhide it by rerunning Exaile.

**Comment by genodeftest** [comment]
I've pushed a workaround (some text to educate the user). Feel free to criticize ;)
