### ISSUE TITLE
Panels: TreeView context menus don't show at all

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#436]
1. Bring up one of the panels that has a treeview
2. Either:
  2.1. Right-click on a treeview row; or
  2.2. Select a treeview row and press the Menu button.

(2.1) Results in nothing happening. (2.2) results in the notebook's context menu to show up (instead of the treeview's).

Might be related to 5c1ecd491255b388cc38a7308513b247105606f8. Tested on Windows (MSYS2), GTK+ 3.22.21, PyGObject 3.24.1.

**Comment by genodeftest** [comment]
2.2 is already covered in #291 as far as I understand and has been present for >1 year.

If 5c1ecd4 were related, it should have broken context menu almost everywhere in Exaile, but it didn't. Anyway, bisecting shows that 5c1ecd4 is to blame breaking the context menu here, but everything looks fine with that commit. So I guess that commit just allows the bug to happen although the code was broken before.

**Comment by javiercantero** [comment]
Can confirm this. Using Debian GNU/Linux Stretch and the last master:
```
INFO    : Loading Exaile 4.0.0beta2+407ed9a...
INFO    : Using Python 2.7.13
INFO    : Using PyGObject 3.22.0
INFO    : Loading settings...
INFO    : Using Locale es_ES UTF-8
INFO    : Using Mutagen 1.36
INFO    : Using GStreamer 1.10.4
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.22.11
```

**Comment by flberger** [comment]
Confirming that 5c1ecd4 broke the tree view context menu here as well.

    INFO    : Using Python 2.7.10
    INFO    : Using PyGObject 3.22.0
    INFO    : Using Locale de_DE UTF-8
    INFO    : Using Mutagen 1.27
    INFO    : Using GStreamer 1.10.3
    INFO    : Using GTK+ 3.22.15

**Comment by virtuald** [comment]
I ran into this also. The problem is that gdk_event_triggers_context_menu only applies if the event is a GDK_BUTTON_PRESS, and many of the places where this was broken are button releases.

I'm going to create a popup-menu helper function to make sure we always do this correctly, there's a lot of duplicate code anyways related to popping up menus.

**Comment by virtuald** [comment]
I've done a bit of work on this, and I'm coming to realize that fixing this in a centralized place is difficult for two reasons:

* A lot of our menus are currently in button_release handlers, and there's a lot of other logic interspersed
* It seems each treeview is just a little bit different in how it prefers to deal with things like menu clicks, selections, and etc. In particular, drag/drop gets in the way here.

**Comment by flberger** [comment]
Sounds like a call for refactoring. :)

Any use in reverting this particular feature to pre 5c1ecd4 for the time being?

**Comment by virtuald** [comment]
I inspected each instance of triggers_context_menu and reverted the ones that were used in a button release event, and left the ones in that belong to a button press event.

I also pushed the `simple-menu` branch with some ideas on fixing our menu popup duplication issues... but I'm tabling that for now.
