### ISSUE TITLE
What should space bar do?

### ISSUE THREAD

**Issue by XzuRukneg** [exaile/exaile#441]
When I press space bar, Exaile play and I think it's good.
But when I press again, it replay at the beginning of the track. Don't you think it's better if it pause, so it can re-start if space bar is pressed again?

* Exaile Version: 4.0.0 -beta2

**Comment by virtuald** [comment]
That seems like a reasonable expectation.

**Comment by genodeftest** [comment]
Can you see where your keyboard focus is when pressing the space bar again?

As far as I can see, there are several different ways to use the space bar to trigger playing a song, including:
* select an audio file in "Files" panel.
  * Pressing space bar adds it to the current playlist.
  * Pressing space bar repeatedly adds it to the current playlist multiple times.
* select an item in any playlist.
  * Pressing space bar starts playback.
  * Pressing space bar repeatedly restarts playback.
* select the "play" button.
  * Pressing space bar toggles its state, even when repeated. I would not change this behaviour.
* select any item in a queue
  * Pressing space bar starts playback of the currently selected item. I would not want to change this behaviour.

Did I miss any case? In the first two cases I agree that pausing playback would be a reasonable alternative behaviour.
