### ISSUE TITLE
TypeError upon exit

### ISSUE THREAD

**Issue by mexicarne** [exaile/exaile#442]
Hello, 

I'm seeing an regression between 11885d6 (20170907) and 9ba2cc8 (20171020). Every time I'm quitting exaile via File -> Quit Exaile menu item, I get this in terminal:

```
Exception TypeError: "'NoneType' object is not callable" in <object repr() failed> ignored
Exception TypeError: "'NoneType' object is not callable" in <object repr() failed> ignored
```
Here is the full log with --debug, but it doesn't seem contain any clues about the error:
https://dpaste.de/BDWQ/raw

**Comment by genodeftest** [comment]
I can't reproduce this issue (although I've seen it before a while ago). Do I read correctly that the only plugin you have enabled is `equalizer`? Do you have the tray icon enabled?

**Comment by mexicarne** [comment]
Yes, the only plugin is equalizer, and tray icon is enabled. When I disable tray icon and restart Exaile - nothing changes, the error is still there. 
If I disable equalizer and restart Exaile, I still get the error upon exit.

**Comment by genodeftest** [comment]
Would you mind sending me your Exaile configuration file? You should find it under `~/.config/exaile/settings.ini` on any Unix system. You might want to send it via mail (see my profile) and you may encrypt it to PGP key id 0x545B42FB8713DA3B.

**Comment by mexicarne** [comment]
It does not contains any sensitive information, so here it is:
https://dpaste.de/gpBX

I only changed real username to `user` in `files_panel_dir`

**Comment by mexicarne** [comment]
Btw, the error is still there, if I remove my original settings.ini and let Exaile generate new one.

**Comment by genodeftest** [comment]
Ok, that's pretty weird because when I start Exaile (same revision 9ba2cc8) without a settings.ini, it does not give me that TypeError.

**Comment by mexicarne** [comment]
How can I find where in the code these exceptions are triggered?

**Comment by genodeftest** [comment]
I can't reproduce the issue with your settings.ini (which is expected because removing your settings.ini does not make it go away).

Our documentation has a section on debugging Exaile: http://exaile.readthedocs.io/en/latest/dev/debugging.html#using-gdb-to-diagnose-issues
I'm not sure but you may want to try just running exaile under gdb and see whether it stops on those exceptions. Then running `bt` and `py-bt` might help. I don't know where this output is generated though, but https://stackoverflow.com/questions/16620932/ has a slight idea. I don't know how to set a breakpoint on the try/catch handler for `__del__` methods though.

**Comment by genodeftest** [comment]
The output is written in Python's `error.c` file in function `PyErr_WriteUnraisable`, so you might want to set a breakpoint there too: `break PyErr_WriteUnraisable` in gdb.

**Comment by mexicarne** [comment]
Will try, thank you!

**Comment by genodeftest** [comment]
@mexicarne : I've also added the documentation to #448. Did it work for you?

**Comment by sbrubes** [comment]
I get this error too.

**Comment by genodeftest** [comment]
@sbrubes : Could you please try and run Exaile under gdb as described in https://github.com/exaile/exaile/blob/master/doc/dev/debugging.rst#debugging-ignored-exceptions ?

PS: It seems like our documentation server is offline.

**Comment by sbrubes** [comment]
@genodeftest are you at IRC channel?

**Comment by genodeftest** [comment]
I am now. Same username.

**Comment by sbrubes** [comment]
That fix it.

**Comment by mexicarne** [comment]
I can confirm that this patch fixing the issue. Thank you!

**Comment by genodeftest** [comment]
@mexicarne Thanks for reporting back!
