### ISSUE TITLE
Right click menus broken on Fedora Linux

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#459]
Not sure if it applies to other OS. git bisect indicates it was introduced in 5c1ecd491255b388cc38a7308513b247105606f8, I'll dig in and figure out what broke.

**Comment by virtuald** [comment]
Ok, the problem is that gdk_event_triggers_context_menu only applies if the event is a GDK_BUTTON_PRESS, and many of the places where this was broken are button releases.

I'm going to create a popup-menu helper function to make sure we always do this correctly.

**Comment by javiercantero** [comment]
I think this was already reported as #436.

**Comment by virtuald** [comment]
Thanks, I'll move it there.
