### ISSUE TITLE
Device Manager not working

### ISSUE THREAD

**Issue by RayArdia** [exaile/exaile#46]
When I select 'Tools', 'Device Manager' the DM screen appears but, although connected my device is not shown.
I'm using Exaile ver 3.3.2 on Ubuntu 14.04. The device involved is an Energy 8.5GB music player; how do I transfer a playlist to it?

**Comment by virtuald** [comment]
The device manager doesn't do anything if the right plugins aren't enabled. Device manager definitely is something that we need to improve in the future. @sjohannes might know more.

**Comment by sjohannes** [comment]
As far as I know, there are three device plugins: *cd*, *massstorage* (for devices that support the USB Mass Storage protocol), and *ipod*. Of those three, only *cd* will work in recent Linux distributions. *massstorage* and *ipod* still depend on HAL, which is very outdated now. Note also that we don't have a plugin that supports the MTP protocol.

As an alternative, if GVFS is set up properly, you may be able to access the device from its filesystem mount at `/run/user/1000/gvfs/...`.

To anyone interested in updating the *massstorage* plugin, have a look at the *UDisks2CdProvider* class in the *cd* plugin. The Exaile-side API is pretty simple, but you'll have to figure out the UDisks2/D-Bus side (you can use D-Feet for browsing D-Bus services).

**Comment by RayArdia** [comment]
Thanks virtuald and sjohannes, however, it would seem to be the case that as things stand at  present Exaile doesn't allow for the transfers that I want it to do.
Looks like I shall have to persevere with some of the other 'inadequate-in-some-important-areas' music players. I'm very dissappointed as I'd thought that with its straightforward-looking GUI that Exaile might have been the answer.

**Comment by virtuald** [comment]
@RayArdia if you create a playlist, you can right click on it and 'Export Files', which will copy all of the files of the playlist to the directory of your choosing. That might meet your needs.

**Comment by RayArdia** [comment]
That doesn't work for me - when I right-click on a playlist the menu only gives me 'Enqueue, Stop playback after this track, Rating, Remove, Randomise playlist, Properties'. Right-click on the Paylist header tag I get 'New Playlist, Save As, Rename, Clear, Close'.
Ray

**Comment by virtuald** [comment]
Try saving the playlist, and then right clicking on the playlist in the playlist panel. 

... yes, that needs to be fixed too.

**Comment by RayArdia** [comment]
Yes, see what you mean. From 'Playlist Panel' I have the right-click option to 'Export Files' that seems to work except, as soon as a .flac file is encountered instead of transcoding to .mp3 (like eg. Clementine) the expot just stops with an error message. I will try it again with a playlist of .mp3 files only - but not just now, it's bedtime!

**Comment by virtuald** [comment]
What's the error? It should just copy the file..

**Comment by RayArdia** [comment]
Came back to it fresh this a.m! Problem solved; because the playlists I was trying to copy to my music player were 'generated' within Clementine, they must have carried some spurious information. When I make up a new playlist from within Exaile, ie using data from the LH panel then saving as a new playlist, all is well, the files can be exported to the music player.
Many thanks for your help.
Regards, Ray
