### ISSUE TITLE
Traceback when scanning AIF file

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#463]
### Steps to Reproduce (for bugs)
1. Have a .aif file
2. scan the folder containing it

### Expected Behavior
No traceback

### Current Behavior
```
ERROR   : Error reading tags for file:///path/to/some/file.aif
Traceback (most recent call last):
  File "/path/to/exaile/xl/trax/track.py", line 381, in read_tags
    f = metadata.get_format(loc)
  File "/path/to/exaile/xl/metadata/__init__.py", line 124, in get_format
    return formatclass(loc)
  File "/path/to/exaile/xl/metadata/_base.py", line 104, in __init__
    self.load()
  File "/path/to/exaile/xl/metadata/wav.py", line 48, in load
    opener = type_map[ext]
KeyError: u'aif'
```

### Possible Solution
Should we remove support for AIF files?

### Environment
* Operating System and version: Fedora 26, python2-2.7.14-2.fc26.x86_64
* Exaile Version: latest git master (af00c467561394aa373c0accff6f7e6267d0dcc3)

**Comment by sbrubes** [comment]
Probably adding the first line to xl.metadata.wav.type_map fix it:

```
type_map = {
    "aif": aifc,
    "aifc": aifc,
    "aiff": aifc,
    "au": sunau,
    "wav": wave,
}
```

**Comment by virtuald** [comment]
Mutagen supports AIFF files natively now (seems to use ID3 underneath the hood), switching to use that.
