### ISSUE TITLE
Find or make an up-to-date version of Moodbar

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#464]
Last I checked, Moodbar depends on GStreamer 0.10, which is gone in most package repositories. Clementine has a version that works with GStreamer 1 but it's integrated into their codebase. I'll see if I can pull it out and turn it into something we can use.

**Comment by sjohannes** [comment]
https://gitlab.com/sjohannes/moodbar

**Comment by sjohannes** [comment]
New location: https://github.com/exaile/moodbar

**Comment by genodeftest** [comment]
Neat, thank you. Works fine with the moodbar plugin!
