### ISSUE TITLE
Segmentation fault enqueuing

### ISSUE THREAD

**Issue by sbrubes** [exaile/exaile#478]
Segmentation fault enqueuing a track, after closing Queue tab.

### Steps to Reproduce (for bugs)
1. Open Exaile
2. Enqueue a track (at my case from Files Panel)
3. Close the Queue tab
4. Enqueue a track again

### Current Behavior
```
Traceback (most recent call last):
  File "/path/to/exaile/xlgui/main.py", line 682, in on_playlist_container_switch_page
    selection.connect('changed', self.on_playlist_view_selection_changed)
AttributeError: 'NoneType' object has no attribute 'connect'

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

### Environment
MacOS High Sierra 10.13.3 / Python 2.7.13 / GTK+ 3.22.26
Exaile at https://github.com/exaile/exaile/commit/e1c3359dd140e724485a8e9e7ea8bbd0831973b9

**Comment by virtuald** [comment]
Reproduced on GTK/Linux. Taking a look now.

**Comment by sbrubes** [comment]
@virtuald Thank you. :D
