### ISSUE TITLE
Apply group tag to more that one song at once 

### ISSUE THREAD

**Issue by flberger** [exaile/exaile#48]
*Migrated from [https://bugs.launchpad.net/exaile/+bug/1341448](https://bugs.launchpad.net/exaile/+bug/1341448)*

In exaile 3.4.0-dev+bzr4524 and the group tagger plugin 0.3, when I select a couple of songs in a playlist and mark a group tag in the GroupTagger panel, only the very first of the selected songs is bein labelled.

This makes it very cumbersome to apply a group tag to more that a handful songs at once.

I propose the following feature:

- When selecting several songs and checking the group tag, a dialog appears "Are you sure you want to apply tag X to more that one song?"

- Confirming "OK", the tag is being applied to all selected songs.

- The dialog could also feature a "Remember selection and don't ask me again" checkbox.

Thanks for considering.

**Comment by virtuald** [comment]
Fixed, albeit slightly differently.
