### ISSUE TITLE
Deleting lots of tracks is slow if the cursor is at the top

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#485]
1. Open the Random 500 playlist.
2. Set focus on the tracklist.
3. Press Home, Shift+End, Del.  (CASE 1)
4. Do steps 1-2.
5. Press End, Shift+Home, Del.  (CASE 2)

Result: In case 1, there is a noticeable delay but it's under 1 s. In case 2, the delay is 2-3 seconds.

**Comment by virtuald** [comment]
It's going to be because the cursor keeps changing (I think as a result of the rows below being inserted). It's yet another weird synchronization error from our model/playlist combination.

**Comment by virtuald** [comment]
Found a fix, I'll push it in to #488 as the solutions are related
