### ISSUE TITLE
Unexpected tracks selected after drag to playlist completes

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#487]
### Steps to Reproduce (for bugs)
1. Drag file(s) within playlist

### Expected Behavior
Dragged file(s) should be selected

### Current Behavior
Random file seems to be selected?

**Comment by sbrubes** [comment]
@virtuald I've notice it, while solving the bug we've talk on IRC's channel and I'm planning to post this solution together (probably today later/already solved)
