### ISSUE TITLE
What should double click do?

### ISSUE THREAD

**Issue by sbrubes** [exaile/exaile#495]
At beta3, when you double click a playing row, it pauses.

Related to #441

**Comment by sbrubes** [comment]
We probably should have two behaviors:

If paused: continue
If playing: restart

Need opinions.

**Comment by genodeftest** [comment]
> If paused: continue
> If playing: restart

Sounds reasonable.

**Comment by sbrubes** [comment]
That’s awesome @rokm! Thanks.

Closed by #507.
