### ISSUE TITLE
Untranslatable string "the"

### ISSUE THREAD

**Issue by adem4ik** [exaile/exaile#50]
Russian as well as some other languages doesn't have articles like "the" at all. So how it can be tranlasted? I've never seen such string for translation in other projects.

https://en.wikipedia.org/wiki/Article_(grammar)#Variation_among_languages

**Comment by eri-trabiccolo** [comment]
Do you mean this: https://github.com/exaile/exaile/blob/master/po/messages.pot#L892
?
Well, leave it blank. That string fills an input field in the preferences -> Collection, for grammatical articles to skip when sorting the collection, so I don't see the problem ...
Also it's broken now and an empty list will be returned anyway. :D

**Comment by adem4ik** [comment]
Thanks for the fast reply. Sorry i've used https://hosted.weblate.org/projects/exaile/ for tranlating, so i didn't see that comment.

**Comment by eri-trabiccolo** [comment]
Ohhh I see so it doesn't provide comments for translators .. :(

**Comment by sjohannes** [comment]
It's actually there! In tiny print on the right side of the page. :(

However, that comment is outdated. [Here's the latest version:](https://github.com/exaile/exaile/blob/master/xlgui/preferences/collection.py#L27)

```python
def _get_default_strip_list():
    return [] # currently, this is broken by the backend not also having access to the default set here, so we will just NOT set one. FIXME
    #TRANSLATORS: Grammatical articles that are ignored while sorting the
    #collection panel. For example, in French locales this could be
    #the space-separated list "l' la le les".
    #If this practice is not common in your locale, simply
    #translate this to string with single space.
    default_strip_list = _("the")
    return [v.lower() for v in default_strip_list.split(' ') if v is not '']
```

As you can see, the string is currently unused (and unfortunately I don't understand the comment about the backend stuff). Also, we just found that the string cannot be blank (gettext thinks empty string = untranslated), so it should be translated a single space character instead.

**Comment by eri-trabiccolo** [comment]
Yeah, I was wrong, of course, no translation => use the original string . Sorry
