### ISSUE TITLE
Finalize 4.0 release notes

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#502]
Just tracking this so we don't forget to update the release notes before release.

https://github.com/exaile/exaile/wiki/Exaile-4.0-release-notes

**Comment by genodeftest** [comment]
Is anything missing there?

**Comment by sjohannes** [comment]
No, it's up to date. Just make sure to remove the "this is a draft" note when releasing.

**Comment by genodeftest** [comment]
This is the last issue open with "Milestone" set to 4.0. Is there anything else to block the release or can we close this issue?

**Comment by sjohannes** [comment]
This is not meant to block the release. It's just a reminder to keep the release notes updated with any changes that happen, and to update it during the release process (remove draft notice, add release date).

**Comment by X0rg** [comment]
So it looks like v4.0 is ready to be finalized.
I don't have any issue with v4.0.0-rc5 on Arch. :ok_hand:

**Comment by virtuald** [comment]
I agree. I was traveling last weekend, but I think we should be able to release... now, I guess? Any last changes to put into the changelog?

**Comment by sjohannes** [comment]
Nope, all up to date.
