### ISSUE TITLE
Enable "Show potentially broken plugins" by default

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#503]
Currently users can't see (by default) what plugins they may be missing out on if they don't already have the requirements installed.

In fact it's probably better to remove the checkbox altogether and always enable it.

**Comment by genodeftest** [comment]
In this case, please make sure that the "enable" checkbox is inactive, i.e. a plugin cannot be enabled.

**Comment by sjohannes** [comment]
I've left the Enable checkbox alone for now. This way users can try enabling it and see which module they're missing. In the future we can make this clearer by indicating the missing module in the UI (e.g. as a tooltip on the warning icon).
