### ISSUE TITLE
Autoformat code

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#504]
I know @genodeftest has been itching to reformat things for awhile now...  ;)

Someone showed me https://github.com/ambv/black, and I'm actually really happy with it's output for the most part... it's not terrible like some of the code formatters I've seen. I'm not quite sure what it would do to Exaile's source code or if it's python2 compatible, but might be worth looking at.

**Comment by sjohannes** [comment]
Another formatter we could try is [yapf](https://github.com/google/yapf). It's modelled after clang-format so it's very configurable. At the same time it means a lot of fiddling with configs to figure out the style that we want.

**Comment by virtuald** [comment]
We did this, closing.
