### ISSUE TITLE
MPRIS pause/play causes go to next song

### ISSUE THREAD

**Issue by kacernator** [exaile/exaile#509]
When using global shortcut in KDE Plasma 5.12 for pause/play, hitting the keyboard shortcut first it pauses the play, but hitting the shortcut for the second time it goes to next song, when it should just continue play the paused song.

Exaile 4.0.0beta3
Opensuse Leap 15

**Comment by sjohannes** [comment]
Does it also happen if you trigger the play/pause MPRIS2 action with this?

    dbus-send --print-reply --session \
      --dest=org.mpris.MediaPlayer2.exaile \
      /org/mpris/MediaPlayer2 \
      org.mpris.MediaPlayer2.Player.PlayPause

It would be great if you could test with other players as well.

**Comment by kacernator** [comment]
With dbus-send command you send, it works normal, as it should. I tried VLC and it doesnt have this problem.

**Comment by sjohannes** [comment]
Confirmed. Plasma's MPRIS2 client uses Play and Pause individually instead of using PlayPause. Our Play handler is broken and plays the next track when the current track is paused.

**Comment by sjohannes** [comment]
Should work correctly now. Thanks for the report!

**Comment by sjohannes** [comment]
Ah, sorry, I meant that I've fixed it in the development tree, but I'm not sure when it will be released. It might take some time.

I'm not familiar with openSUSE's processes but you may be able to get it fixed there faster by filing a bug report and pointing them to this page. This way they can patch the 4.0beta3 version without waiting for us to release a new version.

In the meantime, you can also edit the installed code, although I don't know how it will impact future upgrades. Edit `/usr/share/exaile/plugins/mpris2/mprisobject.py` and replace the `Play` function with this:

```py
    def Play(self):
        player = xl.player.PLAYER
        state = player.get_state()
        if state == 'paused':
            player.unpause()
        elif state == 'stopped':
            queue = xl.player.QUEUE
            queue.play(queue.get_current())
```

**Comment by kacernator** [comment]
That patch works OK.
