### ISSUE TITLE
Consider using NoSuspend

### ISSUE THREAD

**Issue by KOLANICH** [exaile/exaile#516]
I have tried to create a cross-platform lib for inhibiting entering powersaving mode. You may want to use it. 
https://github.com/KOLANICH/NoSuspend.py/blob/master/NoSuspend.py

**Comment by genodeftest** [comment]
What will be the benefit over [`Gtk.Application.inhibit()`](https://developer.gnome.org/gtk3/stable/GtkApplication.html#gtk-application-inhibit)?

**Comment by KOLANICH** [comment]
>What will be the benefit over Gtk.Application.inhibit()?


I guess no benefit when used on a GTK system.
