### ISSUE TITLE
Playback issues

### ISSUE THREAD

**Issue by Entropy0** [exaile/exaile#52]
This one is probably hard to diagnose, since I can't actually tell when it started:

For a while now I have been getting playback issues/ "white noise" superimposed on my music (basically it sounds like I've got poorly soldered cables going to my headphones) - I used to think it was an issue with my hardware (which is why I can't actually tell when it started), but recent tests with different Hardware and/ or players show that only exaile is affected. Not only that, but even exaile with unified engine isn't affected. Ballpark guess puts the start of the misbehavior somewhere between summer and autumn last year.

There are no errors on console.

**Comment by virtuald** [comment]
... I feel like I've seen someone else posting this recently. Was that you?

**Comment by Entropy0** [comment]
Yes, on the old Launchpad tracker. I just migrated this issue here after being told the old bug tracker was no longer being used.

**Comment by virtuald** [comment]
Gotcha, that's where it was from.

**Comment by Entropy0** [comment]
A stroke of inspiration just made me disable the equalizer (which I didn't use anyway - everything was set to 0.0) and what do you know? All my problems just disappeared. So apparently this is an issue with the equalizer, not playback in general.

**Comment by virtuald** [comment]
Hm, is the EQ enabled by default? Maybe the right answer here is to disable the EQ unless the user asks for it.

**Comment by virtuald** [comment]
Going to disable the equalizer by default for now until we can figure out what's going on here.

**Comment by virtuald** [comment]
Disable EQ by default in 69b35c9
