### ISSUE TITLE
Failure to run - subprocess ERRNO2

### ISSUE THREAD

**Issue by humantex** [exaile/exaile#521]
Installed without issue from a standard CentOS 7 yum install (I'm assuming, epel)

Fails to open from icon click in menu or with terminal command

No error pop-ups when clicking the menu item, but do get a popup and short error trace from terminal...
```
[root@centos7 ~]# exaile
Error: running as root is not supported!
Traceback (most recent call last):
  File "/usr/share/exaile/exaile.py", line 85, in <module>
    main()
  File "/usr/share/exaile/exaile.py", line 82, in main
    exaile = main.Exaile()
  File "/usr/share/exaile/xl/main.py", line 164, in __init__
    from xl.version import __version__
  File "/usr/share/exaile/xl/version.py", line 49, in <module>
    revision = get_current_revision(xdg.exaile_dir)
  File "/usr/share/exaile/xl/version.py", line 43, in get_current_revision
    'git', 'rev-parse', '--short=7', 'HEAD'
  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
I get essentially the same error, whether I'm attempting to run as root or a regular user... with the difference being the 1st line about 'root not supported' - and - the references to the user's home directory names.

(I'm unsure why a music player app would be unacceptable to run as root, when 'root' is a valid logged in user on CentOS).

### Environment

* Exaile Version: exaile-3.4.3-1.el7 (from package installer detail)

* Operating System and version: CentOS / 7.5.1804 (fully updated as of today - and - before exaile install)

GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LESSOPEN=||/usr/bin/lesspipe.sh %s
XDG_SESSION_TYPE=x11
QT_IM_MODULE=xim
LOGNAME=root
USER=root
HOME=/root
XDG_VTNR=1
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/root/bin
EXAILE_DIR=/usr/share/exaile
DISPLAY=:0
SSH_AGENT_PID=2475
LANG=en_US.UTF-8
TERM=dumb
SHELL=/bin/bash
XAUTHORITY=/run/gdm/auth-for-root-ba2o6p/database
SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/2301,unix/unix:/tmp/.ICE-unix/2301
SHLVL=1
QT_QPA_PLATFORMTHEME=qgnomeplatform
HISTSIZE=1000
WINDOWPATH=1
QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
IMSETTINGS_INTEGRATE_DESKTOP=yes
GIO_LAUNCHED_DESKTOP_FILE_PID=3561
USERNAME=root
IMSETTINGS_MODULE=none
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/exaile.desktop
XDG_RUNTIME_DIR=/run/user/0
SSH_AUTH_SOCK=/run/user/0/keyring/ssh
GDMSESSION=gnome-classic
XMODIFIERS=@im=none
GNOME_SHELL_SESSION_MODE=classic
XDG_MENU_PREFIX=gnome-
QT_GRAPHICSSYSTEM_CHECKED=1
XDG_CURRENT_DESKTOP=GNOME-Classic:GNOME
XDG_SESSION_ID=3
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-YxRYaLSoZo,guid=6998ff0ec6172d6a1c144f095ac41f77
KDEDIRS=/usr
DESKTOP_SESSION=gnome-classic
HOSTNAME=centos7.electrode.local
GDM_LANG=en_US.UTF-8
HISTCONTROL=ignoredups
XDG_DATA_DIRS=/usr/share/:/root/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/
PWD=/root
MAIL=/var/spool/mail/root
XDG_SESSION_DESKTOP=gnome-classic
XDG_SEAT=seat0

**Commandline:**
/usr/bin/python2 /usr/share/exaile/exaile.py --datadir=/usr/share/exaile/data --startgui

**Full Backtrace:**
subprocess.py:1327:_execute_child:OSError: [Errno 2] No such file or directory

```
Traceback (most recent call last):
  File "/usr/share/exaile/exaile.py", line 85, in <module>
    main()
  File "/usr/share/exaile/exaile.py", line 82, in main
    exaile = main.Exaile()
  File "/usr/share/exaile/xl/main.py", line 164, in __init__
    from xl.version import __version__
  File "/usr/share/exaile/xl/version.py", line 49, in <module>
    revision = get_current_revision(xdg.exaile_dir)
  File "/usr/share/exaile/xl/version.py", line 43, in get_current_revision
    'git', 'rev-parse', '--short=7', 'HEAD'
  File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Local variables in innermost frame:
errread: None
c2pread: 8
gc_was_enabled: True
errwrite: None
shell: False
errpipe_write: 11
to_close: set([8])
close_fds: False
self: <subprocess.Popen object at 0x1aa8c90>
env: None
cwd: None
child_exception: OSError(2, 'No such file or directory')
args: ['git', 'rev-parse', '--short=7', 'HEAD']
executable: 'git'
c2pwrite: 9
data: 'cexceptions\nOSError\np0\n(I2\nS\'No such file or directory\'\np1\ntp2\nRp3\n(dp4\nS\'child_traceback\'\np5\nS\'Traceback (most recent call last):\\n  File "/usr/lib64/python2.7/subprocess.py", line 1282, in _execute_child\\n    os.execvp(executable, args)\\n  File "/usr/lib64/python2.7/os.py", line 344, in execvp\\n    _execvpe(file, args)\\n  File "/usr/lib64/python2.7/os.py", line 380, in _execvpe\\n    func(fullname, *argrest)\\nOSError: [Errno 2] No such file or directory\\n\'\np6\nsb.'
creationflags: 0
errpipe_read: 10
preexec_fn: None
p2cread: None
startupinfo: None
p2cwrite: None
_close_in_parent: <function _close_in_parent at 0x1af7ed8>
universal_newlines: False
```

**Comment by sjohannes** [comment]
This bug was fixed in 3.4.4. You can fix it manually by [making this small change](https://github.com/exaile/exaile/commit/bcaec43b11d69287ba0f6fea1a6077d89ada9ce2) to `/usr/share/exaile/xl/version.py`.

**Comment by genodeftest** [comment]
Anyway, running a GUI application like exaile as root is a horrible idea. Neither exaile nor most of the libraries it uses (especially Gtk+ and WebKit2) are designed to be run as root.

If having a root user on login screen (GUI) is the default on CentOS, I recommend you switch distros. Nobody with knowledge of security would do that.

**Comment by humantex** [comment]
@sjohannes ....
Thanks for the pointer to the fix. Running fine in under 30 seconds.

@genodeftest ...
The anecdotal comment on running as root wasn't the reason for my post obviously, since the issue and error was presented to any logged in user - on an in-house, sandboxed VM on a walled private network.

As a 35+ year admin I'm guessing I started logging in as root from a time before you were born, and have passed through far more security audits than you've had birthdays. Be that as it may... Please don't presume to have an insight into my or anyone's test environment or what their knowledge or experience level might be and then chide them for some off-handed remark made when actually taking the time to make a detailed issue report to help advance a FOSS project. I'd suggest being helpful instead, but that's just me.
