### ISSUE TITLE
Can't pin Exaile to taskbar / No application icon

### ISSUE THREAD

**Issue by X0rg** [exaile/exaile#524]
### Steps to Reproduce (for bugs)
1. Launch Exaile (`exaile.desktop` or `exaile` command; both same behaviour)
2. Right click to application in taskbar

### Expected Behavior
1. Ability to pin Exaile to taskbar
2. Display application icon

### Current Behavior
1. Can't pin Exaile to taskbar
2. No application icon

![Screenshot](https://user-images.githubusercontent.com/2873785/42242242-850db550-7f0d-11e8-951b-43ccc3ca87ce.png)

If I add Exaile to favourite from GNOME Activities, and then I start Exaile from new favourite, it's not better:
![Screenshot](https://user-images.githubusercontent.com/2873785/42243450-af612e96-7f11-11e8-820b-5bef4585ccc2.png)

### Environment
* Operating System and version: Arch Linux x86_64 (rolling release)
* Exaile Version: **4.0.0-rc1**
* GTK version: 3.22.30
* Python version: 2.7.15
* Desktop environment: GNOME 3.28.2, with [Dash to Panel ](https://extensions.gnome.org/extension/1160/dash-to-panel/) extension

**Comment by genodeftest** [comment]
Did you run `make install`? If yes, did you get any warnings or error messages?

It looks like the GNOME shell is unable to locate the .desktop file in the "standard" directories like `/usr/share/applications` or `~/.local/share/applications`. Can you please check where the .desktop file is placed on your computer and post the path?

Based on the way how gnome-shell is designed, the "Expected behavior" cannot work without installing Exaile through `make install` or a software package manager.

Also, something may be wrong with the application ID, but I cannot reproduce this.

**Comment by X0rg** [comment]
I had a similar issue in another GTK application (C bindings), and using [gtk_window_set_icon](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-icon).
With PyGTK, I guess the equivalent is [gtk.Window.set_icon_from_file](https://developer.gnome.org/pygtk/stable/class-gtkwindow.html#method-gtkwindow--set-icon-from-file).

**Comment by virtuald** [comment]
Heh, I guess I never install exaile formally, nor do I use the favorites panel much, so I never noticed this. However, it occurs on my GNOME desktop in Fedora. I'll see if I can fix it.

**Comment by virtuald** [comment]
This seems to be an issue with the .desktop file, not something the application can set from inside the program... referring to https://gitlab.gnome.org/GNOME/gnome-shell-extensions/issues/10

Oddly enough, when I hit the `<super>` key and type 'Exaile', the icon for Exaile shows up there. However, doesn't show it in the taskbar thing. I played with it a bit (including calling `Gtk.Window.set_icon_from_file`), and I've no idea why it doesn't work.

If you figure it out, we'd be happy to modify the Makefile + icon installs to go to the right place.

**Comment by virtuald** [comment]
This seems vaguely useful (https://blogs.gnome.org/mclasen/2016/11/15/help-my-app-icon-is-missing/)... when I launch the app and look at it in `lg`, it shows the application as being 'untracked'. Perhaps because we use a shell script to launch exaile?

**Comment by virtuald** [comment]
Taking advice from https://github.com/laurent22/joplin/issues/86, it seems like setting `StartWMClass` in the exaile.desktop file fixed the issue. Not sure if that's a good long term fix, but works for me!

**Comment by X0rg** [comment]
Yes, I can confirm 914c71e fix this issue.
Thank you very much.
