### ISSUE TITLE
Collection panel display is garbled

### ISSUE THREAD

**Issue by pastk** [exaile/exaile#527]
Please see the screenshot. Items in the list overdraw each other when mouse cursor is hovering over them or when scrolling the list.

![exaile4 0 0-rc1_garbled_list](https://user-images.githubusercontent.com/18434508/42673611-597c829e-86c0-11e8-91d8-272c9c916aea.png)

Exaile 4.0.0-rc1 installed from sources.
Lubuntu 18.04.

I've upgraded to Lubuntu 18.04 recently from Lubuntu 16.04 where I had Exaile 4.0.0-beta3 and the issue didn't exist back then.

Please let me know if you need lib versions etc. or any other info.

**Comment by sjohannes** [comment]
Could you try a different GTK+ theme (Adwaita will do)? IIRC this is <https://github.com/exaile/exaile/issues/362>, which happens because we use a rarely-used GTK+ feature that a lot of themes didn't properly support.

**Comment by pastk** [comment]
You're right, I've changed to the Clearlooks widgets and the issue disappered, thanks!

**Comment by pastk** [comment]
Reported upstream as https://bugs.launchpad.net/lubuntu-artwork/+bug/1781689

**Comment by genodeftest** [comment]
@pastk : Thanks for reporting, checking back and reporting it upstream!
