### ISSUE TITLE
Playback issues (unified)

### ISSUE THREAD

**Issue by Entropy0** [exaile/exaile#53]
Since I was recently forced to try out unified (https://github.com/exaile/exaile/issues/52) I noticed a strange bug with this playback engine:
Everything works fine until I try to manually skip a song or start one via doubleclick - this causes exaile to start skipping through every song in the playlist, sometimes playing a few seconds of them, sometimes not. In the rare cases it actually reacts to the stop-button it opens a banner saying
"Playback error encountered
streaming stopped, reason not-linked"
Alternatively some error about uridecode5 which, interestingly enough, doesn't want to reproduce right now so that I can copy its exact phrasing (it just always gives the above one).

On the commandline it gives the usual INFOs about what it does while starting/ playing a song until the error occurs, when it produces the attached log (those are only about 3 seconds until I start holding down ctrl+c; it just continues like this if I don't)

Once this error occurs exaile only sporadically reacts to keyboard interrupt, kill -15 etc - the only reliable way to end it is a kill -9.

(Since I seem unable to figure out how to attach a File in Github, here is the produced output: http://pastebin.com/gjY7tknx )

**Comment by virtuald** [comment]
I've seen this happen with the unified playback engine too.

**Comment by genodeftest** [comment]
Seems to be fixed with #128
