### ISSUE TITLE
Crashes when Preferences Dialog is open and song finishes in Windows

### ISSUE THREAD

**Issue by erflungued** [exaile/exaile#538]
Had the Preferences Dialog open when a song finished and Exaile crashed.
Reproducable.
Throws a Windows Event 1000 Application Error:
```
Faulting application name: exaile.exe, version: 0.0.0.0, time stamp: 0x5a2e9fe6
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x06795f10
Faulting process ID: 0x818
Faulting application start time: 0x01d440687ef747c3
Faulting application path: C:\Program Files (x86)\Exaile\exaile.exe
Faulting module path: unknown
Report ID: 44bd4577-c965-417f-92c4-e4040a8688a8
Faulting package full name: 
Faulting package-relative application ID: 

```
### Steps to Reproduce (for bugs)
1. Start a song (and to speed things up, advance the song to a few seconds before the end);
2. Open the Preferences Dialog from the Edit menu;
3. Wait for the song to finish and Exaile will crash.

### Environment
* Operating System and version:
`MS Windows 10 Pro, Version 10.0.17134`
* Exaile Version: 
```
4.0.0rc1
GStreamer: 1.14.1
GTK+: 3.22.30
Locale: English_Australia 1252
Mutagen: 1.40.0
PyGObject: 3.28.3
Python: 2.7.15

```

**Comment by sjohannes** [comment]
Does this still happen if you set Edit → Preferences → Playback → Audio Sink to DirectSound?

**Comment by erflungued** [comment]
Thanks @sjohannes . Changing audio sink from *Automatic* to *Direct Sound* fixes the problem.

**Comment by sjohannes** [comment]
This is related to #532 and #534, where the extremely buggy WASAPI GStreamer plugin is used in the auto/auto setup. We'll look into blacklisting this plugin in future versions (possibly with #533).
