### ISSUE TITLE
MP3 tags not read

### ISSUE THREAD

**Issue by sekoenig-de** [exaile/exaile#539]
MP3 tags not read

### Steps to Reproduce (for bugs)
Add folder to collection.

### Expected Behavior
Tags should be properly imported for all supported media files.

### Current Behavior
Tags for ogg and flac files work just fine, but all MP3 files show up without any tag information.

### Further information
* Probably not a problem with mutagen per se since other programs that use it (I tested puddletag) work without problems.
* Interestingly, if I edit the tag info within exaile, it shows up correctly afterwards.

### Environment
* Operating System and version: Debian testing (buster), x86_64
* Exaile Version: 4.0.0-rc2
* mutagen-1.41.1

**Comment by sekoenig-de** [comment]
Here is some additional/updated information:

* To be clear: the MP3 files show up in the collection after scanning, just without any track information.
* When I enable monitoring and then edit a tag within exaile, the information immediately disappears again...
*... except sometimes, apparently at random, it does not!  In such a case, if I then rescan the collection, I suddenly get all MP3 files with full info.  But that is not stable, if I scan again after restarting exaile, the problem is back.

**Comment by virtuald** [comment]
Sorry for missing this. Is this with all MP3 files, or just some? There are some MP3 files in https://github.com/exaile/exaile-test-files ... does it occur with those files also?

If it is specific to certain MP3 files, I'd be interested in obtaining them to try it myself. My collection is almost entirely MP3, and I haven't seen this issue.

**Comment by sekoenig-de** [comment]
Thanks for looking into this!

Yes, when the problem occurs, it misses all my MP3 files.  Only the few .ogg and .flac files I have are found then.

Since the instances where it somehow suddenly works were quite rare, and I currently have a working database, before I check the test files, could you tell me which files or folders in my home directory I need to back up in order to restore my database afterwards?

**Comment by virtuald** [comment]
You can use the `--all-data-dir` to specify a temporary directory to start a new collection in, so it won't touch your existing collection.

**Comment by sekoenig-de** [comment]
Ok, thanks, that's very convenient.

I can confirm the problem also occurs with the test files.  Sometimes the tags are read, sometimes not, and in that case only the MP3 files show up as "Unknown (filename)" in the collection whereas the others are displayed with the proper info.

I'd be happy to try help debuggin, if I can.  As far as I see, the reading just uses an ID3 base class specialized for MP3 and other types, so it seems strange that only MP3 would not work reliably.  Where in the code would I have to start looking to follow the process of reading the collection?

**Comment by sekoenig-de** [comment]
Ok, here's some speculation about what the problem might be:

1. As far as I can see, the behavior I described in my previous comment indicated that the _reverse_mapping attribute of the BaseFormat class is not properly initialized.

2. That, in turn, indicates that the classmethod _compute_mappings fails.

3. Now, according to my understanding of how the collection scanning works, it uses multiple threads.  My question is then, how is there not a race condition regarding the mapping computation?  This may be due to my lack of knowledge of OOP and multithreading in Python, but in C++ for example one would have to take some measures that ensure the initialization is done atomically and only once...

**Comment by virtuald** [comment]
Awesome. Thanks for digging in -- I could totally see a race condition happening. Some of Exaile's code is quite old, and was not very thread/race conscious. We've made great strides towards fixing those issues, but still things remain.

I'll take a look in a few minutes.

**Comment by virtuald** [comment]
It looks like the race is between lines 84 and line 92 -- as the check for the reverse mapping is first, but the second mapping matters also and for some objects it won't get set. I'll put in a fix, as it could affect any of the formats.

**Comment by virtuald** [comment]
Try out #547 and let me know.

**Comment by sekoenig-de** [comment]
I understand of course how easily this can happen, especially when updating older code :)

Unfortunately, when I try the version you pointed to, the problem is still there.  I double-checked that I am running the correct build, and again I mostly get corrupted scans.  Adding my hack from above and rebuilding then makes things work fine again...

I'll try to find some time later for further testing, but I have a question at this point: how do class methods and attributes interact with inheritance in Python?  I mean, when the ID3Format class inherits from BaseFormat, where all this is implemented, will it get its own method and _computed attribute?

**Comment by sekoenig-de** [comment]
Here's some further information which I hope will help:

* I added `print("Computing mappings for " + str(cls))` at the top of the _compute_mappings() method.

* Starting with an empty collection, when I add a new folder and scan it, all I see is:
`Computing mappings for <class 'xl.metadata._base.BaseFormat'>`
and the scan gives me all the mp3 files without tags

* If I add one of those MP3 files to the playlist *and clear the collection*, then on the next startup of exaile, I get a
`Computing mappings for <class 'xl.metadata.mp3.MP3Format'>`
right after "Loading main window...", and scanning a fresh collection then works fine.

* When the collection is not empty on startup, I do not get the MP3Format message, and then with a Collection Rescan I get the problem back.

**Comment by virtuald** [comment]
Starting with an empty collection, if I add `print("Computing mappings", cls)` to line 89 along with a print of the keys returned from get_keys_disk, I get the following output when I add the exaile-test-files repository to my collection without enabling monitoring or scan at startup:

```
INFO    : Scanning library: file:///home/virtuald/exaile-test-files
('Computing mappings', <class 'xl.metadata.mp3.MP3Format'>)
('Computing mappings', <class 'xl.metadata.flac.FlacFormat'>)
('Computing mappings', <class 'xl.metadata.ogg.OggFormat'>)
('Computing mappings', <class 'xl.metadata.wav.WavFormat'>)
('keys', ['__bitrate', '__length'])
INFO    : Scan completed: file:///home/virtuald/exaile-test-files
```

I'm not able to duplicate your issue at all with exaile-test-files (even on master), with various combinations of scanning/rescanning.

I don't see how it's printing out the BaseFormat message... it seems to me you have something rather strange in your installation (perhaps another version of Exaile hiding somewhere?). What versions of things do you have? I've got:

```
INFO    : Using Python 2.7.15
INFO    : Using PyGObject 3.28.3
INFO    : Using Locale en_US UTF-8
INFO    : Using Mutagen 1.41.1
INFO    : Using GStreamer 1.14.1
INFO    : Using GTK+ 3.22.30
```

... though, looking a bit harder, there is one place where an issue could be occuring. In `xl/metadata/__init__.py`, the `get_format` function has a line where if the formatclass is None, it returns BaseFormat. Can you do a `print locals()` at line 139 inside the if statement and see if that occurs at all?

**Comment by sekoenig-de** [comment]
My versions are the following:

`INFO    : Loading Exaile 4.0.0rc2...`
`INFO    : Using Python 2.7.15+`
`INFO    : Using PyGObject 3.30.1`
`INFO    : Using Mutagen 1.40.0`
`INFO    : Using GStreamer 1.14.2`
`INFO    : Using GTK+ 3.22.30`

The older Mutagen is the version that comes with my Debian installation.  I checked that installing 1.41.1 at the user level does not fix the problem.

I added the `print locals()` as requested and find that indeed it fires -- for a single midi file sitting in my collection.  Looking at the formats map, that is indeed supposed to happen, I assume because Mutagen does not support that type.

Removing the midi file from the scanned folder seems to fix the problem.  Could it be that if somehow compute_mappings() is called for BaseFormat early in the scan, it won't be called again for supported formats later in the scan?  In that case, a fix might be to skip the compute if formatclass is None.

Of course, that leaves the question of what is going on with the test files.  As I reported previously, I did observe the problem with those as well.  It was much rarer there, however, and I honestly cannot say right now if perhaps it only occured after I had first scanned my normal library (introducing the problem), removing those again, and then scanning the test files.  At least with that latter setup I can reproduce the issue quite well.  What puzzles me is that still it only affects the mp3 files then, the ogg and flac look fine...

**Comment by rokm** [comment]
The problem is that for unsupported formats (i.e., [```if formatclass is None```](https://github.com/exaile/exaile/blob/bb3b99309d23e086a02df198e718bd14928bb90a/xl/metadata/__init__.py#L138)), we directly instantiate a ```BaseClass```. This initializes an empty ```_reverse_mapping``` and sets it to ```BaseClass```. Consequently, any subsequent first-time instantiations of child classes will also inherit this empty ```_reverse_mapping``` and thus no format-specific mapping initialization is done. 

The issue can be emulated with the following toy example:
```python
class BaseClass:
    def __init__ (self):
        if not hasattr(self, 'name'):
            self.__class__.compute_class()

    @classmethod
    def compute_class (cls):
        if hasattr(cls, '_name_impl'):
            cls.name = cls._name_impl
        else:
            cls.name = None

class ChildClass1(BaseClass):
    _name_impl = 'Name_ChildClass1'

class ChildClass2(BaseClass):
    _name_impl = 'Name_ChildClass2'
```

Now consider the different orders of instantiations. First, instantiating both child classes before the base class,
```python
c1 = ChildClass1()
print(c1.name)

c2 = ChildClass2()
print(c2.name)

b = BaseClass()
print(b.name)
```
results in:
```
Name_ChildClass1
Name_ChildClass2
None
```
which is what we expect to happen.

On the other hand, instantiating base class first,
```python
b = BaseClass()
print(b.name)

c1 = ChildClass1()
print(c1.name)

c2 = ChildClass2()
print(c2.name)
```
results in 
```
None
None
None
```
because at time of instantiation of child classes, the field ```name``` that has been set by the base class instantiation is inherited by children as well.

Similarly, mixed order of instantiation,
```python
c1 = ChildClass1()
print(c1.name)

b = BaseClass()
print(b.name)

c2 = ChildClass2()
print(c2.name)
```
results in name being properly set for the child that is instantiated before the base class, while not for the one that is instantiated after it:
```
Name_ChildClass1
None
None
```

So going back to exaile, if the midi file is encountered first, the ```BaseClass``` instantiation will prevent proper initialization of ```_reverse_mapping``` for subsequent ```mp3.MP3Format``` instances, resulting in missing metadata. Interestingly enough, ```_reverse_mapping``` is also empty for ```flac.FlacFormat```, but that does not prevent the metadata from being extracted.

I guess the easiest solution is to prevent direct instantiation of ```BaseClass``` and creating a dummy proxy class for unsupported formats.
