### ISSUE TITLE
Code guidelines need to be updated to reflect Black preferences

### ISSUE THREAD

**Issue by rokm** [exaile/exaile#543]
The [Black](https://github.com/ambv/black) formatter seems to prefer one-line imports in the form of:
```python
from gi.repository import Gtk, Pango, GdkPixbuf
```
This is at odds with the [Code guidelines](https://exaile.readthedocs.io/en/stable/dev/code_guidelines.html), which state that preferred style shoud be:
```python
from gi.repository import (
    Gtk,
    Pango,
    GdkPixbuf
)
```

The guidelines should be updated to reflect the change in policy, because failing to meet formatting requirements results in CI check failures.

**Comment by virtuald** [comment]
The [latest code guidelines](https://exaile.readthedocs.io/en/latest/dev/code_guidelines.html) show the updated preferences already. Once a 4.0 release is done, then it'll switch over.
