### ISSUE TITLE
Progress bar doesn't appear with python-gi-cairo 3.30.1

### ISSUE THREAD

**Issue by Fanael** [exaile/exaile#544]
The progress bar doesn't appear on my system (Debian sid) after a `python-gi-cairo` upgrade to version 3.30.1. Rolling back to 3.28.3 makes it appear again.

The following error appears on stderr:
```
Traceback (most recent call last):                                             
  File "/opt/exaile/xlgui/widgets/playback.py", line 434, in do_draw              
    Gtk.ProgressBar.do_draw(self, context)                                             
TypeError: Expected cairo.Context
```

**Comment by sjohannes** [comment]
In `xlgui/widgets/playback.py`, could you try commenting out line 422 (`__gsignals__ = {'draw': 'override'}`)?

**Comment by Fanael** [comment]
Commenting out this line seems to fix the issue.

**Comment by Fanael** [comment]
Commenting it out works around the issue.

**Comment by Fanael** [comment]
I also added some print statements to see what `context` is:
```
<class 'gi.repository.cairo.Context'>
<cairo.Context object at 0x7fbec08a2808 (CairoContext at 0x563549612e90)>
```
So it seems to be an actual Cairo context, but GTK for some reason is not fine with it?

**Comment by virtuald** [comment]
Hm, that's strange that it's `gi.repository.cairo.Context`... should be `cairo.Context`, right?

**Comment by virtuald** [comment]
I think we need to figure out what the override thing does/doesn't do. It seems that in this case it doesn't actually do anything (perhaps a holdover from pygtk?). However, we seem to use the gsignals/override thing a quite a few places. There doesn't seem to be any docs about it however.

**Comment by rokm** [comment]
According to [old PyGTK docs](http://zetcode.com/gui/pygtk/signals/) it overrides the default/predefined signal handler connected to a signal (e.g., ```do_draw``` for ```draw``` signal). In GI, it still does the same thing, essentially calling [```g_signal_override_class_closure```](https://developer.gnome.org/gobject/stable/gobject-Signals.html#g-signal-override-class-closure) with the new closure being the method from the python class.

I suspect that in GI, this may not be necessary anymore because ```do_``` handlers are defined as virtual methods, so in python they are automatically overloaded when they are defined within a class.

On the other hand, adding the following import should probably fix/work-around the cairo issue:
```python
from gi import _gi_cairo
```

**Comment by sjohannes** [comment]
> I suspect that in GI, this may not be necessary anymore because do_ handlers are defined as virtual methods, so in python they are automatically overloaded when they are defined within a class.

Yeah I think that's probably it. [PyGObject bug 73][1] seems to indicate that `__gsignals__` itself is outdated. We used to need `__gsignals__` to create signals and override default signals handlers, but I don't think we need it anymore for overriding (it's done automatically for `do_*` methods), and to create new signals we're supposed to use the [`GObject.Signal`][2] decorator (which I've just discovered, along with [`GObject.Property`][3]).

[1]: https://gitlab.gnome.org/GNOME/pygobject/issues/73
[2]: https://pygobject.readthedocs.io/en/latest/guide/api/signals.html#GObject.Signal
[3]: https://pygobject.readthedocs.io/en/latest/guide/api/properties.html#GObject.Property
