### ISSUE TITLE
Unable to import playlist

### ISSUE THREAD

**Issue by dangmai** [exaile/exaile#55]
Hi, for some reason I can't import playlist with Exaile. Under Arch Linux with Exaile version 3.4.3, when I click on the Import Playlist button in the File menu, Exaile throws the following error:

```
Traceback (most recent call last):
  File "/usr/lib/exaile/xlgui/menu.py", line 88, in <lambda>
    lambda *e: get_main().controller.panels['playlists'].import_playlist()
AttributeError: 'Main' object has no attribute 'panels'
```

I also try to import on Windows (3.4.2) and nothing happens either, but I haven't checked whether it's the same error.

**Comment by virtuald** [comment]
Sorry about that, just a typo from when I updated the panels stuff last year, it's fixed in trunk now.

As a workaround, you can right click on the playlists panel contents, and access the 'Import Playlist' option there too. That one should work.
