### ISSUE TITLE
Windows: Moodbar breaks font rendering throughout Exaile

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#558]
1. Enable Moodbar (you need to have the Moodbar app itself).
2. Trigger font redraw by moving the mouse over some UI elements.

Now every character is a rectangle/tofu.

This is a new bug, probably since GTK+ 3.24.

I'm not putting this in the 4.0 milestone because I don't think many people use Moodbar on Windows (they have to compile it manually with MSYS), so I think it's ok to release with this broken.

**Comment by genodeftest** [comment]
That is a funny Gtk+ bug… I have seen it happen with other Gtk+ applications on Fedora some time ago (2…4 years).

**Comment by sjohannes** [comment]
Gone in current MSYS2 env (GTK+ 3.24.1, PyGObject 3.30.1).
