### ISSUE TITLE
No titles in an exported XSPF playlist

### ISSUE THREAD

**Issue by Schweineschwarte** [exaile/exaile#560]
If I want to export my playlist to a XSPF file, the file contains only:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<playlist version="1" xmlns="http://xspf.org/ns/0/">
```
But no more.

### Steps to Reproduce (for bugs)
1. start Exaile and have some titles in your playlist
2. go to the file and choose "export actual playlist" (in german "Aktuelle Wiedergabeliste exportieren")
3. choose on the bottom left file type and then XSPF-Playlist
4. click on save
5. open the saved XSPF playlist with an editor

### Expected Behavior
I expected, that the file contains the titles.

### Current Behavior
It contains no titles, only:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<playlist version="1" xmlns="http://xspf.org/ns/0/">
```

I can't find the Exaile log on my Linux system

### Possible Solution
-----

### Environment
* Operating System and version: openSUSE 15.0 64 bit with KDE/Plasma

* Exaile Version: 4.0.0beta3
GStreamer: 1.12.5
GTK+: 3.22.30
Locale: de_DE UTF-8
Mutagen: 1.40.0
PyGObject: 3.26.1
Python: 2.7.14

**Comment by sjohannes** [comment]
Thanks, I can confirm this.

```pytb
Traceback (most recent call last):
  File "/exaile/xlgui/widgets/dialogs.py", line 1059, in on_response
    export_playlist(self.playlist, path, options)
  File "/exaile/xl/playlist.py", line 175, in export_playlist
    provider.export_to_file(playlist, path, options)
  File "/exaile/xl/playlist.py", line 829, in export_to_file
    stream.write('  <title>%s</title>\n' % escape(playlist.name))
  File "/exaile/xl/common.py", line 1040, in write
    return self.stream.write(s)
TypeError: Item 0: Must be number, not unicode
```
