### ISSUE TITLE
artist names superpose in the library during mouse hover [Breeze theme bug]

### ISSUE THREAD

**Issue by Schweineschwarte** [exaile/exaile#562]
If I hover with my mouse over the library on the left site, at the beginning of a letter area, from top to down, the artist names superpose each other. If I don't start on the top, instead in the middle all is ok.

### Steps to Reproduce (for bugs)
1. start Exaile
2. add a folder to the library
3. go back to main window and wait until Exaile is ready
4. hover the mouse from beginning of a letter area from top to down

### Expected Behavior
I would expected no superpose.

### Current Behavior
The artist names superpose (see image)

![screenshot_20181007_005142](https://user-images.githubusercontent.com/12170903/46576527-18b7a500-c9cc-11e8-8cd1-93b96cce7f61.png)

### Possible Solution
unknown

### Environment
* Operating System and version: openSUSE 15.0 64 bit with KDE/Plasma
* Exaile Version: 4.0.0beta3
GStreamer: 1.12.5
GTK+: 3.22.30
Locale: de_DE UTF-8
Mutagen: 1.40.0
PyGObject: 3.26.1
Python: 2.7.14

**Comment by sjohannes** [comment]
This is a bug in several GTK+ themes which are missing support for GtkTreeView row separators (#362).

Do you happen to be using the Breeze theme? We [reported this](https://bugs.kde.org/show_bug.cgi?id=380291) to them a year ago but so far there is no response.

If you want to try fixing this in the theme CSS, [here is how it was fixed](http://bazaar.launchpad.net/%7Eubuntu-art-pkg/ubuntu-themes/trunk/revision/560) in Ambiance/Radiance.

**Comment by Schweineschwarte** [comment]
Yes, I use the breeze theme. If I change the GTK3 design from breeze to adwaita it works.
Thank you for this information!

**Comment by sjohannes** [comment]
OK I found the problem.

If you edit `/usr/share/themes/Breeze/gtk-3.20/gtk.css` and replace `seperator` with `separator` it should fix the bug....

**Comment by Schweineschwarte** [comment]
Very nice! That's works fine! :+1:

**Comment by virtuald** [comment]
Closing since it's not our bug (and a bug was filed upstream).
