### ISSUE TITLE
Windows: Files panel: Clicking the Home button should go to actual Windows homedir

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#569]
1. Show the Files panel.
2. Click on the Home button.

Expected: Goes to actual home directory, e.g. `C:\Users\user`.

Actual: Goes to the msys home directory, e.g. `C:\msys\home\user`.

**Comment by genodeftest** [comment]
Did you see the issue in a custom-built exaile or in a version from the installer? These may behave differently.

**Comment by sjohannes** [comment]
Hm, you're right, it only happens when I run Exaile from msys, not on the official build. I wonder why it differs.

**Comment by sjohannes** [comment]
Ah, I think it's because if I run Exaile from an msys console the `HOME` env var is set (to the msys homedir), which `os.path.expanduser('~')` prioritises. I think this is the correct behaviour because that's the whole purpose of `HOME`, though it can be confusing.
