### ISSUE TITLE
4.0.0rc1 progress bar not visible Ubuntu MATE 18.04

### ISSUE THREAD

**Issue by LePreSSCuRSeuR** [exaile/exaile#574]
Hi,

I'm using Ubuntu MATE 18.04.

I'm using Exaile but like the #412 and the #496 the progress bar isn't visible, I can click where the bar should be, it works, but I can see it.

The current time isn't visible too.

My case is really similar to #496 :+1: 

Terminal messages :
```
exaile 

(exaile.py:18924): Gtk-WARNING **: 16:03:13.607: Theme parsing error: gtk-widgets.css:3135:13: 'max-width' is not a valid property name

(exaile.py:18924): Gtk-WARNING **: 16:03:13.607: Theme parsing error: gtk-widgets.css:3136:14: 'max-height' is not a valid property name
INFO    : Loading Exaile 4.0.0rc1...
INFO    : Using Python 2.7.15+
INFO    : Using PyGObject 3.30.1
INFO    : Loading settings...
INFO    : Using Locale fr_FR UTF-8
INFO    : Using Mutagen 1.40.0
INFO    : Using GStreamer 1.14.4
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.24.1
INFO    : Loading plugins...
INFO    : Connected with notify server Notification Daemon (version 1.20.1) by MATE
INFO    : Supported spec version: 1.1
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
Traceback (most recent call last):
  File "/usr/lib/exaile/xlgui/widgets/playback.py", line 434, in do_draw
    Gtk.ProgressBar.do_draw(self, context)
TypeError: Expected cairo.Context

```

![exaile](https://user-images.githubusercontent.com/1826338/49687693-ef6be000-fb06-11e8-8a80-396f9d5f19a6.png)

However, I can see the time and the progressbar when I place my cursor on Exaile's icon in the notification area.
![noticiation](https://user-images.githubusercontent.com/1826338/49687602-8e8fd800-fb05-11e8-9e17-f4f7145d2af6.png)

![exaile_version](https://user-images.githubusercontent.com/1826338/49687600-859f0680-fb05-11e8-8e3a-b235d82f2340.png)

Unlike the other similar issues, the packages python-gi-cairo is installed :
![python_cairo](https://user-images.githubusercontent.com/1826338/49687625-0b22b680-fb06-11e8-9cb2-d2f903cecf06.png)

I don't know if it's linked, but my theme is a mix with Ambiant-MATE (Theme, Controls & Icons) and Dust (Window border).

Can you help me please ? Thank in advance

**Comment by genodeftest** [comment]
Hi @LePreSSCuRSeuR,

can you try with the default Gtk+ 3.x theme, Adwaita, please?

    (exaile.py:18924): Gtk-WARNING **: 16:03:13.607: Theme parsing error: gtk-widgets.css:3135:13: 'max-width' is not a valid property name

It looks like your Gtk+ theme is broken. You should file a bug against it.

**Comment by rokm** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/exaile/xlgui/widgets/playback.py", line 434, in do_draw
    Gtk.ProgressBar.do_draw(self, context)
TypeError: Expected cairo.Context
```

Rather than issue with the theme, this looks like #544, which should be fixed by 820d50d54f0180853bb85f4d2f98e0bcc3ea1e5c. @LePreSSCuRSeuR, can you try using 4.0.0-rc3 or git master?

**Comment by genodeftest** [comment]
@rokm : Thanks!

**Comment by LePreSSCuRSeuR** [comment]
Thanks to you @rokm by using the git master (which is the 4.0.0rc3)
![version](https://user-images.githubusercontent.com/1826338/49700128-f2d09b80-fbda-11e8-9ec9-d1fd1b8e5e6c.png)

And it works !
![exaile](https://user-images.githubusercontent.com/1826338/49700132-00862100-fbdb-11e8-9ffb-7621815b9b1a.png)

In fact, I don't really know how to Install a application without a .deb package or with apt from a repository.

So I found a RPM package on a website, convert it into a deb package with Alien and install it with Gdebi.

But by downloading the branch master and with the _make_ and  _make install_ commands, exaile was updated !

Thanks again !

@genodeftest : I know that there is an error for exaile with my gtk theme, but I don't know where I can file a bug...

P.S : Contrary to exaile.org, exaile isn't in Ubuntu's official repository...
