### ISSUE TITLE
Add comments to a song on the main player with a single/double click

### ISSUE THREAD

**Issue by phalgunlolur** [exaile/exaile#579]
It would be beneficial for me, if I can double click on the comments column for each song and add a comment.

Currently, I have to right-click each song, click on track properties, go to tag properties, scroll to the comments section and then add my comment. Which is okay for one or two songs, but if I'm adding multiple comments, it becomes a pain.

**Comment by virtuald** [comment]
This seems like a useful thing -- but it's inconsistent, isn't it? Why should the comment field be editable inline but nothing else is? Mind you, I'm not really sure I want all of the other fields to be editable, I'm just asking the question. What do other audio players do? 

I suspect the answer is that there are certain fields which users are expected to edit and could change; whereas things like Artist and Title probably should rarely (if ever) change? Which fields besides comment should be editable then? One that sticks out to me is the grouping field.

**Comment by virtuald** [comment]
iTunes seems to allow editing on all columns, so that seems good enough of a justification to extend to all columns.
