### ISSUE TITLE
Is grouping by album artist supported?

### ISSUE THREAD

**Issue by cpitclaudel** [exaile/exaile#58]
I've found a few references to this on Ubuntu forums, including a post suggesting that it is supported, but I can't find the relevant option in the latest master. There also seems to be an old patch on launchpad; I didn't test it.

Is there a way to group the left pane by Album Artist?

**Comment by virtuald** [comment]
I don't see the option either. If you link to the old patch, perhaps we can bring it in.

**Comment by cpitclaudel** [comment]
I was thinking of this 2010 bug discussion on exaile's [launchpad tracker](https://bugs.launchpad.net/exaile/+bug/135618)

The [patch](https://launchpadlibrarian.net/57296546/collection-album-artist.patch) itself is in [this post](https://bugs.launchpad.net/exaile/+bug/135618/comments/12).

**Comment by sbrubes** [comment]
Related: https://github.com/exaile/exaile/issues/414

**Comment by virtuald** [comment]
Fixed in #576, please try out Exaile 4 and let us know if this has been addressed for you.

**Comment by cpitclaudel** [comment]
Thanks!
