### ISSUE TITLE
Use "translator-credits" instead of "Unknown translator"

### ISSUE THREAD

**Issue by scootergrisen** [exaile/exaile#590]
Instead of using "Unknown translator" for translator names in the po files i suggest using "translator-credits":

Now:

    #. TRANSLATORS: Add your own name here. Separate translator names with newlines.
    #: ../data/ui/about_dialog.ui:25
    msgctxt "About dialog translator credits"
    msgid "Unknown translator"

The future (maybe):

    #. TRANSLATORS: Add your own name here. Separate translator names with newlines.
    #: ../data/ui/about_dialog.ui:25
    msgctxt "About dialog translator credits"
    msgid "translator-credits"

I see "translator-credits" being used in multiple other software.
Not sure if it is some kind of standard but translators can properly easy recognize it.

Also instead of writing Unknown translator in the about/contributor dialog  then maybe just dont write anything.

**Comment by fitojb** [comment]
Indeed, among software translated with gettext, `translator-credits` is common and most FOSS translators understand what it’s for and how to translate it appropriately. Right now, in some languages this string is translated literally.
