### ISSUE TITLE
Rename xdg.local_hack to something less misleading

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#591]
`xdg.local_hack` checks whether the `data` subdir exists in `$EXAILE_DIR`. There are three situations where this is the case:

* Running Exaile from source directory.
* Running Exaile from the official Windows package.
* Running Exaile from the official Mac package.

The name may lead people (such as myself) to think that it only checks for the first case, causing confusion like in #588.

I want to rename it to something else. The variable essentially checks whether Exaile is installed in an FHS-compliant location, so I'm thinking of changing it to `is_fhs_install` and flipping the logic and usage.

**Comment by luzip665** [comment]
Done with #792
