### ISSUE TITLE
Scrolling through tags and accidentally hovering over a tag cause tag to scroll and change unintetionally

### ISSUE THREAD

**Issue by sarosenb** [exaile/exaile#6]
When in the tags window and using a scroll wheel when the mouse hovers over a scrollable tag, such as BPM for a song, the value will change. By allowing this it can cause unintentional  changes to tags that are unnoticed by the user.

**Comment by genodeftest** [comment]
Gtk+ 3 removed this behavior. Try the 'gi' branch, you won't be able to reproduce this issue. This issue will be gone once Exaile 4.0 is released.

**Comment by sjohannes** [comment]
I tried this on the SpinButtons and ComboBoxes in the tag editor (with GTK+ 3.18) and it still happens. Anyway, I'm going to commit something that should disable scrolling on tag widgets.

I'm a bit wary to change default GTK+ behaviour, but I think this is the right thing to do.
