### ISSUE TITLE
Even more automation for release process

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#601]
Since we have Windows builds, it seems like Travis should push up linux dists also.

One thing that could be nice is if the `make` process automatically set the version based on the tag. That would save some effort too.

**Comment by X0rg** [comment]
> One thing that could be nice is if the make process automatically set the version based on the tag.

You mean change `major`/`minor`/`extra` in `xl/version.py` based on `TRAVIS_TAG`?
It requires to be committed from Travis CI, but the commit will be set after the tag (unless you untag and retag), right?

What about  CI/CD for macOS?

**Comment by virtuald** [comment]
GTK on OSX is unstable and crashes, so I don't want to make any releases there.

I'm thinking that the version file gets generated/edited during the dist process, so no commit would be necessary. For those using a direct git checkout, it's already deriving the version partially from git, why not go the rest of the way?

**Comment by X0rg** [comment]
> GTK on OSX is unstable and crashes, so I don't want to make any releases there.

Well, if Exaile is not shipped on macOS, do you plan to drop support for this OS?

> I'm thinking that the version file gets generated/edited during the dist process, so no commit/retag would be necessary. For those using a direct git checkout, it's already deriving the version partially from git, why not go the rest of the way?

I agree with you, it will work in these cases. But what if people take the auto-generated "Source code" archive (like https://github.com/exaile/exaile/archive/4.0.0-rc3.tar.gz)?
These archives don't come with `.git` directory, so the version will no be found in that case.

**Comment by virtuald** [comment]
Then it would be 'devel' or something like that?

**Comment by X0rg** [comment]
I have this: 939d915af38969a78b297d650c69ec3dcd6eaacb
But it breaks plugin_tool: https://github.com/exaile/exaile/blob/master/tools/plugin_tool.py#L60

If we use 'devel', then it will break the check for plugin version, is it not?

**Comment by X0rg** [comment]
@virtuald: Is there something wrong with #604?

**Comment by virtuald** [comment]
This is fixed thanks to @X0rg, final -rc coming after 614 is merged.

**Comment by X0rg** [comment]
Did everything go well when you tag the version 4.0.0-rc4? Or something else need to be fixed/improved?

What about signed assets?

**Comment by virtuald** [comment]
The automation worked wonderfully, thank you.

We've traditionally always signed releases, but I've never felt particularly strongly that it needed to be done, so I'm fine not doing it.
