### ISSUE TITLE
Update CDDB bindings (used for plugin "cd", part of python 3 migration) or port to musicbrainz

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#608]
We're currently using CDDB-py (known as python-cddb on some linux distributions) for retreiving CD metadata. This is the only remaining dependency except spydaap which is not available for python 3. This issue is related to #246.

CDDB-py:
* uses freedb.org servers
* http://cddb-py.sourceforge.net/
* https://sourceforge.net/projects/cddb-py/
* pro: very stable
* cons: last update in 2003, python 1/2 code plus native C library
* License: GPLv2

PyCDDB: 
* uses freedb.org servers
* http://pycddb.sourceforge.net/
* https://sourceforge.net/projects/pycddb/
* License: GPLv2
* requires discid (same author)
  * https://sourceforge.net/projects/discid/
  * http://discid.sourceforge.net/
  * License: GPLv2
  * cons: python code plus native C library
* untested by myself

libcddb:
* uses freedb.org servers
* http://libcddb.sourceforge.net/
* https://sourceforge.net/projects/libcddb/
* pro: still used in many distros
* con: native library, no bindings
⇒ no option

libdiscid:
* uses musicbrainz (most compatible with the rest of Exaile)
* official library by musicbrainz: https://musicbrainz.org/doc/libdiscid
* multi-platform
* still partially maintained
* bindings:
  * https://pypi.org/project/python-libdiscid/
  * https://pypi.org/project/discid/

cd-discid command line tool:
* no database connection
* http://linukz.org/cd-discid.shtml
* probably not ported to windows
⇒ no option

python-musicbrainzngs:
* pure python implementation
* https://pypi.org/project/musicbrainzngs/
* already used by Exaile

Our options:
1. port CDDB-py and/or PyCDDB to python 3. I would try to port the native code to python code too. Maintain it ourselves. In this case we may think about putting it into our own source tree as the license is compatible.
2. use bindings to libcddb. This solution is less flexible (uses native code) but probably the easier way to go.
3. use python bindings to libdiscid, reuse musicbrainzngs which we're using in the musicbrainzcovers plugin anyway.

**Comment by genodeftest** [comment]
I'd go for the last solution if that works out.

**Comment by sjohannes** [comment]
> 2. use bindings to libdiscid. This solution is less flexible (uses native code) but probably the easier way to go.
> 3. reuse musicbrainzngs which we're using in the musicbrainzcovers plugin anyway.

If I understand correctly, these go together. So we use libdiscid to get the disc ID, then use musicbrainzngs to [query MusicBrainz for the metadata](https://github.com/alastair/python-musicbrainzngs/blob/master/examples/find_disc.py). I like this option and I think it's the most modern one.

A potential problem here is that distros package different bindings: Arch has distid, Debian has python-libdiscid. But their APIs are pretty much identical so it shouldn't be an issue: [discid](https://python-discid.readthedocs.io/en/latest/usage/#basic), [python-libdiscid](https://github.com/sebastinas/python-libdiscid#usage).

**Comment by genodeftest** [comment]
Thanks for the comment. I've clarified option 2 and 3. and added 4. 

For the different bindings names: afaik python-musicbrainzngs is available on most platforms including Debian, Arch, FreeBSD, Fedora under the same name. It is pure python so there is no platform limitation. If needed, we can ship our own copy.

**Comment by genodeftest** [comment]
Thanks for the comment. I've clarified option 2 and 3. Seems like I didn't understand what's going on ;)

**Comment by sjohannes** [comment]
Oh, I see, you meant libcddb in the 2nd point. In that case, yeah, I agree that the 3rd option is what we should go for.

**Comment by genodeftest** [comment]
I have a somewhat working prototype: https://github.com/genodeftest/exaile/tree/replace-cddb-by-libdiscid

**Comment by ryneeverett** [comment]
This can be closed now that #824 is merged.
