### ISSUE TITLE
plugin audioscrobbler: AttributeError when restarting with plugin enabled

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#623]
When exaile starts with the `audioscrobbler` plugin enabled, it throws an `AttributeError`.

### Steps to Reproduce (for bugs)
1. Start exaile (latest version from git master, works on a fresh data dir)
2. enable plugin audioscrobbler
3. close/quit exaile
4. start exaile and have a look at the logging

### Expected Behavior
Start exaile just fine

### Current Behavior
Exaile fails to start.
```
ERROR   : Unhandled exception
Traceback (most recent call last):
  File "/path/to/exailexl/main.py", line 570, in __init__
    self.__init()
  File "/path/to/exailexl/main.py", line 753, in __init
    self.gui = xlgui.Main(self)
  File "/path/to/exailexlgui/__init__.py", line 111, in __init__
    self.main = main.MainWindow(self, self.builder, exaile.collection)
  File "/path/to/exailexlgui/main.py", line 102, in __init__
    'mainwindow-accelerators', self.accel_group
  File "/path/to/exailexlgui/accelerators.py", line 45, in __init__
    providers.ProviderHandler.__init__(self, providername, simple_init=True)
  File "/path/to/exailexl/providers.py", line 204, in __init__
    self.on_provider_added(provider)
  File "/path/to/exailexlgui/accelerators.py", line 56, in on_provider_added
    self.accelerators[(provider.key, provider.mods)] = provider
AttributeError: 'AcceleratorManager' object has no attribute 'accelerators'
```

Probable cause: the audioscrobbler plugin is being initialized during startup (when the plugin's enable() function is called) but it should be initalized later (on_gui_loaded or on_exaile_loaded)

**Comment by Qwerty-Space** [comment]
I also have this issue.

**Comment by virtuald** [comment]
Fixed in master.

**Comment by Qwerty-Space** [comment]
Sweet
Pushed to repos yet?

**Comment by genodeftest** [comment]
> Pushed to repos yet?

Yes, it's already in the git master.

**Comment by Qwerty-Space** [comment]
It's not on the AUR yet by the looks of it

**Comment by genodeftest** [comment]
> It's not on the AUR yet by the looks of it

Please contact the AUR maintainer for that.

**Comment by Qwerty-Space** [comment]
Okay, will mark as out of date

**Comment by X0rg** [comment]
@Qwerty-Space I think you misunderstood how the AUR works.
To flag a VCS package out-of-date is a nonsense in that case (see [this **Note** on the wiki](https://wiki.archlinux.org/index.php/Arch_User_Repository#Flagging_packages_out-of-date)), and "it is your responsibility to track AUR package updates".
When you invoke `makepkg` to build a VCS package, it fetches the latest commits automatically, ignoring the `pkgver` variable.
