### ISSUE TITLE
Exaile 3.4.4 doesn't start

### ISSUE THREAD

**Issue by l2212** [exaile/exaile#63]
While Exaile 3.4.3 did work fine with my PC (with Windows 8.1), 3.4.4 doen't start at all. If I try to open it, I can only see a black prompt window for an istant, then nothing. And that only the first time, if I try again not even the window appears.
Trying with "Exaile (debug)" that's what i get:

```
INFO    : Python: C:\Python27\python.exe
INFO    : Python arch: 64-bit
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
INFO    : GStreamer: C:\gstreamer-sdk\0.10\x86_64\

** (python.exe:1752): WARNING **: Trying to register gtype 'GMountMountFlags' as
 enum when in fact it is of type 'GFlags'

** (python.exe:1752): WARNING **: Trying to register gtype 'GDriveStartFlags' as
 enum when in fact it is of type 'GFlags'

** (python.exe:1752): WARNING **: Trying to register gtype 'GSocketMsgFlags' as
enum when in fact it is of type 'GFlags'
INFO    : PyGTK works
INFO    : Mutagen works
Traceback (most recent call last):
  File "exaile_win.py", line 115, in main
    exaile.main()
  File "C:\Program Files (x86)\Exaile\exaile.py", line 82, in main
    exaile = main.Exaile()
  File "C:\Program Files (x86)\Exaile\xl\main.py", line 164, in __init__
    from xl.version import __version__
  File "C:\Program Files (x86)\Exaile\xl\version.py", line 49, in <module>
    revision = get_current_revision(xdg.exaile_dir)
  File "C:\Program Files (x86)\Exaile\xl\version.py", line 43, in get_current_re
vision
    'git', 'rev-parse', '--short=7', 'HEAD'
  File "C:\Python27\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] Impossibile trovare il file specificato
```

The last line is in italian: "Impossibile trovare il file specificato" = "Unable to find the specified file"

**Comment by virtuald** [comment]
Interesting, once my computer restarts I'll try it over there. We did just change something related to that.

**Comment by virtuald** [comment]
@l2212 I'm not able to duplicate the error on my Windows 8.1 machine. Additionally, the code that's executing there should be catching `OSError` (see [this commit](https://github.com/exaile/exaile/commit/bcaec43b11d69287ba0f6fea1a6077d89ada9ce2)).

I wonder if it's a remnant of the previous install? Can you try to uninstall Exaile, then install it again?

**Comment by l2212** [comment]
@virtuald It doen't seems to wok. I uninstalled it, restarted the PC and re-installed it but it does the same thing. I also tried before using CCleaner to delete previous files or stuff like that (I don't know if that has even any sense, of course, I'm really not an expert) but again, nothing.

**Comment by virtuald** [comment]
Interesting. @sjohannes reported that he could also start Exaile on Windows 8.1 without any issues.

**Comment by virtuald** [comment]
So I've tried harder, and cannot reproduce this at all. What version of python do you have installed? You can find out by going to a command prompt and entering `C:\Python27\python.exe --version`, followed by the enter key.

**Comment by sjohannes** [comment]
Based on line numbers, it seems that the code that you have is still on 3.4.3. For example,

    File "C:\Program Files (x86)\Exaile\xl\version.py", line 49, in <module>
      revision = get_current_revision(xdg.exaile_dir)

is [line 49](https://github.com/exaile/exaile/blob/3.4.3/xl/version.py#L49) in 3.4.3 and [line 51](https://github.com/exaile/exaile/blob/3.4.4/xl/version.py#L51) in 3.4.4.

Could it be that you installed the wrong version? Or is Exaile's upgrade process broken?

**Comment by l2212** [comment]
I've installed Python 2.7.8. But the news are that after downloading the installer again and re-installing Exaile another time, somehow, now it works. I don't know what happened, i didn't change anything else. Probably there was really still some old file on my PC from the previous version. Thanks a lot guys!
