### ISSUE TITLE
Double-clicking on editable field doesn't trigger playback

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#633]
Double-click on a non-selected track. This has to be done on an editable field, e.g. title, *on the text itself* (not on an empty region).

This will just select the field and not play the track.

**Comment by virtuald** [comment]
At the moment, that's intended behavior. If you click on the empty area (as you note above), then it will play the song.

I suppose we could change it so that single click edits and double click plays? Would need to add the changes to the modified cell renderer.

**Comment by genodeftest** [comment]
On Windows, double-click opens a file, but two consecutive clicks with a timeout inbetween trigger renaming. I think this is something we may want.

**Comment by sjohannes** [comment]
It's really confusing right now because it's possible to double-click on a track and nothing happens.

> On Windows, double-click opens a file, but two consecutive clicks with a timeout inbetween trigger renaming. I think this is something we may want.

Yes, on Windows Explorer it's this way: double-clicking on a file will always launch it; single-clicking the name of a file *that is already selected* will trigger rename.

**Comment by virtuald** [comment]
It was mentioned to me that a different (related) bug is that currently it's not possible to edit a tag that doesn't exist for a given file.

**Comment by virtuald** [comment]
I finally understood what @sjohannes meant in this issue's description.

I'm debugging this at the moment, and it seems to be a GTK bug, as our function is returning a GtkEntry when the double click occurs. Going to dig a bit more.

**Comment by sjohannes** [comment]
To clarify a bit more (because I'm now confused by your comment re. GtkEntry): this report is about what happens when you double-click on a track that is not already selected:

1. Select Track A.
2. Double-click Track B on its title.

Expected: Track B is selected and starts playing.

Actual: Track B is selected.

(I should have used this format for the report in the first place.)

**Comment by virtuald** [comment]
Sorry for the confusion, caused by the confusion. :+1: 

When (2) occurs, our `CustomizedCellRendererText.do_start_editing` function is called, and falls through to `Gtk.CellRendererText.do_start_editing`, which returns a Gtk.Entry, which should cause editing to begin. However, as you've observed, nothing occurs.

Yes, I realize you want it to play instead of editing -- but it's weird that it's not doing that either.

**Comment by sjohannes** [comment]
Oh I see. If I change it back to `renderer = Gtk.CellRendererText` it does the same thing.

Looks like in this case `EditableColumn.on_editing_started` gets called but probably cancelled immediately.

**Comment by virtuald** [comment]
Something else seems to be grabbing the focus, which clears the editing.

**Comment by virtuald** [comment]
Ah yes, in `Playlist::do_button_press_event`, we are grabbing focus. Introduced in 8b628b2a0ab82bd93598a2550651604facf49b82... I think it can be removed.

By removing that, at least now the behavior is consistent.

**Comment by sjohannes** [comment]
So back to the issue of not playing, I think the root of the problem is that GTK triggers the cell editing first before checking for double click.

One way to get around this is to set editable=false and only trigger editing on our own terms (e.g. somehow distinguish single click from double-click, or maybe on pressing F2 like in Nautilus).

To trigger editing on a particular cell when editable=false:

```py
path, column = treeview.get_cursor()
if path:
    cell = column.get_cells()[0]
    cell.props.editable = True
    treeview.set_cursor_on_cell(path, column, cell, start_editing=True)
    # TODO: Set editable back to False when finished editing
```

**Comment by sjohannes** [comment]
Here's an implementation of what I suggested in the last comment; what do you think?

https://github.com/exaile/exaile/compare/master...sjohannes:tracklist-cell-edit-with-f2

You need to click the cell first, then press F2. This also fixes the issue with not being able to edit a tag unless there is already a value in the cell. Another nice thing is that if you want to edit multiple tracks/tags you can navigate between cells with the arrow keys and F2 to edit.

**Comment by virtuald** [comment]
It works pretty well. I'm not a huge fan, but it does address the issue.

I'm not sure why I don't like it. I guess it doesn't seem very discoverable, but F2 is a pretty standard renaming hotkey, and click to edit isn't very obvious either.

**Comment by virtuald** [comment]
Discussing with my wife (a very non-technical person), her first impulse when asked to rename the title of a track was to right click on the title and look for a menu option 'Rename'. Second impulse was clicking on the title. Didn't realize F2 was a shortcut key for renaming things.

**Comment by sjohannes** [comment]
Yeah, my biggest reservation with this is that F2 is not discoverable, and we currently don't even have a way to show it in the Shortcuts dialog. But it's the closest thing I can think of to implement this inline tag editing feature while keeping the double-click behaviour consistent.

On a related note, we also have a few other shortcut keys that are in the same boat (Q to queue, Alt+Up/Down to reorder). They are defined/handled in `PlaylistView.on_key_press_event` and are not displayed in our Shortcuts dialog (which only shows app-wide shortcuts).
