### ISSUE TITLE
Exaile icon is incorrect on KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [exaile/exaile#653]
### Steps to Reproduce (for bugs)

1. start KDE Plasma Wayland session
2. open exaile
3.
4.

### Expected Behavior

Both the title bar and the task switcher (alt+tab menu) show Exaile icon.
### Current Behavior

We can see a Wayland generic icon in the title bar and when we press alt+tab.
### Possible Solution

maybe this link can help you
https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon
### Environment

* Operating System and version:
Arch Linux running KDE Plasma 5.16.3 desktop environment on Wayland

* Exaile Version: 4.0.0

![exaile](https://user-images.githubusercontent.com/15967631/61578390-94eb2700-aacc-11e9-902c-3b0da44ad8f2.png)

**Comment by sjohannes** [comment]
I couldn't figure out the problem. I've tried renaming the desktop file to `org.exaile.Exaile.desktop` and moving the icon to /usr/share/icons/...; it didn't work.

GNOME Terminal has the same issue, but MATE Terminal doesn't, and I didn't notice anything particularly different about their desktop files.

**Comment by glaubersm** [comment]
gtk CSD windows (gnome terminal, for example) are affected by a gtk bug - read the comment 4 in the following bug report please
https://bugs.kde.org/show_bug.cgi?id=409967

I think that maybe Exaile is affected by app_id vs .desktop file name issue pointed by David Edmundson in the same bug report.

**Comment by rokm** [comment]
As per the linked comment above, the app_id is indeed ```exaile.py``` and it does not match the name of the .desktop file:
```
[rok@vm-fedora30 ~]$ WAYLAND_DEBUG=1 exaile |& grep set_app_id
[2416573,053]  -> xdg_toplevel@24.set_app_id("exaile.py")
[2416860,794]  -> xdg_toplevel@32.set_app_id("exaile.py")
```

Renaming ```exaile.desktop``` to ```exaile.py.desktop``` does fix the issue.

But changing the program name using ```glib_set_prgname``` in ```exaile.py``` also seems to do the trick (not sure if there are any other side effects, though):
```python
#...
os.environ['EXAILE_DIR'] = basedir

from gi.repository import GLib
GLib.set_prgname('exaile')

def main():
#...
```
```
[rok@vm-fedora30 ~]$ WAYLAND_DEBUG=1 exaile |& grep set_app_id
[2442290,363]  -> xdg_toplevel@24.set_app_id("exaile")
[2442526,272]  -> xdg_toplevel@32.set_app_id("exaile")
```
And the icon shows correctly without having to rename the .desktop file.

**Comment by virtuald** [comment]
My inclination would be to use GLib.set_prgname, that seems more correct.

**Comment by sjohannes** [comment]
`Main.__init__` is a good place for this; it already contains similar calls to `Gdk.set_program_class` and `GLib.set_application_name`.

**Comment by rokm** [comment]
If I put the ```GLib.set_prgname('exaile')``` to ```xlgui/__init__.py``` (where the ```Gdk.set_program_class``` and ```GLib.set_application_name``` are), then the splashscreen "window" has app_id ```exaile.py``` while the application window has app_id ```exaile```. 

Consequently, the main window has correct icon, while the splash screen does not. Considering the splashscreen is not shown for a very long time, is that acceptable?

**Comment by sjohannes** [comment]
I see; in that case, maybe `xl.main.Exaile.__init`? The other calls could probably move there as well. Doesn't really matter though.
