### ISSUE TITLE
RuntimeErrors on startup and on focus when moodbar plug enabled.

### ISSUE THREAD

**Issue by bitterjug** [exaile/exaile#66]
I get the following output when I start exaile with Moodbar plugin enabled. I'm working on making Moodbar work on the Preview Device, which is how I noticed this; but the following output is from the master 3.4.4 relase version. I'd like to find where these are coming from but I don't know how to proceed.  Shouldn't there be a message along with those runtime errors?
```
~/workspace/exaile➔ ./exaile  --version
Exaile 3.4.4+fa51379
~/workspace/exaile➔ ./exaile
INFO    : Loading Exaile 3.4.4+fa51379 on Python 2.7.6...
INFO    : Loading settings...
INFO    : Using en_GB UTF-8 locale
INFO    : Loading plugins...
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Using GTK+ 2.24.23
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
/home/marks/workspace/exaile/xl/main.py:327: Warning: unable to set property 'rating' of type 'gint' from value of type 'gchararray'
  self.gui.main.window.show_all()
/home/marks/workspace/exaile/xlgui/__init__.py:77: Warning: unable to set property 'rating' of type 'gint' from value of type 'gchararray'
  gtk.main()
RuntimeError
RuntimeError
RuntimeError
RuntimeError
RuntimeError
RuntimeError
```
Starting exaile gives me half a dozen of these. Switching window focus (alt-tab) from the termina, back to exaile and back to the terminal again, adds another six, and so on.  

 There are, of course, also the `gchararray` errors, but these seem to be coming from Exaile core.

**Comment by sjohannes** [comment]
Yeah, I've noticed those as well. Not sure yet where it comes from.

**Comment by bitterjug** [comment]
```
Original exception was:
RuntimeError: maximum recursion depth exceeded
```
I've tried tinkering with `sys.excepthook`, but doesn't give any more info. Not even sure why I got the above on a different machine. Tried removing the try-catch block in xl/main/Exaile.__mainloop. I'm feeling like a bit of a blunt instrument.

**Comment by bitterjug** [comment]
I noticed @virtuald  talking about [badness arising from threading and UI widgets](https://github.com/exaile/exaile/issues/67#issuecomment-98949335). I know Dustin doesn't use the moodbar; I'd like to try and track down the problem but really don't know how to find the source of the exception because the stack trace isn't being propagated. Any pointers to help me get started?

**Comment by sjohannes** [comment]
The [PyGTK FAQ] has some ideas for catching errors that don't cause crashes, but it also involves `sys.excepthook`, which you've tried. Are you able to get a stack trace from the exception hook?

**Comment by virtuald** [comment]
@bitterjug you might try the --debug flag for exaile...

**Comment by sjohannes** [comment]
Heh, I found the cause of this while doing something completely unrelated (porting to GTK+ 3 and trying to work around some other event-related issues).

The issue is not in the Moodbar plugin itself but rather in Exaile's SeekProgressBar, which the Moodbar replaces. The problem happens when the SeekProgressBar is detached from the main window&mdash;it then reconnects the focus-out-event signal to the wrong object. More info in the linked commit.

**Comment by bitterjug** [comment]
Excellent, thanks!

While looking into this, I discovered the Marker feature on the seek progress bar. Pretty cool. But, I guess, not quite polished, as they stick around when you change tracks. 

Reminds me; I'd love a GUI way to set a track's StartOffset and Stop Offset. And, of course, I want to do this with the help of the Moodbar waveform view (e.g. to see where the talking stops and the music begins). I'm wondering about re-implementing the moodbar as a background layer for the progress bar. The progress bar widget, however, appears to draw its own opaque background (maybe it can be made transparent through styling?). So maybe it would entail creating a new widget that behaves like the current default progress bar, and building the seek progress bar on top of that, perhaps using mixin/multiple inheritance. What do you think?

**Comment by virtuald** [comment]
Feel free to add polish to anything that needs polishing. ;)

There's a way to set the start/stop offset in the track properties (I assume you've found it already?), but you're right that it would be nice to have some other way of doing this.

Your idea sounds pretty cool. Just make sure that when you do it, to do it in a way that won't be too hard to move to GTK3, as it looks like we're moving there in the very near future (or better yet, help out with the GTK3 efforts :) ).
