### ISSUE TITLE
Sorting by track number is broken on the python 3 branch

### ISSUE THREAD

**Issue by Fanael** [exaile/exaile#661]
I understand that the python 3 port is still very much work in progress, but I tried it nonetheless and it works almost perfectly for me already, there is just a single issue that I've noticed.

### Steps to Reproduce (for bugs)
1. Add some album to the playlist.
2. Sort the playlist by the track number.

### Expected Behavior
10 should be sorted after 9.

### Current Behavior
10 appears between 1 and 2.

### Possible Solution
Sort track numbers as numbers, not lexicographically as strings.

### Environment
Commit b8454f747e94a6f29f240dbb47af32cf3cc362d4
GStreamer: 1.16.1
GTK+: 3.24.12
GTK+ theme: Breeze-gtk
Locale: pl_PL UTF-8
Mutagen: 1.40.0
PyGObject: 3.34.0
Python: 3.7.5

**Comment by Fanael** [comment]
Reverting 237eacc1e81bd81688aec607a87806618689ea39 makes this problem go away.

**Comment by rokm** [comment]
Thanks for the report! As you noticed yourself, this issue was introduced by 237eacc, which I have reverted now.
