### ISSUE TITLE
Add a way to easily add current played song to playlist

### ISSUE THREAD

**Issue by brunetton** [exaile/exaile#662]
Hi,
I'm using Exaile for a couple of hours and I'm creating playlists. First impression is very good ! Very pluggable, simple and clean. I love it ! 
But I've the global feeling that it's quite or impossible to "find" the track I'm listening to; to add it to playlist(s):

- as soon as a track is started to being played, it dissapears from Queue
- if I didn't started the play action from an existing playlist, `view -> show playing track` option is useless, nothing happens

### Current Behavior
- add some tracks in queue from collection
- double-click on a track to play it
- try to find this track to add to a playlist

### Possible Solution
I see two simple solutions for this problem:

1. keep playing track in the queue (like the most part of players I've tried) 
  - and remove it only when the track finished
  - or display it in gray at the top of queue
2. add a way to drag & drop current track to playlist from the top part of the app (where the album cover is displayed, and the track name is displayed in big)

I think the two could be implemented:
- keep playing track in the queue is a solution to always find the current track by invoking `view -> show playing track`: this could simply focus/show queue
- being able to drag & drop current track to playlist from the top part of the app could be a simple way to always find a way to drag & drop current track, always from the same location (whatever the state of playlists panels is)

### Environment
* Operating System and version:
Arch Linux

* Exaile Version: 
4.0.0

**Comment by virtuald** [comment]
Hi @brunetton, we're happy you find Exaile useful!

There is currently already an option to ensure that tracks don't disappear from the queue:

* Edit -> Preferences
* Under "Playback", there is an option "Remove track from queue upon playback", make sure it's unchecked.

Hope that helps!
