### ISSUE TITLE
Error importing playlist (GLib.Error: g-io-error-quark: Operation not supported (15))

### ISSUE THREAD

**Issue by charlesdaniels** [exaile/exaile#664]
#612 # Steps to Reproduce (for bugs)

1. Open exaile
2. Select any radio stream from the left bar/pane

### Expected Behavior

The stream should begin playing

### Current Behavior

The stream does not play.

Note that I have tested playback of local files (in this case, some OGG/Vorbis files), and they played no problem.

It is certainly possible that the SlackBuild is wrong, or something about Slackware is confusing Exaile somehow (such as a library in the wrong place).

Here is the terminal output when said behavior occurs:

```
INFO    : Loading Exaile 4.0.0...
INFO    : Using Python 2.7.17
INFO    : Using PyGObject 3.18.2
INFO    : Loading settings...
INFO    : Using Locale en_US UTF-8
INFO    : Using Mutagen 1.43.0
INFO    : Using GStreamer 1.6.4
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.18.9
INFO    : Using GTK+ theme Adwaita
INFO    : Loading plugins...
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
ERROR   : Error importing playlist
Traceback (most recent call last):
  File "/usr/local/share/exaile/plugins/somafm/__init__.py", line 185, in _get_playlist
    self.playlists[playlist_id] = playlist.import_playlist(url)
  File "/usr/local/lib/exaile/xl/playlist.py", line 135, in import_playlist
    return provider.import_from_file(path)
  File "/usr/local/lib/exaile/xl/playlist.py", line 522, in import_from_file
    with GioFileInputStream(gfile) as stream:
  File "/usr/local/lib/exaile/xl/common.py", line 996, in __init__
    self.stream = Gio.DataInputStream.new(gfile.read())
Error: g-io-error-quark: Operation not supported (15)
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xlgui/panel/radio.py", line 289, in on_row_activated
    self.emit('playlist-selected', item.get_playlist())
  File "/usr/local/share/exaile/plugins/somafm/__init__.py", line 211, in <lambda>
    url, playlist_id
  File "/usr/local/share/exaile/plugins/somafm/__init__.py", line 191, in _get_playlist
    return self.playlists[playlist_id]
KeyError: 2
Traceback (most recent call last):
  File "/usr/local/lib/exaile/xlgui/panel/radio.py", line 289, in on_row_activated
    self.emit('playlist-selected', item.get_playlist())
  File "/usr/local/share/exaile/plugins/icecast/__init__.py", line 312, in <lambda>
    ]: self._get_playlist(name, station_id)
  File "/usr/local/share/exaile/plugins/icecast/__init__.py", line 191, in _get_playlist
    self.playlists[station_id] = playlist.import_playlist(url)
  File "/usr/local/lib/exaile/xl/playlist.py", line 135, in import_playlist
    return provider.import_from_file(path)
  File "/usr/local/lib/exaile/xl/playlist.py", line 868, in import_from_file
    with GioFileInputStream(Gio.File.new_for_uri(path)) as stream:
  File "/usr/local/lib/exaile/xl/common.py", line 996, in __init__
    self.stream = Gio.DataInputStream.new(gfile.read())
GLib.Error: g-io-error-quark: Operation not supported (15)
```

### Environment

* Operating System and version: Slackware 14.2

```
GStreamer: 1.6.4
GTK+: 3.18.9
GTK+ theme: Adwaita
Locale: en_US UTF-8
Mutagen: 1.43.0
PyGObject: 3.18.2
Python: 2.7.17
```

* Exaile Version: 4.0.0

Some more stuff that might be useful:

```
cad@kronos:~ > uname -a
Linux kronos 4.4.202 #2 SMP Sat Nov 16 14:16:42 CST 2019 x86_64 Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz GenuineIntel GNU/Linux
cad@kronos:~ > python --version
Python 2.7.17
cad@kronos:~ > locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
cad@kronos:~ > slackpkg search gstreamer

Looking for gstreamer in package list. Please wait... DONE

The list below shows all packages with name matching "gstreamer".

[ Status           ] [ Repository               ] [ Package                                  ]
   installed               multilib                     gstreamer-compat32-1.6.4-x86_64-1compat32
   installed               multilib                     gstreamer0-compat32-0.10.36-x86_64-1compat32
   installed               slackware64                  gstreamer-1.6.4-x86_64-1
   installed               slackware64                  gstreamer0-0.10.36-x86_64-1
   installed               slackware64                  phonon-gstreamer-4.8.2-x86_64-1
   installed               slackware64                  qt-gstreamer-1.2.0-x86_64-1

You can search specific files using "slackpkg file-search file".
```

I have also attached the SlackBuild file which I used to compile Exaile. This is just a shell script, for those unfamiliar.

[exaile.SlackBuild.txt](https://github.com/exaile/exaile/files/4007742/exaile.SlackBuild.txt)

Finally, I have also attached the output  produced by the SlackBuild when executed, in case this might provide some insight as to whether or not the build process has gone wrong.

[exaile_build_log.txt](https://github.com/exaile/exaile/files/4007743/exaile_build_log.txt)

**Comment by charlesdaniels** [comment]
I also went ahead and tested on Pop_OS 18.04 LTS (Which is essentially Ubuntu 18.04) and I was not able to re-produce.

Here are the versions that are displayed on Pop_OS on the console when Exaile is starting:

```
INFO    : Loading Exaile 4.0.0...
INFO    : Using Python 2.7.17
INFO    : Using PyGObject 3.26.1
INFO    : Loading settings...
INFO    : Using Locale en_US UTF-8
INFO    : Using Mutagen 1.38
INFO    : Using GStreamer 1.14.5
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.22.30
INFO    : Using GTK+ theme Pop-slim-light
INFO    : Loading plugins...
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
```

**Comment by rokm** [comment]
This looks like your Slackware installation is missing GVFS or ```http``` backend for GVFS, which results in an error when trying to open URL via GIO. 

Can you check if [```gvfs``` package](https://slackware.pkgs.org/14.2/slackware-x86_64/gvfs-1.26.3-x86_64-1.txz.html) is installed?

**Comment by charlesdaniels** [comment]
I do see `gvfs-1.26.3-x86_64-1` installed on my system. I have also tried installing gnome-vfs 2.24.4, but I think that's separate from gvfs.

I also see that `/usr/libexec/gvfsd-http` is a file that is present on my system.

[This](https://mirrors.slackware.com/slackware/slackware-14.2/source/l/gvfs/gvfs.SlackBuild) is the SlackBuild package for the official gvfs package distributed for 14.2. Notably, the `--disable-http` flag is not asserted.

**Comment by rokm** [comment]
Hmm, does the following shell command work?
```shell
gio cat "http://example.org"
```
Or the following python snippet?
```python
from gi.repository import Gio
print(Gio.File.new_for_uri("http://example.org").load_contents(None))
```

**Comment by charlesdaniels** [comment]
I don't seem to have a `gio` command? Is that supposed to be part of gvfs? 

The Python snippet had this output:

```
Python 2.7.17 (default, Oct 20 2019, 14:16:51)
[GCC 5.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gio
>>> print(Gio.File.new_for_uri("http://example.org").load_contents(None))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
GLib.Error: g-io-error-quark: Operation not supported (15)
```
I do have a `gvfs-cat` command though? Might that be related?

```
cad@kronos:~ > gvfs-cat "http://example.org"
gvfs-cat: http://example.org: error opening file: Operation not supported
```

A cursory Google search with any terms I could think of did not reveal anything useful.

**Comment by rokm** [comment]
Based on the above errors (```Operation not supported (15)```) this looks like an issue with ```gvfs```.

I am not familiar with Slackware enough to say what, though. I tried running the above snippets (python and gvfs-cat) in a fresh Slackware 14.2 installation in VM, but they worked as expected. 

Do you see any gvfs processes running? After I ran the above snippets, I see ```gvfsd```, ```gvfsd-fuse``` and ```gvfsd-http```.

**Comment by charlesdaniels** [comment]
```
cad@kronos:~ > ps aux | grep -i gvfs
cad      15191  0.0  0.0  10868  1872 pts/2    S+   11:37   0:00 grep -i gvfs
cad@kronos:~ > gvfs-cat "http://example.org"
gvfs-cat: http://example.org: error opening file: Operation not supported
cad@kronos:~ > /usr/libexec/gvfsd
^Z
[1]+  Stopped                 /usr/libexec/gvfsd
cad@kronos:~ > bg
[1]+ /usr/libexec/gvfsd &
cad@kronos:~ > gvfs-cat "http://example.org"
gvfs-cat: http://example.org: error opening file: Operation not supported
cad@kronos:~ > ps aux |grep -i gvfs
cad      15248  0.0  0.0 272896  6404 pts/2    Sl   11:37   0:00 /usr/libexec/gvfsd
cad      15254  0.0  0.0 336500  7196 pts/2    Sl   11:37   0:00 /usr/libexec/gvfsd-fuse /home/cad/.gvfs -f -o big_writes
cad      15323  0.0  0.0  10868  1884 pts/2    R+   11:37   0:00 grep -i gvfs
cad@kronos:~ > ls -lah ~/.gvfs
total 4.0K
dr-x------  2 cad users    0 Dec 30 11:37 .
drwx--x--x 36 cad users 4.0K Dec 30 11:27 ..
cad@kronos:~ > fg
/usr/libexec/gvfsd
^C
cad@kronos:~ > /usr/libexec/gvfsd-http
cad@kronos:~ >  > /usr/libexec/gvfsd-http
cad@kronos:~ > ps aux | grep -i gvfsd
cad      15418  0.0  0.0 272896  8500 ?        Sl   11:38   0:00 /usr/libexec/gvfsd
cad      15423  0.0  0.0 338748  6984 ?        Sl   11:38   0:00 /usr/libexec/gvfsd-fuse /home/cad/.gvfs -f -o big_writes
cad      15482  0.0  0.0  10868  1860 pts/2    S+   11:38   0:00 grep -i gvfsd
cad@kronos:~ > gvfs-cat "http://example.org"
gvfs-cat: http://example.org: error opening file: Operation not supported
```

In an (almost) completely clean VM (just Xorg and a few GUI programs installed), I see the same behavior (as I have previous reported). Did you perchance upgrade/update the packages in your VM before testing? I'm wondering if maybe this worked with the initial 14.2 release, but had a regression in an update?

It would appear that [gvfs has been upgraded several times in -stable](ftp://ftp.osuosl.org/pub/slackware/slackware64-14.2/ChangeLog.txt).

To see if this might be the case, try the following in your VM:

1. Un-comment the `mirrors.slackware.com` line in `/etc/slackpkg`
2. Run `slackpkg update`
3. Run `slackpkg upgrade-all`
4. Run `slackpkg clean-system`

Then reboot and test gvfs-cat again. If it stops working, then we can assume it's a regression either in gvfs and/or Slackware, otherwise it's something else.

**Comment by charlesdaniels** [comment]
I have tried building and installing gvfs-1.28.4 (the newest that supports the glibc version that Slackware ships with). This did not produce any noticeable effect.

I also tried building from the Slackware sources the version that was supposed to come with 14.2 (what I had installed originally), which also produced no effect.

I tried this with gvfs-1.16 (from Slackware 14.1), which also had no effect.

Interestingly, the whole thing can't be completely broken, since `gvfs-cat` works on local files. The "Operation not supported" error does appear for remote files via FTP though, in addition to HTTP.

**Comment by charlesdaniels** [comment]
Aha!

This seems to be a problem with how I have dbus configured somehow... 

I figured this out thanks to [this issue](https://bugzilla.redhat.com/show_bug.cgi?id=1184767).

```
cad@kronos:~ > sudo /etc/rc.d/rc.messagebus status
System dbus-daemon is running.
cad@kronos:~ > ps aux | grep dbus
message+  1188  0.0  0.0  19968  2676 ?        Ss   11:27   0:01 /usr/bin/dbus-daemon --system
cad       1459  0.0  0.0  35328  2436 ?        S    11:27   0:00 dbus-launch --autolaunch 001d7e96cb76e2dbb36dee3e5e02b5e1 --binary-syntax --close-stderr
cad       1460  0.0  0.0  19868  2628 ?        Ss   11:27   0:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
cad       3705  0.0  0.0  19736  2680 ?        S    12:41   0:00 /usr/bin/dbus-daemon --config-file=/etc/at-spi2/accessibility.conf --nofork --print-address 3
cad       5560  0.0  0.0  19736  2104 ?        Ss   12:46   0:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
cad       5682  0.0  0.0  19736  2176 ?        Ss   12:46   0:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
cad       5791  0.0  0.0  19736  2172 ?        Ss   12:47   0:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
cad       6379  0.0  0.0  10868  1952 pts/2    S+   12:49   0:00 grep dbus
cad@kronos:~ > gvfs-cat http://example.org
gvfs-cat: http://example.org: error opening file: Operation not supported
cad@kronos:~ > dbus-launch gvfs-cat http://example.org
<!doctype html>
<html>
<head>
    <title>Example Domain</title>
...
```

Additionally, launching Exaile with `dbus-launch exaile`, rather than running the command directly resolves the problem (note for future googlers: I also had to install `gst-plugins-ugly` and `gst-plugins-bad` from slackbuilds.org in order to get an MP3 codec).

I'm nor very familiar with how dbus works. Clearly, dbus is running, and it can't be *too* broken, since everything works at it should via `dbus-launch`.

I do notice however that `DBUS_SESSION_BUS_ADDRESS` gets set in my environment if I do `dbus-launch bash`. Perhaps running my desktop session through dbus-launch would be helpful?

**Comment by charlesdaniels** [comment]
I believe I have resolved the issue.

Apparently one's desktop session is supposed to be launched via `dbus-launch --exit-with-session`. So this was my fault for configuring my session incorrectly. 

So I guess there are no problems with dbus, gvfs, or Exaile, although I sure wish gvfs had a more helpful error message (like "could not connect to dbus, some features may not work") or something. That would have saved me a lot of time spent troubleshooting this issue.

This issue can be closed at your leisure. Sorry to waste your time on something that ultimately proved to be my fault. Exaile is the only program that has features that depend on dbus that I use, hence why I didn't notice this problem until trying to use Exaile.

**Comment by rokm** [comment]
Glad to hear you sorted it out! I didn't know that gvfs depended on dbus, either, so I learnt something new as well.
