### ISSUE TITLE
[py3] documentation generation is broken

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#667]
### Steps to Reproduce (for bugs)
1. Get the latest commits from `py3` branch
2. run `make check-doc` or `make -C doc html`

### Expected Behavior
Generate documentation or at least try to.

### Current Behavior
Aborts with this error message:
	Configuration error:
	There is a programmable error in your configuration file:

	Traceback (most recent call last):
	  File "/usr/lib/python3.7/site-packages/sphinx/config.py", line 361, in eval_config_file
		execfile_(filename, namespace)
	  File "/usr/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 86, in execfile_
		exec(code, _globals)
	  File "/path/to/exaile/doc/conf.py", line 46, in <module>
		mocks.fake_xl_settings()
	  File "/path/to/exaile/doc/mocks.py", line 81, in fake_xl_settings
		import xl.settings
	  File "/path/to/exaile/xl/settings.py", line 41, in <module>
		from xl.common import VersionError, glib_wait, glib_wait_seconds
	  File "/path/to/exaile/xl/common.py", line 748, in <module>
		class ProgressThread(GObject.GObject, threading.Thread):
	TypeError: __mro_entries__ must return a tuple

### Possible Solution
I think *someone* needs to go over the config for sphinx and probably redo it.

### Environment
Linux/Fedora with python3-3.7.6-1.fc31.x86_64 and python3-sphinx-2.1.2-2.fc31.noarch. I have also seen this with our ubuntu19.10 and debian10 docker images:
https://travis-ci.org/exaile/exaile/jobs/637118951
https://travis-ci.org/exaile/exaile/jobs/637118949

**Comment by rokm** [comment]
From what I can tell, this is caused by introduction of PEP 560 in python 3.7.

Our ```Mock``` implementation returns an instance of itself for ```__mro_entries__``` (default behavior), causing the error. Raising ```AttributeError``` seems to cause another error later on, but adding a ```__mro_entries__``` method that returns an empty tuple seems to do the trick.

However, as noted in the PR, I am not familiar enough with this area of python to be certain that there are not side effects.

**Comment by rokm** [comment]
Hmm, it seems the PR fixed the issue for pyhton 3.7.x but not for python 3.6.x - Ubuntu 18.04 is still failing, but with the ```metaclass conflict error``` that I've mentioned above.
