### ISSUE TITLE
Test data reading & upgrade when switching to Python 3

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#668]
We need to test that user data are correctly read and saved back (possibly upgraded) when first running the py3 branch using existing profile from Exaile 4.0.

From highest priority to lowest:

* Collection
* Settings (`settings.ini`) - `U` entries should change to `S`
* Manual playlists
* Tracklist tabs
* Smart playlists
* Covers

Anything else?

This should ideally be done before we merge py3 to master, to prevent data loss for people tracking master.

**Comment by genodeftest** [comment]
Some of the tests already happen in our test suite, namely checking migration of a sample collection, settings and maybe also some of the other stuff.

**Comment by sjohannes** [comment]
OK, I've done this. I couldn't find any `U` settings so hopefully it's fine. Everything else works well.
