### ISSUE TITLE
Segmentation fault on D&D from the Files tree onto Playlist

### ISSUE THREAD

**Issue by devfom** [exaile/exaile#67]
Hi,

I'm getting a segmentation fault every time I Drag and Drop from the Files onto Playlist. The log is the following:

> INFO    : Loading Exaile 3.4.4 on Python 2.7.6...
> INFO    : Loading settings...
> INFO    : Using en_US UTF-8 locale
> INFO    : Loading plugins...
> INFO    : Loading collection...
> INFO    : Loading devices...
> INFO    : Connected to udisks2
> INFO    : Loading interface...
> INFO    : Using GTK+ 2.24.23
> INFO    : Loading main window...
> INFO    : Connecting main window events...
> INFO    : Loading panels...
> INFO    : Connecting panel events...
> INFO    : Done loading main window...
> INFO    : WARNING: could not open podcast file
> [1]    2939 segmentation fault (core dumped)  exaile

_Note_: it only happens if I D&D very quick. meaning without waiting sometime in the DragMove state, if I start Drag and wait a bit, when it doesn't crash.

Once I was able to get more precise call stack while running current git version, and it showed [this line](https://github.com/exaile/exaile/blob/master/xlgui/widgets/common.py#L336) so I guess it has something to do with a cover fetching.

Steps to reproduce:
1. Start app
2. From the files tree select any album under any artist
3. D&D onto playlist, without waiting to see the D&D status icon

**Comment by virtuald** [comment]
Interesting. I can't reproduce this, but it seems like my computer is probably too fast to do so.

**Comment by virtuald** [comment]
Oh, interesting. So, the line you linked to is inside a thread... so my guess is that the code is interacting with a UI widget from another thread, and badness is happening. This pattern is actually all over the Exaile codebase, probably should look for these things and clean them up.

**Comment by devfom** [comment]
Please, let me know if I can help somehow. I'm a bit new to Python, but nevertheless.

**Comment by virtuald** [comment]
To get really useful information, what you have to do is install python-dbg and related packages (like pygtk-dbg, et al) and run in gdb until it breaks, then you can use `py-bt` to get a stacktrace. It's a bit tricky, and I'm not sure if there's anywhere that it's completely documented.

Alternatively, you could just try running it via gdb (something like `gdb -- python exaile.py --startgui`) and see if the backtrace gives you something useful or not.

A core dump might be useful too... what OS are you running?

**Comment by devfom** [comment]
I'm using Ubuntu 14.04.2 LTS. I will try to capture stacktrace.

**Comment by virtuald** [comment]
It's also possible this is a GTK2 bug. We're in the process of migrating to GTK3, so once that is done we can give this a look.

**Comment by genodeftest** [comment]
This is no Gtk2 bug, still present in Gtk3. Only present if you move your mouse _really fast_

**Comment by sjohannes** [comment]
This is consistently happening on Exaile 4 when using the MSYS2 environment. Commenting out [`xlgui/widgets/common.py:267-273`](https://github.com/exaile/exaile/blob/07b92495bbb50c7e48314bf55734249d313eb09f/xlgui/widgets/common.py#L267) stops the crash, but the mouse cursor is missing and I can't find the code that causes it.

**Comment by genodeftest** [comment]
Maybe a threading issue?
@sjohannes can you get a backtrace? Preferably for both, python and native code, so `thread all apply backtrace full` and `py-bt`.

**Comment by sjohannes** [comment]
gdb isn't working for me, just hangs at some point during Exaile startup.

**Comment by genodeftest** [comment]
> gdb isn't working for me, just hangs at some point during Exaile startup.

You might want to change the cygwin gdb, if that even works on MSYS-built binaries. There are some differences between cygwin and msys2 provided versions of GDB.

**Comment by sjohannes** [comment]
I'm trying to rebuild the MSYS2 gtk3 package with debug symbols and it's failing. Argh. Not sure if it's worth trying to attack the problem from that angle anymore.

I think what's triggering the bug here is the custom drag icon code (the one that sets the drag icon to the album cover). If getting rid of it fixes the crash then that would be sufficient.

**Comment by genodeftest** [comment]
Please try the changes commited to #433.
