### ISSUE TITLE
AutoScrollTreeView scrolls to the top when reordering or adding songs to a playlist

### ISSUE THREAD

**Issue by fuhry** [exaile/exaile#685]
### Steps to Reproduce (for bugs)

1. Create a playlist with enough songs to have 3+ screens worth of scrolling to do.
2. Scroll down a few screens in the playlist
3. Drag to reorder songs, or drag songs from your library to the playlist.

### Expected Behavior

The playlist scroll offset should not change when list items are reordered.

### Current Behavior

The playlist list view (an `AutoScrollTreeView`) scrolls to the top. This appears to be a regression from Exaile 3.x.

### Possible Solution

See this draft PR for a horrific, hacky fix for the issue: https://github.com/exaile/exaile/pull/684

### Environment

Arch Linux, GTK3 3.24.13, MATE desktop environment

**Comment by sjohannes** [comment]
I can't find the root of the problem either; I don't know what's causing it to scroll. What do you think about https://github.com/sjohannes/exaile/commit/9aacc46dca7e3a7b35b5c92d3e423a3c9382ce93 ?

**Comment by luzip665** [comment]
Hello,

I got the same problem even without triggering the auto scroll. Each time I move a track on the bottom of the list to another position the list scrolls to (almost) to top.

A possible solution I found is to save the current vertical offset at the end of on_drag_data_received and re-set after the size-allocation signal.

In on_size_allocate the original value of self.get_parent().get_vadjustment() always is 7.0.

**Comment by luzip665** [comment]
There where similar things while inserting track from the left sidebar to the current list and with the queue.
In the queue it never scrolled to top but lost the right selection of tracks.

**Comment by luzip665** [comment]
Moved the scroll restoring to AutoScrollTreeView (as in PR #684)
Only the selection restoring happens in the playlist itself.

**Comment by virtuald** [comment]
Fixed in #766
