### ISSUE TITLE
Please include built man-page into the package

### ISSUE THREAD

**Issue by mexicarne** [exaile/exaile#69]
Hello. 

Building an manpage is a pita for a packager on FreeBSD:
1. One needs to install all the huge exaile dependency stack just to build simple manpage, because exaile is called in Makefile's manpage target.
2. FreeBSD package cluster building packages under root user, and since exaile refusing to start under root user, the overall process fails.

So, please keep the manpage target and include the all-set manpage (gzipped or not) into the actual distribution, so we can just copy it into the right place in the filesystem. Thank you much in advance.

**Comment by virtuald** [comment]
Sorry about the troubles.

If it helps, as of https://github.com/exaile/exaile/commit/7bc7bc72dd3be90d63f1b4ce5df0ebc7db76143e, we no longer refuse to run as root.

**Comment by mexicarne** [comment]
Hmm, indeed. Thanks for the point, I'll check that later today and response back, but including pre-built manpage is still the preferred choice. It's common practice to include the manpages and let user to rebuild them if needed. Most users are not much cares if their manpages were installed pre-built or were built on theirs system, the only thing they care - if manpage is available.

**Comment by virtuald** [comment]
Sure, I'm not opposed to including it, sounds like a reasonable plan to me. If you want to do it and create a pull request, that'd be great, otherwise I'll try to look at it in the near future unless @sjohannes beats me to it.

**Comment by mexicarne** [comment]
No, I get my words back. It now builds quite fine with commit, you mentioned. The only think that I had to tweak is the manpage directory prefix. It's PREFIX/share/man/man1 on linuces and PREFIX/man/man1 on bsd's. So may be there can be introduced MANPREFIX variable in Makefile, or something like that, but it's not that critical at the time. Thank you, and sorry for false alarm.

**Comment by sjohannes** [comment]
#8 has some additional info regarding this.

The MANPREFIX suggestion is now tracked at #70.
