### ISSUE TITLE
why translations don't work?

### ISSUE THREAD

**Issue by lahtis** [exaile/exaile#695]
why translations don't work in a compiled program?
```
INFO    : Loading Exaile 4.1.0-alpha1+3e38133...
INFO    : Using Python 3.6.9
INFO    : Using PyGObject 3.26.1
INFO    : Loading settings...
INFO    : Using Locale fi_FI UTF-8
INFO    : Using Mutagen 1.38
INFO    : Using GStreamer 1.14.5
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.22.30
INFO    : Using GTK+ theme Ambiance
INFO    : Loading plugins...
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
INFO    : Scanning library: file:///home/tuomas/Musiikki/Musiikki
INFO    : Scan completed: file:///home/tuomas/Musiikki/Musiikki
INFO    : Playing file:///home/tuomas/Musiikki/Musiikki/Johnnylla%20oli%20kitara/ACDC%20-%20Johnny%20B%20Goode.mp3

(exaile:16344): Gtk-CRITICAL **: 12:46:26.342: gtk_list_store_get_path: assertion 'iter->stamp == priv->stamp' failed
Traceback (most recent call last):
  File "/home/tuomas/Lataukset/git/exaile/xl/common.py", line 184, in _idle_callback
    value = func(*args, **kwargs)
  File "/home/tuomas/Lataukset/git/exaile/xlgui/cover.py", line 370, in do_cover_fetched
    *self.cover_size, interp_type=GdkPixbuf.InterpType.BILINEAR
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 814, in __getitem__
    aiter = self._getiter(key)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 802, in _getiter
    aiter = self.get_iter(key)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 836, in get_iter
    path = self._coerce_path(path)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 811, in _coerce_path
    return TreePath(path)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1175, in __new__
    path = ":".join(str(val) for val in path)
TypeError: 'NoneType' object is not iterable
INFO    : Playing file:///home/tuomas/Musiikki/Musiikki/monenmoista/Albert%20Lee%20-%20Rock%20And%20Roll%20Man.mp3
```
### Environment
* Operating System and version: Ubuntu 18.04.4 LTS
* Exaile Version: 4.1.0-alpha1+3e38133

**Comment by genodeftest** [comment]
This does not look like a translation issue to me. Can you please try with `LC_ALL=C ./exaile` instead and tell us whether you run into the same issue there?

Also, can you please describe what you did before you ran into this issue? Did you press specific buttons?

**Comment by lahtis** [comment]
LC_ALL=C ./exaile
INFO    : Loading Exaile 4.1.0-alpha1+3e38133...
INFO    : Using Python 3.6.9
INFO    : Using PyGObject 3.26.1
INFO    : Loading settings...
INFO    : Using Locale Unknown
INFO    : Using Mutagen 1.38
INFO    : Using GStreamer 1.14.5
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.22.30
INFO    : Using GTK+ theme Ambiance
INFO    : Loading plugins...
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
INFO    : Exaile is shutting down...
INFO    : Tearing down plugins...
INFO    : Saving state...
INFO    : Bye!

Locale is Unknown and translation is English.

**Comment by sjohannes** [comment]
Could you check if there is a `po/fi/LC_MESSAGES/exaile.mo` file? If the file exists, running Exaile with a fi_FI locale should work (not everything is translated currently, but some of the menu items should be in Finnish, as well as the side panel titles).

**Comment by lahtis** [comment]
LC_ALL=fi_FI ./exaile
exaile: Warning: unsupported locale setting
  Exaile could not set the application locale, this
  may cause language-specific problems. To investigate this
  issue, look at the output of the locale tool.

(exaile.py:20546): Gtk-WARNING **: 14:19:28.647: Locale not supported by C
library.
Using the fallback 'C' locale.
INFO    : Loading Exaile 4.1.0-alpha1+3e38133...
INFO    : Using Python 3.6.9
INFO    : Using PyGObject 3.26.1
INFO    : Loading settings...
INFO    : Using Locale Unknown
INFO    : Using Mutagen 1.38
INFO    : Using GStreamer 1.14.5
INFO    : Reconfiguring crossfading
INFO    : Crossfade: disabled
INFO    : Using GTK+ 3.22.30
INFO    : Using GTK+ theme Ambiance
INFO    : Loading plugins...
INFO    : Loading collection...
INFO    : Loading devices...
INFO    : Connected to udisks2
INFO    : Loading interface...
INFO    : Loading main window...
INFO    : Connecting main window events...
INFO    : Loading panels...
INFO    : Connecting panel events...
INFO    : Done loading main window...
INFO    : Scanning library: file:///home/tuomas/Musiikki/Musiikki
INFO    : Scan completed: file:///home/tuomas/Musiikki/Musiikki
INFO    : Exaile is shutting down...
INFO    : Tearing down plugins...
INFO    : Saving state...
INFO    : Bye!

la 23. toukok. 2020 klo 18.00 Johannes Sasongko (notifications@github.com)
kirjoitti:

**Comment by rokm** [comment]
Hmm, setting `LC_ALL` does in fact seem to have no effect when running exaile out of the source directory. But it does work with system-installed version (also for `fi_FI`).

I think in the out-of-source-dir case, [the `locale_path` is set incorrectly, ](https://github.com/exaile/exaile/blob/e0b9757ab88eff3217a328139ac58e20de26a9df/xl/nls.py#L72), as it points to the translations' source directory (`po`). It should be pointing to the directory with compiled translation files, i.e., `build/locale`, which is created after running `make`.

**Comment by sjohannes** [comment]
Oh, you're right, @rokm. We used to dump the compiled translations in the `po` directory, but I moved them to `build/locale` and forgot to change this part of the code. Should be ok now.

**Comment by lahtis** [comment]
Exaile is now working properly. Thanks to everyone for the fix.

Tuomas

la 30. toukok. 2020 klo 17.36 Johannes Sasongko (notifications@github.com)
kirjoitti:
