### ISSUE TITLE
Right click properties on a playlist cause unexpected behavior

### ISSUE THREAD

**Issue by sarosenb** [exaile/exaile#7]
Right clicking properties on a playlist causes either nothing to happen or seemingly random songs in playlist to display their properties or crash Exaile.

**Comment by johannspies** [comment]
Maybe this is related: 

Example: I define a new smart playlist play only tracks that has not been played for the last 10 weeks.
![screenshot - 12032015 - 11 46 28](https://cloud.githubusercontent.com/assets/2785429/6615543/79af055c-c8ad-11e4-9f81-1cc11c7b4454.png)

Doubleclicking on it has no effect.  When I open that smartlist for modifications it shows:
"Play all the items played in the last 10 seconds"  
![screenshot - 12032015 - 11 45 05](https://cloud.githubusercontent.com/assets/2785429/6615519/44a6c980-c8ad-11e4-92cf-f7151f8d17ca.png)

This is on Debian.

> wajig list exaile
ii  exaile                                                      3.4.0.2-1                           all          flexible, full-featured audio player
ii  exaile-plugin-contextinfo                                   3.4.0.2-1                           all          Exaile plugin for contextual information
ii  exaile-plugin-ipod                                          3.4.0.2-1                           all          Exaile plugin for iPod support
ii  exaile-plugin-moodbar                                       3.4.0.2-1

**Comment by genodeftest** [comment]
@johannspies : That is a separate issue. If you can still reproduce it with [4.0.0 beta 2](https://github.com/exaile/exaile/releases/latest), please open a separate issue.

@sarosenb : I cannot reproduce the bug you described with [4.0.0 beta 2](https://github.com/exaile/exaile/releases/latest). If you still can, please add a comment here and reopen this issue. I assume it is being fixed.
