### ISSUE TITLE
Add MANPREFIX Make option

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#70]
According to #69, manpages in FreeBSD are located in `$PREFIX/man`, while in Linux it's `$PREFIX/share/man`.

**Comment by sarnold** [comment]
Since I've been having so much fun with make and autotools lately, I went ahead and added this to master (commit is on top of pull request #184) but it took a little cleanup and a compatibility fix to the launcher script to make it work correctly.  (see commit msg, it was a weird bug...)

**Comment by mexicarne** [comment]
That's great news, thank you!

**Comment by sjohannes** [comment]
My comments to 8fb10cc ended up cluttering #148, which is really about a different issue, so I'll move them here. I've also added an extra reply to the `.NOTPARALLEL` stuff.

```diff
-PYTHON2_CMD	?= `command -v python2`
+PYTHON2_CMD	= `command -v python2`
 
-PREFIX 		?= /usr/local
-EPREFIX		?= ${PREFIX}
-LIBINSTALLDIR 	?= /lib
-XDGCONFDIR 	?= /etc/xdg
+PREFIX		= /usr/local
+EPREFIX		= $(PREFIX)
+LIBINSTALLDIR	= $(EPREFIX)/lib
+DATADIR		= $(PREFIX)/share
+XDGCONFDIR	= /etc/xdg
+MANPREFIX	= $(PREFIX)/share
```

I tried replacing all the `=`s here to `?=` and running `make PREFIX=foo` and it seem to still work. As far as I know, the only difference between `=` and `?=` is that `?=` allows reading values from the environment, i.e. `PREFIX=foo make` instead of `make PREFIX=foo`, so I don't understand how you're seeing the problem you mentioned in the commit log.

```diff
+.NOTPARALLEL:	install-target install-locale make-install-dirs
```

>> The [GNU Make manual](https://www.gnu.org/software/make/manual/html_node/Special-Targets.html#index-_002eNOTPARALLEL) suggests that just the presence of `.NOTPARALLEL:` causes the whole makefile to be run sequentially (and that any prerequisites are ignored). I've never had problems with `make -j`; what is `.NOTPARALLEL` fixing here?

> It probably went in early in debugging the missing "/usr" path, but in this case it should be safer than not (or relying on upstream packagers like me to add MAKEOPTS=-j1 as a workaround). Otherwise your two different make targets have a potential race condition between creating the target dirs and installing to the same dirs

That shouldn't be possible, though. `install-target` depends on `make-install-dirs`, so it won't install the files before all the dirs are created.

```diff
-	-find . -name "*.~[0-9]~" -exec rm -f {} \;
-	-find . -name "*.py[co]" -exec rm -f {} \;
-	find po/* -depth -type d -exec rm -r {} \;
+	-find . -name "*.~[0-9]~" -exec rm -f {) \;
+	-find . -name "*.py[co]" -exec rm -f {) \;
+	find po/* -depth -type d -exec rm -r {) \;
```

Search-and-replace mistake?

**Comment by sarnold** [comment]
Yup, eyes getting older...  didn't see that one without looking at full diff in meld...

**Comment by virtuald** [comment]
This seems fixed, comment if it isn't.
