### ISSUE TITLE
Absolute position in playing track (times) is too discreet. Lack of contrast on Windows?

### ISSUE THREAD

**Issue by Chealer** [exaile/exaile#700]
### Expected Behavior
The position in the current track should be displayed with a minimal prominence.

### Current Behavior
The time to start and time to end are written:

- with a gray font on a gray background
- in the smallest font size

![image](https://user-images.githubusercontent.com/486141/81363622-cf509f80-90b1-11ea-83fa-080bedd1ff5d.png)

### Possible Solution
The easiest fix would be to make the font darker (for maximal contrast, black). For me, this would suffice, but for people with a worse sight, increasing the font size might also be warranted. One option to do that without increasing window height would be to move the position at the right of the position bar, which can currently get quite longer than required.

### Environment
* Windows 10:
GStreamer: 1.16.0
GTK+: 3.24.8
GTK+ theme: Adwaita
Locale: French_Canada 1252
Mutagen: 1.40.0
PyGObject: 3.32.1
Python: 2.7.16
* Exaile Version: 4.0.2

---

I installed Exaile and played a few tracks. Then, I checked where I was. Seeing that the systray tooltip would not show it, I opened the window, and it took about 10 seconds before I finally noticed where the position was written. During that time, I thought I found Exaile unimpressive, but that it was already good that it was open source and that I hadn't found any major issue with it after 20 minutes of testing. I wondered whether the absence of that information (by default) meant I was wasting my time on a product too immature, or if I should continue my trial.

When I finally located the information, I first thought this was a problem specific to that information and started writing this report. But when I took the screenshot, I realized that a large share of the interface elements display with very low contrast (also gray on gray). I am therefore wondering if I am experiencing Exaile as it was meant to be, or if the primary issue is one with the default theme. For other elements, this certainly does not constitute a problem anywhere close to the one reported here, but I tend to think that for some elements (at least the Play/Stop/etc playback buttons) this is sub-optimal.

To complete, I should note that there is one more element which led me to conclude the text was missing in addition to contrast and size: I did not expect the text to be at the center of the position bar, isolated from all other interface elements.

To clarify, it took me at least 5 seconds to notice the text even while a track was playing (i.e. when the text was changing, which should have helped locating it).

**Comment by sjohannes** [comment]
The styling comes from the GTK theme. There's no real way to change it in a manner that would work with all themes, so the only alternatives I can think of are to either draw our own widget or move the text to the side.

I'm leaning towards moving the text to the side as it's simpler, but this is a big decision (we haven't moved things around in the UI for maybe 10 years) and will require input from the other developers.

**Comment by virtuald** [comment]
The screenshot you shared is pretty much what I expect Exaile to look like, it's not particularly flashy but it gets the job done well. 

I'm not opposed to changing it -- though I guess I'd like to see some different variations before we pick one? I'm actually used to the progress bar being on the top (because I use the dual-playback feature, which moves elements of the UI around). I think we have some other issues open regarding ideas for UI rearrangement, but haven't done any of them in quite awhile as sjohannes said.

**Comment by sjohannes** [comment]
I think the biggest issues are that the text is small and the contrast is low, so it can be difficult to read. It used to look fine on most GTK 2 themes ([like in this screenshot](https://www.exaile.org/public/images/exaile-3.4.png)) due to the GtkProgressBar on themes from that era, but since the switch to GTK 3 the visibility is kind of poor on Adwaita and its many derivatives. Perhaps this is something to bring to the GTK designers instead, but I don't have much hope there.

**Comment by sjohannes** [comment]
OK, I think I figured something that we can use. Adwaita sets this:

```css
progressbar {
  font-size: smaller;
  color: transparentize($fg_color, 0.6);
}
```

which is my main problem with it. We can undo this with:

```css
progressbar {
  color: unset;
  font-size: unset;
}
```

and the text becomes normal sized and non-transparent. The bar shifts down a few pixels but still looks fine. On some themes this might cause the playback hbox (including the buttons) to grow a bit taller, but I don't see it causing any significant issues.

What do you think, @virtuald? You can test it from the CSS tab of Gtk Inspector.

**Comment by Chealer** [comment]
> The screenshot you shared is pretty much what I expect Exaile to look like, it's not particularly flashy but it gets the job done well.

Thanks @virtuald 
Regarding the general appearance, to clarify, I was not suggesting elements should blink... there should be room between difficult to see and flashy. I was not even suggesting colors to be used, higher contrast would already make a big difference.

I also think there are elements for which higher contrast is not warranted. For example, the icons at the right of filter fields to clear them need not be prominent, and having them very subtle is fine for me. They are easy to see anyway as they are in the fields. What I find curious is the discretion of primary elements, like the Play and Stop buttons.

Thank you very much for the investigation @sjohannes

**Comment by sjohannes** [comment]
I've pushed a commit that makes progressbars use the normal font color and size, which should make it easier to read.

Regarding the playback buttons, those images come from the icon theme. On Windows we use GTK's default, Adwaita, so again perhaps this is something to bring up to the GTK developers. We could create our own icons and override the user's theme but I'd rather not.

**Comment by Chealer** [comment]
Thank you very much Johannes

I still feel the text could be larger, and ideally grouped with track information (at the top), but I confirm visibility is reasonable in Exaile 4.2.2.

Moreover, I am happy to see not only the position improved, but the contrast of many more elements is now optimal.👏
