### ISSUE TITLE
How to store ratings/stars in *.m3u playlists? Where is it currently stored?

### ISSUE THREAD

**Issue by tobwz** [exaile/exaile#703]
Where does Exaile store my current rating information?

Is it possible to put it into *.m3u playlist file as well?

Tobias

**Comment by sjohannes** [comment]
> Where does Exaile store my current rating information?

It's in the the library database (`~/.local/share/exaile/music.db`).

> Is it possible to put it into *.m3u playlist file as well?

[The M3U format](https://en.wikipedia.org/wiki/M3U#File_format) doesn't seem to have an accepted way to store this sort of information, so I don't think that's possible.
