### ISSUE TITLE
How to associate 1 playlist with exactly 1 folder? Auto-add+auto-delete to/from playlist?

### ISSUE THREAD

**Issue by tobwz** [exaile/exaile#704]
The way I organize my playlists and *.mp3 songs is as follows:
I have multiple folders with multiple *.mp3 file in each.
All *.mp3 files in a certain folder are put into exactly one corresponding playlist.

What I want to achieve now is that if I add a new *.mp3 file physically in a folder (by copying inside Windows Explorer outside of Exaile) this new *.mp3 file should AUTOMATICALLY be added at the end of the playlist. Or at least on-demand by menu/command "add all new songs".

Conversely if I remove physically a song from folder (in WinExplorer outside of Exail) the songs should AUTOMATICALLY by removed from Playlist (or at least on demand by "refresh playlist" command or similar).

How can I achieve this?
How do I setup such an association?

Changing the song order in Playlist should auto-update the underlying *.m3u playlist file as well (at least on Exaile exit)

Thank you
Tobias

**Comment by sjohannes** [comment]
This is not possible, sorry. Exaile only supports basic import+export of M3U playlists, and it has to be done manually. I think this would be better done from a separate program.

**Comment by virtuald** [comment]
You could definitely write a plugin to do this, but it'd be a bit of work, and probably not something we would ship with Exaile.
