### ISSUE TITLE
Feature request: Shortcut to add gap/wait time between songs

### ISSUE THREAD

**Issue by phalgunlolur** [exaile/exaile#708]
Hello everyone,

I was talking to one of the local DJs here in Sweden and he mentioned how in his program, he can set how long to wait before playing the next song. Basically, it's the ability to set a pause between songs on the go, with a hotkey. He can press ctrl+5, then the software automatically waits 5 secs before playing the next song. ctrl+9 ---> 9 secs before playing the song. I think it would be a great feature that can be added to Exaile and would be pretty useful in reading the crowd behaviour, thereby control the music flow better.

### Expected Behavior

I use the shortcut ctrl+4 to set the gap time between songs to be 4 seconds. ctrl+2 - gaptime is 2 seconds

### Current Behavior

Currently, there is an option to set a gap between songs manually in the settings
-->
### Environment

* Operating System and version: Windows 10

* Exaile Version: 4.0.2
GStreamer: 1.16.0
GTK+: 3.24.8
GTK+ theme: Adwaita
Locale: English_United States 1252
Mutagen: 1.40.0
PyGObject: 3.32.1
Python: 2.7.16

**Comment by virtuald** [comment]
Does it revert back to the default gap or does it stay at that gap until changed again?

**Comment by phalgunlolur** [comment]
I'm not sure. But either option would be good to implement, I believe. I would personally prefer the gap staying whatever is set until it is changed again with a hotkey.

**Comment by luzip665** [comment]
@phalgunlolur 
Is this issue resolved for you with the quickbuttons plugin from #746 and #775?

**Comment by phalgunlolur** [comment]
Yes. It's resolved with the previous quickbuttons plugin. I am unable to install the new updated plugin as it says that there is already a plugin installed with the same name. So I have to presumably uninstall the older plug-in but I'm not quite sure how
![image](https://user-images.githubusercontent.com/17207822/147304583-b3ef650e-2204-4e98-94c5-dc474884dd99.png)

**Comment by phalgunlolur** [comment]
It's resolved for me now!
