### ISSUE TITLE
Disable confirmation on the BPM counter plugin

### ISSUE THREAD

**Issue by phalgunlolur** [exaile/exaile#717]
Hello,

I was wondering if it would be possible to disable the confirmation - 'Set BPM of xxxxx to 145' after I tap it and hit Apply BPM. It would make my music sorting process a little quicker. I can understand the need to have it for others but I personally would like to have it disabled if possible

### Expected Behavior
Once I tap the BPM, hit Apply BPM the BPM is saved to the IDE tag

### Current Behavior
Once I tap the BPM, hit Apply BPM, I get a pop up asking for a confirmation if I really want to set the BPM to xxx

### Possible Solution
Have an option in settings to disable the confirmation

### Environment

* Operating System and version:
Windows 10

* Exaile Version: 4.0.2
GStreamer: 1.16.0
GTK+: 3.24.8
GTK+ theme: Adwaita
Locale: English_United States 1252
Mutagen: 1.40.0
PyGObject: 3.32.1
Python: 2.7.16

**Comment by sjohannes** [comment]
I reckon we don't really need the confirmation; could probably just remove it altogether, unless other devs object.

**Comment by rokm** [comment]
Removing the confirmation altogether sounds reasonable.

**Comment by phalgunlolur** [comment]
Great. Looking forward to a future version soon!

**Comment by phalgunlolur** [comment]
Is there a quick fix to this without having to waiting for a future version?

**Comment by sjohannes** [comment]
In `plugins/bpm/__init__.py`, replace [lines 126 to 136](https://github.com/exaile/exaile/blob/309cc1f57e9063109d0dcf9875c8da7250c8bbb0/plugins/bpm/__init__.py#L126-L136) with

```py
self._set_bpm(Gtk.ResponseType.YES, bpm, track)
```

**Comment by phalgunlolur** [comment]
This worked for me, thank you!
