### ISSUE TITLE
Can't run or install on Kubuntu 20.04 (various problems)

### ISSUE THREAD

**Issue by berrytsakala** [exaile/exaile#725]
**Solution: install dependencies listed in  DEPS file.**

As of today, 2020-10-28, in Kubuntu, it means to install these packages:

```sudo apt install python3-bsddb3  python3-mutagen python3-dbus python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0    libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-libav gstreamer1.0-x gstreamer1.0-alsa  gstreamer1.0-gtk3 gstreamer1.0-pulseaudio```

(I might've forgotten few python packages here.)

After installing the dependencies, Exaile should be able to run directly from the git directory, without any errors, i.e.
```
$ cd exaile
$ ./exaile
```

**Original problem descriptions, and error messages, for future readers who also didn't read the DEPS file**

All installation problems, "weird" errors, are solved by installing dependencies, and pulling latest git. 

These errors (and more) are given due to missing dependencies:

 - Gst namespace not found
 - ValueError: Namespace GstPbutils not available
 - /bin/sh: 1: help2man: not found   (this is not required to run)
 - (and other errors)

Other notes:

 1. the program's runtime doesn't check or warn about missing dependencies
 2. the dependenies are in the non-standard DEPS file.
 3. Do NOT try to install the "stable/current" suggested tar.gz package: it's using python2. Python2 is deprecated on K/Ubuntu 20.04+ anymore, and trying to install python2 will cause you a lot of problems.

My system:

 - Python 3.8.5 (default, Jul 28 2020, 12:59:40)
 - Kubuntu 20.04 (updated regularly)

**Comment by sjohannes** [comment]
> ValueError: Namespace GstPbutils not available

This is likely missing the `gir1.2-gst-plugins-base-1.0` package (it's listed in the [`DEPS`](https://github.com/exaile/exaile/blob/master/DEPS) file).
