### ISSUE TITLE
Playing 0DB: output is +0.2 DB

### ISSUE THREAD

**Issue by XzuRukneg** [exaile/exaile#73]
I put a normalized to 0DB audio file in Exaile and play.
Recording exaile with Ardour, I notice the output was not 0 DB but +0,2DB.
This is very disturbing for me (cracks noise, etc..).

![exail peak](https://cloud.githubusercontent.com/assets/4454843/7319138/5cfca5a6-ea93-11e4-92af-03e2cc6c8a6e.png)
You can see on this screen shot the original file, and backside the exaile output, a little bigger.

**Comment by virtuald** [comment]
Try turning the equalizer plugin off.

**Comment by XzuRukneg** [comment]
I don't have any EQ or plugins.
And sorry, I've don't say the version, it's Exaile 3.4.4

**Comment by virtuald** [comment]
Exaile comes with certain plugins enabled by default. If you go into 'Preferences', there's a list of plugins displayed. By default, Exaile comes with the Equalizer plugin enabled. Try disabling it, and let me know if that fixes your issues.

**Comment by XzuRukneg** [comment]
I confirm I don't have plugin enabled!

**Comment by virtuald** [comment]
Certainly a gstreamer problem, but not really sure what. Are you using Windows or Linux?

**Comment by XzuRukneg** [comment]
Linux.

**Comment by virtuald** [comment]
I think this is a gstreamer problem as Exaile doesn't directly manipulate audio data -- you can test this by using `gst-launch-0.10 playbin2 uri="file:///path/to/file.ogg` to play an audio file. You can use `gst-launch-1.0 playbin uri="file:///path/to/file.ogg` to try it using gstreamer 1.x.

We're in the process of migrating to gstreamer 1.x, so once that's done you can try it out and let us know whether it's still an issue.
