### ISSUE TITLE
Travis migration (.org to .com, or maybe to something else)

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#732]
[travis-ci.org is closing down on 31 December 2020](https://docs.travis-ci.com/user/migrate/open-source-repository-migration), and we're expected to migrate to the .com service.

Our builds are taking 15+ minutes, most of it just waiting for build machines to be available. Hopefully migrating to .com brings this down again.

**Comment by sjohannes** [comment]
For comparison, here is a working GitHub Actions config for Exaile: <https://github.com/exaile/exaile/compare/master...sjohannes:ghci>, and here is the build output: <https://github.com/sjohannes/exaile/actions/runs/374554413>. Normal builds take 1 minute, deployment builds take 1.5 to 2 minutes. The only thing missing compared to our Travis config is the IRC notification, which is not a big deal.

**Comment by virtuald** [comment]
I've had great success with github actions on RobotPy, I'd be supportive of ditching travis/appveyor for github actions.
