### ISSUE TITLE
Travis → GitHub deploy fails

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#733]
The source deployment stage on Travis [is failing](https://travis-ci.org/github/exaile/exaile/jobs/743915896) and the reason is completely unclear to me.

Looking at the build history, the [alpha1 deploy also failed](https://travis-ci.org/github/exaile/exaile/builds/659951506). So how the hell did it appear in the release? Did I create the tarball manually? I don't remember doing it at all.

**Comment by rokm** [comment]
This looks like the issue with `virtualenv: system_site_packages` being enabled. See https://travis-ci.community/t/python-3-6-and-3-7-with-system-site-packages-enabled-fails-to-activate-on-xenial/1697

**Comment by rokm** [comment]
Do we need system site packages? Or rather, do we need `python-gi` (installed via apt-get, hence the need for system site packages) to create the source distribution?

**Comment by sjohannes** [comment]
No, `make dist` just uses normal Unix stuff (sed, tar, etc.) and Python with no external modules (to run `tools/plugin_tool.py`).

(If you want to trigger a Travis build for testing: `git tag -a whatever && git push origin whatever`. Note that Travis builds take something like 30 minutes now due to #732. To remove the tag: `git push origin :whatever && git tag -d whatever`.)

**Comment by sjohannes** [comment]
I was wrong. `plugin_tool.py` imports Exaile stuff (`xl.xdg` and `xl.version`), which eventually imports GLib.

**Comment by rokm** [comment]
Indeed. Can we rework/isolate version retrieval, so that it won't require GLib?

**Comment by rokm** [comment]
Actually, it seems the only thing `version.py` is importing `xdg.py` for is `exaile_dir`, which is set to `os.environ['EXAILE_DIR']`.

So we could probably have `version.py` use its local copy of `exaile_dir = os.environ['EXAILE_DIR']`. Or, have `exaile_dir` defined in `version.py` or some other place, and have `xdg.py` pull it in from there.

**Comment by genodeftest** [comment]
Can we use something more recent than Xenial?

**Comment by sjohannes** [comment]
Forgot to comment on this when closing it: we've moved from Travis to GitHub Actions, so the original issue is not relevant anymore. Would still be nice not to require PyGObject during build time, though.
