### ISSUE TITLE
Latest Windows build fails to import GTK

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#734]
[This check fails.](https://github.com/exaile/exaile/blob/c7f11513422aa1cc56ba8660ead6e0d63d3bb449/exaile_win.py#L78)

Build: https://ci.appveyor.com/api/buildjobs/6mt4y7v2qtwlw03l/artifacts/exaile-4.1.0-beta1.exe

**Comment by rokm** [comment]
This one's caused by pyinstaller/pyinstaller#5129. 

I've synced the `sdk-py3` branch in our PyInstaller fork with `develop` branch from the upstream, which should take care of the problem.

**Comment by sjohannes** [comment]
Thanks! I've tested the latest build and it works.
