### ISSUE TITLE
request: Permanent jack output ports

### ISSUE THREAD

**Issue by XzuRukneg** [exaile/exaile#74]
That will be so great is we (GNU musicians) can have permanent JACK output ports for Exaile!
(for lots of multiples reasons)

Anyway, thank you very much!

**Comment by virtuald** [comment]
If you go to preferences, select 'Playback' and then look for the 'Audio Sink' option. There should be a JACK option there.

**Comment by XzuRukneg** [comment]
Maybe I'm not clear.
There is still not PERMANENT ports.
Their appears only if you start "play", and disappear when "stop".
Their are not permanent, so we can't use it into audio creative context. 
We need ports when exaile is launch, even if it was not playing.

**Comment by virtuald** [comment]
I see. Exaile doesn't directly interact with JACK at all, it uses a gstreamer plugin to communicate with it. If the gstreamer JACK plugin supports doing what you're talking about, then it's possible that someone could add a fix to Exaile to make sure it works properly.

I don't have JACK and am not familiar with it at all.

**Comment by XzuRukneg** [comment]
Ok.
So that issue comes from gstreamer. 
Thanks anyway!

**Comment by virtuald** [comment]
Well, it's possible that it *doesn't*, or that there's a way to work around it. However, someone would need to look into it, as I don't know very much about JACK. I suggest you look into it if you're interested.
