### ISSUE TITLE
Set the same tag to multiple songs

### ISSUE THREAD

**Issue by phalgunlolur** [exaile/exaile#741]
Hello,

I was wondering if it would be possible to select a number of songs, use the group tagger feature to assign a particular tag to all of the songs selected

### Expected Behavior
Assigning a tag to selected songs assigns the tag to all the songs

### Current Behavior
Assigning a tag to selected songs assigns the tag to only one song (the first selected track)

### Environment

* Operating System and version: Windows 10
* Exaile Version: 4.0.2

GStreamer: 1.16.0
GTK+: 3.24.8
GTK+ theme: Adwaita
Locale: English_United States 1252
Mutagen: 1.40.0
PyGObject: 3.32.1
Python: 2.7.16

**Comment by sjohannes** [comment]
This can be done using the "Apply current value to all tracks" toggle buttons on the right side of the Track Properties dialog (the one next to the Remove buttons).

![Illustration](https://user-images.githubusercontent.com/8440927/104016882-08945e80-51af-11eb-8911-37f893bc1901.png)

1. Select multiple tracks.
2. Right click → Track Properties.
3. Enter the value of the tag you wish to modify.
4. Activate the "Apply current value to all tracks" toggle button next to it.
5. Apply.

**Comment by sjohannes** [comment]
Actually I've just re-read this and I may have misunderstood what you meant. If you wish to apply the same Grouping tag to multiple files, this can be done with right click → GroupTagger → add tags to all.
