### ISSUE TITLE
Add Preferences shortcuts to the player

### ISSUE THREAD

**Issue by phalgunlolur** [exaile/exaile#746]
I was wondering if it was possible to add shortcuts from the preferences to the main player. For example, I'd like to 'Disallow playing new tracks when another track is playing' when I am actively DJing. I'd love to actively add a shortcut to the main player, on the bottom line where all it seems to do currently is display 'x songs showing, yzzx in collection' on the bottom right

As a sidenote, is it possible to disable that line or change what is displayed on that particular line?

This might also help with another issue I raised in the past (#708) about actively be able to change the delay between songs. If I can add a shortcut to the main player, I can easily a delay time in (milli)seconds and change it as I DJ

### Environment

* Operating System and version: Windows 10

* Exaile Version: 4.0.2
GStreamer: 1.16.0
GTK+: 3.24.8
GTK+ theme: Adwaita
Locale: English_United States 1252
Mutagen: 1.40.0
PyGObject: 3.32.1
Python: 2.7.16

**Comment by sjohannes** [comment]
There's no mechanism to do this, especially not in a generic way, but it wouldn't be difficult to write a plugin that just adds this for particular config items.

**Comment by phalgunlolur** [comment]
oooh, that sounds great. Also, any comments on configuring/ getting rid of what is displayed on the bottom line?

**Comment by luzip665** [comment]
I would like to try to implement.

My preferred shortcuts are:
* Queue tracks by default instead of playing them
* Disallow playing new tracks when another track is playing
* Remove track from queue upon playback
* Automatically advance to the next track
* Delay between tracks (ms)

Any further ideas?

**Comment by luzip665** [comment]
[quickbuttons.tar.gz](https://github.com/exaile/exaile/files/6363445/quickbuttons.tar.gz)

You can try this plugin.
It adds some buttons and a spinner on the bottom line of the playlist.
The spinner sets the delay between tracks in seconds.

**Comment by phalgunlolur** [comment]
Hi @luzip665 

I tried installing this plugin but I'm unable to enable it. I get the following error - invalid syntax (C:\Users\phalg\AppData\Local\exaile\plugins\quickbuttons\__init__.py, line 77)

I looked up the code and it seems to be this line -     def _on_option_set(self, event_name, event_source, option: str) -> None:

**Comment by luzip665** [comment]
Hi

which python version is installed?
Type hinting came with Python 3.5. Exaile (at least 4.1.1) is supposed to use Python 3.6.

But btw there was a bug in handling the default settings.
[quickbuttons-0.2.tar.gz](https://github.com/exaile/exaile/files/6564219/quickbuttons-0.2.tar.gz)

**Comment by phalgunlolur** [comment]
I'm using the windows build - 4.0.2, so it comes with Python 2.7. I'm leaving my system details below:

Operating System and version: Windows 10
Exaile Version: 4.0.2
GStreamer: 1.16.0
GTK+: 3.24.8
GTK+ theme: Adwaita
Locale: English_United States 1252
Mutagen: 1.40.0
PyGObject: 3.32.1
Python: 2.7.16

**Comment by luzip665** [comment]
Can you update?

**Comment by phalgunlolur** [comment]
I just did. Didn't realise there was an updated version of Exaile out. 

I noticed a small non-performance bug. The spinner(?) where I add the delay is excellent and exactly what I've been looking for. Only thing I would change there is the pop-out text. It currently says the delay is in ms, where as it is actually in seconds!

Is it also possible to add an EQ button there? The only other buttons I can think of is selecting the audio devices for the main playback and preview!

**Comment by luzip665** [comment]
It seems quite impossible to me to open the equalizer window from a button.
 
So, for now I only changed the label.
[quickbuttons-0.3.tar.gz](https://github.com/exaile/exaile/files/6813904/quickbuttons-0.3.tar.gz)

**Comment by luzip665** [comment]
Finally I got the equalizer button.
[quickbuttons-0.4.tar.gz](https://github.com/exaile/exaile/files/6926612/quickbuttons-0.4.tar.gz)

**Comment by luzip665** [comment]
Hello,

I think this can be closed after merging of https://github.com/exaile/exaile/pull/755

**Comment by virtuald** [comment]
Closing this issue for now. @phalgunlolur opened #775 for the feature you just requested.

**Comment by phalgunlolur** [comment]
Hi @luzip665,

I downloaded your plugin version 0.4 but sadly, I'm unable to install it. I get an error as follows:

'Plugin archive contains an unsafe path'

![image](https://user-images.githubusercontent.com/17207822/146277041-ccc2ceba-ceda-47be-a1b8-7028227e4223.png)

Also, I realised there is no way for me to uninstall a plugin, apart from disabling it. Am I missing something?

**Comment by luzip665** [comment]
[quickbuttons-0.4.1.tar.gz](https://github.com/exaile/exaile/files/7724844/quickbuttons-0.4.1.tar.gz)
Corrected.

But Uninstallation is an issue. Right now you can only just remove the plugin in the exaile data dir.

**Comment by phalgunlolur** [comment]
Still says unsafe path for me!
