### ISSUE TITLE
Equalizer has severe problems

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#75]
I've heard lots of complaints, and there are issues such as #52 related to it. I've disabled it by default, but at some point probably should figure out what's wrong with it.

A friend of mine's computer has severe static issues when using the EQ on Windows on battery power, along with the preview device. It's possible that there's an issue with the custom DirectSound driver, but I think there's a more general problem somewhere here too, as I've had issues with the EQ crashing Exaile on OSX.

**Comment by virtuald** [comment]
I'm hoping this will just magically resolve itself after migrating to GST 1.x.

**Comment by genodeftest** [comment]
I don't know how equalizer works but I noticed that all equalizers are on (enabled) by default. Could this be the reason?

**Comment by genodeftest** [comment]
I think the equalizer is working fine again now (with #104, c910e99, ef4a7ec, df81c05, etc.) in gi branch. At least it does for me. Can anyone confirm that?

**Comment by tfree87** [comment]
The equalizer seems to be working perfectly on my Fedora23 system.

**Comment by virtuald** [comment]
Good enough for me.
