### ISSUE TITLE
Unable to sort a playlist with rating value

### ISSUE THREAD

**Issue by phalgunlolur** [exaile/exaile#758]
I just upgraded to the latest exaile and I am no longer able to sort playlists by their rating

### Steps to Reproduce (for bugs)

1. Click on Rating and the sorting no longer works. 
2. Before clicking on Rating, sorting works well with other fields. Sorting doesn't work on other fields after clicking on Rating

### Expected Behavior
Be able to sort according to rating

### Current Behavior
Sorting stops working after clicking on the Rating tab

### Environment

* Operating System and version: Windows 10

* Exaile Version: 4.1.1

GStreamer: 1.18.4
GTK+: 3.24.27
GTK+ theme: Adwaita
Locale: English_United States 1252
Mutagen: 1.40.0
PyGObject: 3.38.0
Python: 3.8.8

**Comment by luzip665** [comment]
Hi,

this happens in case there is a track without rating in the list.

Possible bugfix: https://github.com/exaile/exaile/pull/762

**Comment by rokm** [comment]
Fixed by #762.
