### ISSUE TITLE
Import radio stations list

### ISSUE THREAD

**Issue by cefer60** [exaile/exaile#763]
Hello. Does anyone know if it is possible to import a list of radio stations?

**Comment by cefer60** [comment]
Hi. I discover how

Got to "File" then "Import playlist"
The list (text file) must be in "m3u" form (example: radiolist.m3u)

#EXTM3U
#EXTINF:0,FM 104.9
http://someurl
#EXTINF:0,FM 105.3
http://otherurl

**Comment by virtuald** [comment]
If we had more comprehensive user documentation, this would be a good thing to add to that. However, it doesn't exist at this time. Glad to hear you figured it out!
