### ISSUE TITLE
SPAT should leave the subsequent track next in queue

### ISSUE THREAD

**Issue by ryneeverett** [exaile/exaile#767]
Stop Playback After This Track should leave the next track stopped and selected after "this track" completes.

### Steps to Reproduce (for bugs)

1. Toggle on "Stop Playback After This Track"
2. Play the given track to completion.

### Expected Behavior

The subsequent track should be next in queue.

### Current Behavior

The same track is next in queue.

### Possible Solution

I think this should be the default behavior. Why would one want to play the same track again (next time they hit play) when it has already played to completion?

I would be probably be willing to implement it myself.

### Environment

* Operating System and version: Nixos 21.05
* Exaile Version: 4.1.1

**Comment by virtuald** [comment]
I agree that seems like buggy behavior. I've never really used the SPAT feature, so I'm mildly surprised it isn't broken. :-D

I'm happy to review a PR to fix this behavior.

**Comment by luzip665** [comment]
May it relates to #789?

There is one more thing. After removing the subsequent track the other tracks on queue keep greyed out. I would expect, that after the spat fires, the list is not grey any more.
