### ISSUE TITLE
Creates an empty log message t startup (Создаёт пустое лог сообщение при запуске)

### ISSUE THREAD

**Issue by algri14** [exaile/exaile#769]
Creates an empty log message every time you start/restart.
Создаёт пустое лог сообщение при каждом запуске/перезапуске.

Each time the player starts, it creates an empty log message in /home/user/.cache/exaile/logs/exaile.log , a lot of empty messages are recorded there, this is wrong.
При каждом запуске плеер создаёт пустое лог сообщение в /home/user/.cache/exaile/logs/exaile.log , там записывается очень много пустых сообщений, это неправильно.

### Environment

* Operating System and version: Mageia-8 x64 Kernel: 5.14.10-desktop-1.mga8 x86_64 Desktop: KDE Plasma 5.20.4

* Exaile Version: 4.1.0
* GStreamer: 1.18.5
GTK+: 3.24.24
GTK+ theme: Breeze
Locale: ru_RU UTF-8
Mutagen: 1.45.1
PyGObject: 3.38.0
Python: 3.8.12

**Comment by virtuald** [comment]
Do you mean "useless"? The log files have content in them.

**Comment by luzip665** [comment]
I can reproduce.

After starting exaile with --quiet flag there are two log files in ~/.cache/exaile/log:

exaile.log
exaile.log.1

Both files are empty.

Starting without any flag in exaile.log some message are written. exaile.log.1 keeps empty.

Seen on Ubuntu 20.04 with current master.
