### ISSUE TITLE
Add source selection to quickbuttons plugin

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#775]
Great. I was wondering if it possible to add a shortcut to select a source for the output audio and the preview device directly too. I'll check out the equalizer button later tonight! Thanks for adding it!

_Originally posted by @phalgunlolur in https://github.com/exaile/exaile/issues/746#issuecomment-994046065_

**Comment by luzip665** [comment]
@phalgunlolur
Hi!
You mean the playback setting for Audio Sink or Audio Device?

**Comment by phalgunlolur** [comment]
Audio Device. I usually leave Audio Sink to be automatic, without it being an issue for me.

Picking the main audio device and the preview device from the main window would be super useful. Especially, when I'm dealing with multiple sound cards

**Comment by luzip665** [comment]
Can you check
[quickbuttons_0.4.98.tar.gz](https://github.com/exaile/exaile/files/7732632/quickbuttons_0.4.98.tar.gz) ?
 
Right now working for the main device.

**Comment by phalgunlolur** [comment]
I'm unable to install it as I get the error - 'Plugin archive contains an unsafe path'
![image](https://user-images.githubusercontent.com/17207822/146640295-556fc424-4fef-4e3a-ad74-68a4bffef090.png)

**Comment by luzip665** [comment]
Ah. You need to rename the archive to quickbuttons.tar.gz.

**Comment by luzip665** [comment]
[quickbuttons.0.4.99.tar.gz](https://github.com/exaile/exaile/files/7750116/quickbuttons.0.4.99.tar.gz)

Now with both devices. The device list is a menu in order to update it if a device is added.

**Comment by phalgunlolur** [comment]
I've renamed the file but I cannot install the update as I already have the plugin installed with the same name (older version). How do I remove it to do a fresh install?

![image](https://user-images.githubusercontent.com/17207822/147304673-ea923f9d-6637-4927-8a63-7617aa04f7ea.png)

**Comment by luzip665** [comment]
Did a plugin update ever work?

For a fresh installation you need to find the exaile-plugin directory on your system. 
You use Windows, right? Could be something like `%USERPROFILE%\AppData\Local\exaile` .

If found in there is a folder named quickbuttons. This you need to remove.

**Comment by phalgunlolur** [comment]
I've never installed a plugin update until now. I removed the plugin folder in the local folder. I was initially looking for it in the main plugins folder in Program Files. This works really well for me now.

One additional request. Is it possible to hide the total songs in collection in that same row. I don't see the need to show how many songs I have in my collection. It could be an option to display it, if needed. I do like it that it shows how many songs are selected in a particular playlist with the total length though. I can open a separate issue about this, if that is better

**Comment by luzip665** [comment]
I agree, but I think, this is better in a separate Issue.
