### ISSUE TITLE
Tests hang on the fedora-latest and ubuntu-rolling test images

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#783]
[Example.](https://github.com/exaile/exaile/runs/4604173662?check_suite_focus=true) The command runs for 4 minutes with no output (normally it finishes in 10 seconds and outputs a lot of text) and times out.

[Here is the relevant section of the CI file](https://github.com/exaile/exaile/blob/a37184c804030b40d2411e6868256461f612c25c/.github/workflows/ci.yml#L20-L43).

Possibly an issue with recent pytest?

**Comment by genodeftest** [comment]
> Possibly an issue with recent pytest?

Which _recent_ version do you mean?

I've executed `make test` locally with `python3-pytest-6.2.4-5.fc35.noarch` on a fully updated F35 and it works fine for me, even when executed headless. I don't see any recent update or update in progress in the [package database](https://src.fedoraproject.org/rpms/pytest). As far as I understand, we install these packages [using DNF](https://github.com/exaile/exaile-testimg2/blob/master/Dockerfile.fedora).

**Comment by genodeftest** [comment]
I have no clue what `subinterpreters` are, but if they are used, it is likely to be [this bug](https://bugs.python.org/issue46070) ([Fedora bug report](https://bugzilla.redhat.com/show_bug.cgi?id=2034962)).

**Comment by luzip665** [comment]
What is ubuntu-rolling?

I did `make test` on Ubuntu 20.04 with Python 3.10.1 succesfully in general.

There are just some warnings, but that are not new I think
` xl.trax.track:track.py:560 Setting "__basename" directly is forbidden.`

**Comment by genodeftest** [comment]
"ubuntu-rolling" is a rolling release version of ubuntu, which means it always gets the latest packages quite soon ([more detailled explaination](https://www.techrepublic.com/article/how-to-convert-ubuntu-into-a-rolling-release/)) in contrast to regular Ubuntu releases which only get a few updates between Ubuntu releases. This is a concept that is being used for some other linux distributions (Arch linux, for example, is a rolling release distro) and especially for development channels (Fedora rawhide, Debian Unstable ("sid"), openSUSE Tumbleweed) which are usually less stable.

> ` xl.trax.track:track.py:560 Setting "__basename" directly is forbidden.`

I don't see that one, but I get a deprecation warning in mox instead…

**Comment by sjohannes** [comment]
> The latest update was pushed to Fedora's stable repositories on 2021-12-21, which roughly matches the time when the tests started to fail. All other packages I had a look at were updated more than a month ago.

What I failed to mention is that the problem could have been due to any OS changes between 2021-08-07 and 2021-12-17. This is because between these dates the exaile-testimg2 automated builds [stopped running](https://github.com/exaile/exaile-testimg2/actions#check_suite_4692509038) and therefore the test images didn't update during that time. (GitHub disables scheduled CI runs if there are no commits in 2 months; you have to go to the page and hit an "enable" button.)

> I have no clue what subinterpreters are, but if they are used, it is likely to be this bug (Fedora bug report) introduced in Python 3.10.1.

Ubuntu 21.10 (current `rolling`), which is also failing, is still on [Python 3.9.4](https://packages.ubuntu.com/impish/python3) so it's probably something else.

**Comment by luzip665** [comment]
I installed a current ubuntu-rolling on virtualbox. It's shipped with Python 3.9.9. Tests work.
Aside the Warning about mox I got 7 skips. 

Which packages are installed on ubuntu-rolling? Exaile does not work out of the box.

**Comment by sjohannes** [comment]
I'm unable to reproduce this using the same [Docker image](https://github.com/exaile/exaile-testimg2/pkgs/container/exaile-testimg) that the CI uses, using the same commands.

I've created a verbose test run with `python -v pytest -v`; [result](https://github.com/exaile/exaile/runs/4620300586?check_suite_focus=true#step:4:643). It appears that pytest hangs after that "collecting ..." message.

**Comment by luzip665** [comment]
Did some blackbox tests.

If the test xl/player/gst/test_fader is excluded, everything works
See https://github.com/exaile/exaile/pull/787/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R255

**Comment by sjohannes** [comment]
Thanks, that's very helpful. From there I tracked the issue further to the `PLAYER` initialisation in `xl/player/__init__.py` but that's as far as I got up to.

(As an aside, I've never liked the fact that we create those `PLAYER` and `QUEUE` singletons on import.)

**Comment by luzip665** [comment]
Tracking further to `xl/player/gst/__init__.py` Line 17.

Tests work if I remove this line.

**Comment by sjohannes** [comment]
Thanks, the culprit is indeed the `Gst.init` call. I've created a GitHub project that minimally reproduces this: https://github.com/sjohannes/pytest-gst-test . It contains one test file that just calls `Gst.init`, and a GitHub CI file that starts with the plain `ubuntu:21.10` Docker image, installs a few things, and runs pytest.

**Comment by luzip665** [comment]
Tried to use init_check to fetch a GLIB.Error but I can't get any output.

Merry Christmas!

**Comment by sjohannes** [comment]
Oh, it looks like this has nothing to do with pytest. [This very simple CI file](https://github.com/sjohannes/pytest-gst-test/blob/ddd6859d36a4905cff8ac1af561f582a3332b551/.github/workflows/ci.yml), with nothing else in the project, [already hangs](https://github.com/sjohannes/pytest-gst-test/runs/4628116748?check_suite_focus=true).

I'll see if I can test this using C instead of Python, but at this point it's looking like a GStreamer issue. It's weird that it only happens on GitHub Actions though....

**Comment by sjohannes** [comment]
It also happens from C. I've created a GitHub support ticket and written to the GStreamer IRC channel about this; no replies yet. In the meantime I'll disable the two failing jobs.

GH ticket (I filed under the Exaile org but I don't know if anyone else in the org can view it): https://support.github.com/ticket/personal/0/1438369

**Comment by sjohannes** [comment]
Debugged this with Tim-Philipp Müller on the GStreamer IRC channel.

What happens is that, on `gst_init`, GStreamer launches a `gst-plugin-scanner` subprocess using `g_spawn_async_with_pipes`. Somehow in our case this call never returns. Tim suggests that this might be [GLib bug 2506](https://gitlab.gnome.org/GNOME/glib/-/issues/2506), fixed in GLib 2.70.3. We don't know why we're only seeing this on GitHub Actions, but the symptoms roughly match.

Setting `GST_REGISTRY_FORK=no` ([documentation](https://gstreamer.freedesktop.org/documentation/gstreamer/running.html)) causes the plugin scan to be done in-process, which works around this. (`GST_REGISTRY_UPDATE=no` doesn't work, probably because the registry needs to exist for it to have an effect.)

**Comment by genodeftest** [comment]
Thanks for the collaborative debugging and fix!
