### ISSUE TITLE
Plugin update and remove is difficult

### ISSUE THREAD

**Issue by luzip665** [exaile/exaile#788]
If I try to update or remove custom installed plugins, there are some difficulties

### Steps for reproduce
1. Install a custom plugin via Settings > Plugins > Install > Add Plugin File
2. Install the same plugin (in a newer version) again

### Current Behavior
A Message with 'A plugin with the name ... is already installed.' comes up

### Expected Behavior
The new plugin version is installed

### Steps for reproduce
1. Install a custom plugin via Settings > Plugins > Install > Add Plugin File

### Current Behavior
There is no button to remove the custom plugin

### Expected Behavior
There should be a button to remove the custom plugin. May be in the plugin list next to the refresh plugin.
The button is only needed for custom plugins. Shipped plugins must not be deletable.

**Comment by phalgunlolur** [comment]
Great. I'm glad this got added!
