### ISSUE TITLE
'Previous track' fails when playing in shuffle mode

### ISSUE THREAD

**Issue by Noctiflore** [exaile/exaile#79]
When playing in tracks shuffle mode (not tried with album shuffle), previous track action often skips some tracks, jumping to another previously played track. The latter seems to become the 'default target' for some time (every subsequent try leads to this one).
Trying to come back to a track played when still in sequential mode also seems to fail.

(tested on versions 3.3.2, 3.4.0 and 3.4.5+544bd5b (latest commit)).

**Comment by virtuald** [comment]
Strange. I think we'll put this off until after the GTK3/GST1.x migration, unless someone else finds time to fix it.

**Comment by genodeftest** [comment]
@sbrubes: Would you mind rebasing your changes into separate branches and create pull requests? I'd like to see your fixes here ;)

**Comment by sbrubes** [comment]
No big deal.

That's why I've asked about the procedure at IRC.

I've supposed that should be a branch for a fix, but I didn't know that.

I don't know when I'll do, so if you have an easier way, you could do it, it's also not a problem.

Thank you.

**Comment by genodeftest** [comment]
If it's just small changes you can easily create pull requests against the master branch. Right now, this is the only branch being developed on.

I've cherry-picked or manually committed a few of the changes you proposed, so thank you!

**Comment by virtuald** [comment]
Fixed in 407ed9ac8980668ff23069465a140a8adc3fc6f9
