### ISSUE TITLE
Windows build broken due to feedparser & setuptools incompatibility

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#799]
[Build log.](https://ci.appveyor.com/project/ExaileDevelopmentTeam/exaile/builds/42190852)

The culprit is [feedparser 5.2.1 using setuptools' `use_2to3` feature](https://github.com/kurtmckee/feedparser/blob/5.2.1/setup.py#L6), which has been [removed in setuptools 58](https://setuptools.pypa.io/en/latest/history.html#v58-0-0).

Suggested solution:

* Test whether the *podcasts* plugin can work with feedparser 6.
* If it works, then just upgrade the feedparser version in `tools/installer/requirements.txt`.
* If it doesn't work, make it work with both feedparser 5 and 6. This is necessary because Ubuntu is still on feedparser 5 while Fedora is already on 6.

The quick workaround, if we just want the Windows build to work again, is to revert the [Windows SDK update](https://github.com/exaile/exaile/commit/904ea460361617fd48aa66c10b4bc7a513ad3b0f).

**Comment by luzip665** [comment]
Test with feedparser 6.0.8 on Ubuntu 20.04 seem to work.

**Comment by luzip665** [comment]
Tested on Win10 with feed 'https://www.bremeneins.de/feed/podcast/chronik-114.xml'

Works in general, but has an issue with the ssl. May relate to https://stackoverflow.com/questions/35569042/ssl-certificate-verify-failed-with-python3
