### ISSUE TITLE
Unable to change cover of a track

### ISSUE THREAD

**Issue by ashishhowal** [exaile/exaile#810]
### Steps to Reproduce (for bugs)
1. Run Exaile 
2. Right-click on the track and click on track properties
3. click on add cover 
4. Navigate to the new cover image and select the image (.jpg Image selected of 64.8 kb) 
5. Click on save 

### Current Behavior:  Writing of Tags failed error. 
Tags could not be written to the following files:
file:///source/Music/Khalid%20-%20Scenic%20Drive%20EP%20(2021)%20Mp3%20320kbps%20%5BPMEDIA%5D%20%E2%AD%90/08.%20Open%20(feat.%20Majid%20Jordan).mp3

### Environment

* Exaile Version:  [4.1.2-beta1](https://github.com/exaile/exaile/releases/download/4.1.2-beta1/exaile-4.1.2-beta1.tar.gz)
windows version
![unable_to_add_new_Cover](https://user-images.githubusercontent.com/30282765/166643053-fa35374e-ca87-4d80-89d0-8d1022d1a1f3.png)

**Comment by luzip665** [comment]
Hello @ashishhowal 

thanks for your feedback.
I tried myself and cannot reproduce here.

Please, can you append exaile.log? You should find it in `%USERPROFILE%\AppData\Local\exaile\logs`
Can you save other tags?

**Comment by ashishhowal** [comment]
I'm able to change tags for some songs however, for some songs, it throws an error. 
The Logs say Permission Denied, but All the songs are at the same location in the system. 
PFA the log file
[exaile.log](https://github.com/exaile/exaile/files/8646363/exaile.log)

Hope this helps.

**Comment by luzip665** [comment]
So, please can you check if the files are read-only?

**Comment by ashishhowal** [comment]
Yes, I just checked, they're on read-only which was causing the error.
Thanks for the solution. :)

**Comment by luzip665** [comment]
You're welcome
