### ISSUE TITLE
Artist/Title tags from a stream, correctly set only the first time, when the artist tag is not supplied by the source

### ISSUE THREAD

**Issue by eri-trabiccolo** [exaile/exaile#812]
### Steps to Reproduce (for bugs)

1. Add radio playlist, e.g. any SomaFM playlist
2. Play it
3. Song's artist and title are correctly set
4. Wait for the next songs to be played, or double click on the track.

### Expected Behavior
I'd expect the Artist and Title tags to change accordingly.

### Current Behavior
The Title tag shows in the format Title - Artist, while the Artist tags sticks to the first played track.

This is because of this line:
https://github.com/exaile/exaile/blob/8064a98f3908fde2226beaf120b7a72586a21cfb/xl/player/gst/gst_utils.py#L285
Since the track is always the same, its artist tag was already set at the beginning.

### Possible Solution

I changed that line to:
`        if not etags.get('artist'):`

But I wonder if wouldn't be more correct to reset all the tags when a new song is detected...

### Environment
* Exaile Version: 
4.1.2-beta1+373b0fe

**Comment by luzip665** [comment]
I think there is no better way.
Artist would be set if it is submitted by the stream 
https://github.com/exaile/exaile/blob/8064a98f3908fde2226beaf120b7a72586a21cfb/xl/player/gst/gst_utils.py#L257
If not the title needs to be used.
