### ISSUE TITLE
I haven't been consistent about plugin version numbers

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#82]
As @bitterjug stated:

> You mean out of whack with each other. It'd be good to have consistent numbering. What to other projects do? Is it really necessary to have separate versions for the ones shipped with Exaile? Perhaps treat them as part of the core and just change the Exaile version number when they change."

@sjohannes what do you think about plugin version numbering? I'm not opposed to numbering the plugins the same as the core... the only argument is that it would make it harder to tell what changed, but I don't know if I care about that. We could write a script that fixes all of their versions upon release?

**Comment by sjohannes** [comment]
I think the only reason our plugins are versioned is because early versions of Exaile (0.2.x) had a plugin repository which let us push plugin updates independently of Exaile.

Considering our current release method, I don't think we need plugin versions at all.

**Comment by virtuald** [comment]
Well, I think there are some distros that package the plugins separately, so for them the versions would make sense.

Given that there are some plugins that are distributed externally from Exaile (though not many), we should probably retain version functionality. But perhaps things that are installed where the core plugins are can omit plugin numbers? ... but externally distributed plugins are probably installed in the same place, right?

The problem I guess with changing all the versions for each release is that there will be a lot of code churn each release. But maybe that's ok. We already have at least one commit per release, so if we had a tool that did that for us it would be ok. I think I would be more inclined to do this than completely omit versions, however.

**Comment by sjohannes** [comment]
What if, rather than changing all plugin versions for each release, we do it during `make install`? So after installing each plugin, we use `sed` to modify the `PLUGININFO` file.

**Comment by eri-trabiccolo** [comment]
Just my 2cents . I don't install exaile (I use just the git version), but in general a new source code should have consistent source files .. IMHO

**Comment by virtuald** [comment]
I don't like the `make install` route, better to have no plugin versions instead.

**Comment by sjohannes** [comment]
I'm fine with any of the options really. I can see the version display in the UI being useful for external plugins, so maybe we can still go for your original suggestion.

**Comment by bitterjug** [comment]
Is there a way to put, e.g. 'as exaile' for plugins distributed with
exaile, and have them show the exaile version number in the gui, and have
explicit version numbers for external plugins and have those show up in the
gui?

**Comment by virtuald** [comment]
@bitterjug sure, though there's nothing stopping someone from marking a plugin as 'core'.

I think starting with a 3.5 release, that we should go with my original suggestion -- change all plugin versions for each release. Add it to 'make dist' or something.

**Comment by genodeftest** [comment]
Are there any external plugins at all? If they don't exist we don't need to care about version numbers.

**Comment by virtuald** [comment]
The only one I can think of is [this](https://github.com/sunng87/exaile-doubanfm-plugin), there might be one or two more.

**Comment by virtuald** [comment]
I created a tool to set the version numbers to match the current version, and make dist will fail if you forget to run the tool.
