### ISSUE TITLE
Cannot see the quick buttons

### ISSUE THREAD

**Issue by phalgunlolur** [exaile/exaile#822]
### Steps to Reproduce (for bugs)
Open the player. For context, I have just updated to the latest release.

### Expected Behavior
Would expect to see the Quickbuttons at the bottom

### Current Behavior
Cannot see the Quickbuttons on the main player although it is enabled in the settings/plugins

### Environment

* Operating System and version:

* Exaile Version: 4.1.2
GStreamer: 1.18.5
GTK+: 3.24.31
GTK+ theme: Adwaita
Locale: English_United States 1252
Mutagen: 1.40.0
PyGObject: 3.40.1
Python: 3.9.7

**Comment by luzip665** [comment]
Hi.
Which version is shown for the plugin in Settings > Plugins?
Did you try to disable and enable again?

**Comment by phalgunlolur** [comment]
0.4.99. I tried disable and enable again, but that didn't do anything. I also had 0.4.98 saved on my drive, so I tried installing it (after disabling 0.4.99) but it gave me an error saying that it was an unsafe path

**Comment by luzip665** [comment]
May be the same problem as in #775 (https://github.com/exaile/exaile/issues/775#issuecomment-1000750278).
Can you have a look at  `%USERPROFILE%\AppData\Local\exaile\plugins`?

**Comment by luzip665** [comment]
Please just remove. 
In the meantime the most recent plugin version is shipped with 4.1.2

**Comment by phalgunlolur** [comment]
You mean 0.4.99, right? Because that's the one I got through 4.1.2

**Comment by phalgunlolur** [comment]
I could install 0.4.98 and that seems fine. Will test it out tonight and update this thread, if needed

**Comment by luzip665** [comment]
Sounds good.
But please, in Settings > Plugins select the quickbuttons plugin on the right. There should be the version 4.1.2
In a fresh local installation here it is.

**Comment by luzip665** [comment]
Solved, right?
