### ISSUE TITLE
Lots of thread related issues

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#83]
There are lots of places in Exaile's source code where we don't deal with multithreaded code in an appropriate/safe way. I'm a culprit just as much as anyone else when it comes to these things, but we really should deal with them at some point.

In particular, we should never interact with GTK widgets unless we're on the main thread. There's lots of places where this accidentally can happen, because our eventing system issues events from arbitrary threads -- for example, from a GST thread, or from a collection scan thread, or whatever.

**Comment by virtuald** [comment]
One thing I've been contemplating is creating a debugging tool that attaches itself to all the GTK widgets and checks what thread it's in when methods on them get called. Could be useful for tracking some of these down.

**Comment by virtuald** [comment]
After looking into this, apparently at one time the events were executed on the idle thread. Then in 9976a20e0ef9a1c82cd93b6fa13042f6788d4f98, e2c24b625718011b93481e8f32d5c58b3b3abe21 it looks like events were made to be synchronous, which resulted in the situation we have now.

At one time, the gtkrun decorator existed in guiutil, but was deprecated in 02e63dadaf9433c1cd56246cd507eac2d1e2b5a4, which was before events were made synchronous. There's a comment there about not needing this for events anymore -- but that's no longer true now that events are synchronous.

I think the right way to fix events (which will in turn then fix most of our thread related issues I suspect) is to keep them synchronous as they are now, except allow handlers to mark themselves as 'UI' via a parameter to event.add_callback, in which case they will be called in a UI-safe way. If you use threads_enter/threads_exit, the problem of course is that the GTK lock is not reentrant on Linux. So.. probably call it via idle_add instead of using a gtkrun-type of operation?

**Comment by virtuald** [comment]
For future reference: https://wiki.gnome.org/Projects/PyGObject/Threading

**Comment by genodeftest** [comment]
I just ran into a non-reproducible crasher (SIGSEGV) when opening and closing cover manager window repeatedly. I guess it is a threading issue too, but I can't tell.

**Comment by genodeftest** [comment]
Adding many files to playlist (e.g. from files or library panel) is freezing exaile. Looks like the adding (and possibly reading metadata from files) work is done in main thread.

**Comment by genodeftest** [comment]
Some crashers are caused by xlgui/cover.py which is not correctly threaded. I'll be working on that.

**Comment by genodeftest** [comment]
I am trying to fix xlgui/cover.py, but I can't get `event.log_event()` working when send to a different class/object.
An example: in 23aca49f17094d1d6e8d7a0cd0464882337b17f0 the `CoverChooserDialog.on_set_button_clicked()` sends a `cover-set` event. `CoverChooser._on_cover_set()`is never called though. What am I doing wrong?

**Comment by virtuald** [comment]
@genodeftest come to the IRC channel and we can yap.

**Comment by virtuald** [comment]
Looking at the code, it *should* work. You can use `--eventdebug --debug` to produce useful debugging output for this, it's possible there's a hidden exception.

**Comment by genodeftest** [comment]
With your tips and what we discussed on IRC I still couldn't fix this using events. Since python documentation states it can garbage collect cyclic dependencies I don't need those events anyway. I was thinking signals/events should be preferred over cyclic object dependencies but that seems to be not true. Thanks for your help anyway!

**Comment by genodeftest** [comment]
I'm still running into some freezes on git master from time to time. Using `--eventdebug` doesn't help.

**Comment by virtuald** [comment]
I know. It's still in a bad state. I'm still working on robotics stuff... I expect to get back to Exaile development in mid-March.

**Comment by genodeftest** [comment]
Ok.

Btw: I've found a nice way to debug these thread-related issues in exaile:
1. run gdb with `G_DEBUG=fatal-warnings gdb python2`
2. run exaile from gdb with `exaile --startgui`
3. do whatever could crash
4. debug with gdb using `py-bt` and `info threads`

___WARNING:___ This will freeze your X server. I recommend starting exaile on another X server or on a Wayland backend.

Just in case someone is running into this again.

**Comment by genodeftest** [comment]
Is there any logic or strategy exaile code follows when deciding which tasks to do in which thread? Or maybe any strategy one could follow? It would be good to have this documented somewhere.

**Comment by virtuald** [comment]
FYI, I added faulthandler to exaile, so if you have faulthandler installed, you can send SIGUSR2 to exaile and it will output stack traces of wherever it happens to be at the moment. Great for finding freezes.

**Comment by virtuald** [comment]
I'm going to close this. I haven't personally ran into thread related crashes in a very long time, and I think adding the explicit 'add_ui_callback' stuff for events fixed the event related issues. Further issues get their own bugs I think.
