### ISSUE TITLE
winmmkeys plugin does not respond to media keys anymore

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#830]
I think the `keyboard` module stopped giving us the key events. This seems to be [an issue on their end](https://github.com/boppreh/keyboard/issues/544), possibly related to recent-ish Windows changes.

[pynput](https://github.com/moses-palmer/pynput) is another module we can try. It uses ctypes so it's very simple to bundle (like `keyboard`, but unlike pyHook).

**Comment by rokm** [comment]
If bundling is concern, I can look into proper bundling of whatever solution/library is the best for us.

**Comment by dbolton** [comment]
I just downloaded 4.1.3-beta2 to test whether I could use multimedia keys, but I'm not able to enable the plugin. It says "Could not enable plugin! No module named 'pynput'". 

Any suggestions to get this working?

**Comment by sjohannes** [comment]
Yeah, there was [a piece of code](https://github.com/exaile/exaile/commit/92541ee467d5e37c702b08ca9c41fee006b46d4f) missing to actually add pynput to the installer. This will be fixed in the next beta/release.
