### ISSUE TITLE
Playback stops at end of queue

### ISSUE THREAD

**Issue by toto-42** [exaile/exaile#903]
Playback stops when the last track of the queue has been reached instead of playing tracks from the active playlist.

### Steps to Reproduce (for bugs)

1. Create a playlist with at least two tracks.
2. Play the first track from it.
3. During playback of the first track, enqueue a third track

### Expected Behavior

After the first track from the playlist ends, the enqueued track is played. When this track ends and the queue is empty, playback from the playlist is resumed.

### Current Behavior

On reaching the end of the queue, playback stops.
From the output of "exaile --debug":

15:53:39,423:ERROR   : Unhandled exception (gtk)
Traceback (most recent call last):
  File "/usr/lib/exaile/xl/player/gst/engine.py", line 660, in on_message
    play_args = self.engine.player.engine_autoadvance_notify_next(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/exaile/xl/player/player.py", line 518, in engine_autoadvance_notify_next
    next = self.queue.next(autoplay=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/exaile/xl/player/queue.py", line 169, in next
    self.current_position = 0
    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/exaile/xl/playlist.py", line 1010, in set_current_position
    raise IndexError("Cannot set position past end of playlist")
IndexError: Cannot set position past end of playlist

Locals at innermost frame:

{ 'oldposition': -1,
  'position': 0,
  'self': <xl.player.queue.PlayQueue object at 0x7fb0387dd8d0>}

### Environment

* Operating System and version: Debian Unstable/Sid (up to date)

* Exaile Version:

**Comment by toto-42** [comment]
Exaile: devel

GStreamer: 1.22.6
GTK+: 3.24.38
GTK+ theme: Breeze
Locale: en_US UTF-8
Mutagen: 1.46.0
PyGObject: 3.46.0
Python: 3.11.5

**Comment by virtuald** [comment]
That isn't the behavior I would expect. How would it even know which playlist is the active playlist?

**Comment by toto-42** [comment]
Hi,

exaile used to do this ;-)  I checked with Rhytmbox, it does this, too. Quoting from the documentation: ["Once a track has been played, it will be automatically removed from the Play Queue Source. Once the Play Queue is empty, Rhythmbox Music Player will play the source which was played before." ](https://help.gnome.org/users/rhythmbox/stable/playqueue.html.en)

**Comment by toto-42** [comment]
Hi,

sry for the late reply, busy weeks...

I've just installed and tested your branch, works for me! Thx for doing this. I've missed this feature very much.
