### ISSUE TITLE
Dark theme not working on Kubuntu Plasma

### ISSUE THREAD

**Issue by mister-bum** [exaile/exaile#914]
### Steps to Reproduce (for bugs)

1. Install Exaile from `ppa:exaile-devel`
2. Preferences -> prefer dark theme
3. Restart Exaile

### Expected Behavior
Exaile should start with a dark theme.

### Current Behavior
No visual changes of the appearance. 

### Possible Solution
The tool tip reads, that the dark theme does not work on all platforms. So maybe that's it, but I would like to double-check. Especially, as the buttons are barely visible , no matter whether or not the check box is ticked.

![image](https://github.com/exaile/exaile/assets/60568506/02b36924-4322-408e-8a46-55e34cda2bdd)

### Environment
Exaile 4.1.3
GStreamer: 1.20.7
GTK+: 3.24.38
GTK+ theme: Breeze-Noir-Dark-GTK
Locale: de_DE UTF-8
Mutagen: 1.46.0
PyGObject: 3.42.2
Python: 3.10.13

OS: Kubuntu 22.04
KDE-Plasma-Version: 5.24.7
KDE-Frameworks-Version: 5.92.0
Qt-Version: 5.15.3
Kernel-Version: 6.5.0-15-generic (64-bit)
Grafik-Plattform: X11

**Comment by sjohannes** [comment]
>  GTK+ theme: Breeze-Noir-Dark-GTK

That's strange; the GTK theme is already a dark theme, so my understanding is that that setting shouldn't have any effect. I'm not too familiar with how GTK does theming, though.

**Comment by mister-bum** [comment]
Sorry, for my late reply on this post. It works! I dont know why, but I tried it again recently and it's as dark as it's supposed to be. The only thing that does not seem to look correct is the menu icon for the cover - but maybe it's supposed to look that way, but that is a minor issue :-)
![image](https://github.com/exaile/exaile/assets/60568506/2f3d8df9-4471-42a6-b0ad-df8d52a25fe3)
