### ISSUE TITLE
Exaile loses playlists on crash

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#93]
Using exaile from git repository (master).

Sometimes when exaile crashes it looses its playlists. After starting exaile all playlists are gone.
It would be useful to do some kind of session backup like e.g. firefox does.

**Comment by genodeftest** [comment]
I just discovered that there is a "Save playlist" feature. It is accessible e.g. by right-clicking on the current playlist tab.
How about removing this menu button and just auto-saving all playlists?

**Comment by virtuald** [comment]
Right now, Exaile saves settings every 30 seconds. It could also save playlist data that has been updated too. 

This has bit me a few times. I tend to use the queue a lot, and on a crash it's lost also.

**Comment by virtuald** [comment]
The settings bit has been changed, but not the playlist save piece. Tracking it in #166
