### ISSUE TITLE
DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by grahamwhiteuk** [exaile/exaile#935]
The pipes module is currently being used in exaile and this is slated for removal in Python 3.13.  Hence, exaile is currently failing to build for Fedora 41 (and above).  

One example of problem code area:
https://github.com/exaile/exaile/blob/30a7ba5eafbf3fd1fd5a8810829daff74e2ffcad/tools/generate-completion.py#L91-L125

**Comment by grahamwhiteuk** [comment]
@sjohannes thanks for fixing this so quickly!  I may unearth some more deprecations as I try to build for Fedora 41 and above.

**Comment by oldherl** [comment]
Thanks for the fix. But it has been a long time since last release. Any plan to tag a new release?
