### ISSUE TITLE
Covers manager cannot complete "Fetch Covers" task and closes. Next time it opens, it never completes "Collecting albums and covers" task.

### ISSUE THREAD

**Issue by angelmir** [exaile/exaile#96]
Dear friends,
I installed Exaile on Linux Mint 17.1 two days ago. I installed it using the apt-get command, version 3.3.2. I added my collection folders to it - I have a big mp3 collection on my HD, over 50gb of music. Exaile processed my collection successfully. I started playing music without problems. Then, I opened the covers manager and it showed some albums had covers, others did not. I said I needed to retrieve over 4000 covers. I clicked on "Retrieve covers" and it started the process of retrieving covers from the internet. In the middle of the process, Exaile closed by itself. I reopened Exaile, I reopened the covers manager. But this time it wouldn't show any covers anymore, I would start "Collecting albums and covers". The progress bar started moving. At about 40% of the way, it would stop moving completely, even after a few hours. I uninstalled Exaile twice, deleted the Exaile folder in .local/Share. Installed Exaile again twice, did the same process previously described twice, but the result was always the same... I hope you can help me.
Regards,
Ângelo
![screenshot-2015-05-28-124338](https://cloud.githubusercontent.com/assets/12646306/7864734/55c44390-053a-11e5-8d5a-a117c4dd871b.png)

**Comment by virtuald** [comment]
Can you try the latest stable release of Exaile (3.4.5)? There were various cover related fixes made in the 3.4.0 release that may solve your problem.

**Comment by angelmir** [comment]
Dear Dustin!
How can I install it on Linux Mint? I mean, the latest version?
I am kind of a newbie on Linux!
Thanks!
Regards,
Ângelo

**Comment by virtuald** [comment]
You can install Exaile the same way that you install most other Linux programs from source. Assuming that you have all the dependencies installed, download the latest release from our website, untar it, and run the following:

    make
    sudo make install

**Comment by genodeftest** [comment]
Closing because we have not seen an answer in years.
