### ISSUE TITLE
Moodbar: Support Clementine's cache

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#98]
Not too difficult to let Exaile read Clementine's cache, in addition to .mood files and our own cache. Can also allow write access, with big warning since we can't guarantee the format.

Quick overview of Clementine's Moodbar cache format (essentially QNetworkDiskCache):
- Path: `~/.cache/Clementine/moodbarcache/data7/X/YYYYYYYY.d`.
  - URI &rarr; SHA1 &rarr; first 64 b &rarr; uint64 (native order) &rarr; base 36 (lowercase) &rarr; first 8 chars &rarr; `YYYYYYYY`.
  - Last `Y` &rarr; ord &rarr; mod 16 &rarr; hex (lowercase) &rarr; `X`.
- Content: 8 B stuff, 4 B URI len (network order), URI, 28 B stuff, data (3000 B moodbar).

**Comment by genodeftest** [comment]
I wouldn't want to do this:
* Clementine's format might change at any time. We should only do this in my opinion if we contact the clementine developers prior to that.
* Clementine's cache belongs to Clementine, not to Exaile. A separate library (with separate cache folder) would be preferred.

**Comment by sjohannes** [comment]
It's not a big deal anyway. I'd rather concentrate on the big problems with Moodbar, mainly that there is still no alternative version to the Gst 0.10-based one.
